### ISSUE TITLE
Hydra 70's

### ISSUE THREAD

**Issue by Nerfclasher** [PapaJoesSoup/BDArmory#1]
The Hydra 70 sound is either too long, or bugging out.

When in ripple mode hold your fire button down and the sound will play over itself again and again and again, and continues to play at the cockpit view (haven't tested the world view) until the rocket hits the ground. 

from [](https://github.com/BahamutoD/BDArmory/issues/54)

**Comment by SpannerMonkey** [comment]
I can confirm this one is still current, sound is stuck in perpetual loop until rocket impact, tested all situations and error persists

**Comment by SpannerMonkey** [comment]
Further to the above issue, the problem is not just with standard BDA rockets but any type of rocket.  I have a custom rocket turret and associated custom rockets in Boomsticks and these too display the sound looping issue. Will check sound files for errors

**Comment by Nerfclasher** [comment]
This must be a serious issue that needs addressed fast because it could fixed by making the sounds  quieter as they move away

**Comment by Nerfclasher** [comment]
Looking in the files the sound loops repeatedly

**Comment by jrodrigv** [comment]
I will work on this next. I will keep you updated with my findings.

**Comment by jrodrigv** [comment]
@Nerfclasher @PapaJoesSoup I just fixed this issue on the support branch. Can you test it?
