### ISSUE TITLE
CKAN support

### ISSUE THREAD

**Issue by embix** [PapaJoesSoup/BDArmory#10]
As the original BDArmory isn't currently actively supported and this repo is, we should make CKAN somehow work again. Either by (1) using a new name and generating a metadata file or (2) by taking over the original one.

see: https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN

**Comment by Nerfclasher** [comment]
We don't support ckan and we send metadata via spacedock and second it is already on ckan and also go to ckan for support if you have a issue with ckan

**Comment by PapaJoesSoup** [comment]
Please send your request to the CKAN team.  Conversely, you might be able make the needed changes to the NetKan file and submit a PR if you wish.  It is our policy not to provide support for CKAN as we have no control over the process beyond listing when deploying to SpaceDock.
