### ISSUE TITLE
BDArmory doesn't work on the new update for kerbal space program!

### ISSUE THREAD

**Issue by MrTomfour** [PapaJoesSoup/BDArmory#100]
When my KSP updated my BDArmory stoped working none of my weapons work anymore, nothing works. kinda making mad. if someone has fixed the problem please let me know! The version of KSP i got that made BDArmory stop working was Loud and Clear version. Is there a updated version of BDArmory I need for BDArmory to work on this version of KSP or what? Yes I have checked to see if BDArmory is in the right folders and it is. Any help would be amazing please!

**Comment by gomker** [comment]
Have you downloaded the latest update from here : https://github.com/PapaJoesSoup/BDArmory/releases

**Comment by gomker** [comment]
I will close this issue out now as there has been no update for a week.

When reporting issues please provide the following information:

- Version of KSP
- Version of BDA
- OS Build and Version
- Link to a full KSP log if reporting a problem

[See this for more information
](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)
