### ISSUE TITLE
AI Pilot is unable to use Rapiers in Air Breathing mode if landed

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#102]
Reproduction Steps:

1- Build a plane with Rapiers as the engine
2- remove all oxidizer
3- stage engines and activate AI Pilot

The craft will not take off since the AI pilot is trying to use the closed loop mode like it uses the afterburners on a Panther engine ... if the craft is landed or below it's cruise speed in flight, then it will switch to the more powerful mode of the engine which in this case is closed loop mode

For atmospheric AI competitions, this precludes a competitor from using the Rapier unless said competitor adds Oxidizer to account for this

**Comment by jrodrigv** [comment]
I'm going to fix this issue using the following approach. Only multimode engines with Wet & Dry modes will trigger the Toggle mode. For other engines like the rapier, the second mode will not be used.
