### ISSUE TITLE
[Feature Request] Warhead expansion

### ISSUE THREAD

**Issue by demonfiren** [PapaJoesSoup/BDArmory#106]
Currently only one variety of warhead exists in the mod, the aptly-named Small Warhead.
I would like to request an expansion of warhead sizes and especially the addition of a 0.35 metre variation (the same profile as smaller Sounding Rockets components, which are excellent for building small missiles or guided submunitions).
Furthermore inline versions of at least the existing explosive would be very useful for creating more aerodynamic cruise missiles, among others.

Finally, and only as afterthought, if cluster warheads are possible, they may be a worthwhile addition - especially with a manual or distance-to-target trigger.

**Comment by TheDestroyer111** [comment]
AFAIK one of the devs is already working on a modular warhead system that can allow different warhead sizes. @PapaJoesSoup ? @gomker ? @jrodrigv ?

**Comment by gomker** [comment]
Yes, currently we are working on overhauling the Modular Guidance system as well as features of the `BDExplosivePart` which is the part module for the Small Warhead.  There will be a way to control the amount of "HighExplosive" for the custom warheads.

**Comment by Guard13007** [comment]
I hope that we can have an adjustable warhead part (like the adjustable missile rails) instead of a bunch of differently-sized warhead parts. Please devs, don't make more parts. o.o

**Comment by jrodrigv** [comment]
It doesn´t make sense to me to re-invent the wheel again.

We are not going to create an adjustable warhead part like the adjustable missile rails. Instead of doing that, I prefer to support other mods like TweakScale and ProceduralParts that are very well known mods and they do exacty what we need.

**Comment by Guard13007** [comment]
That's an even better idea. ^^

**Comment by Nerfclasher** [comment]
@jrodrigv is this going to be a Christmas present maybe?

**Comment by jrodrigv** [comment]
This issue has been already implemented and it will be released.
