### ISSUE TITLE
Many pointless questions on wiki WIKI

### ISSUE THREAD

**Issue by TheDestroyer111** [PapaJoesSoup/BDArmory#111]
There are currently countless stupid posts on the BDA Wikia with people saying that their WM doesn't appear in part list, WM window doesn't appear on toolbar etc., most likely without even reading my answers to previous questions of the same nature (and even if they read previous comments, they usually completely forget about the entire wiki and don't reply when I ask them to eg. give a screenshot of their GameData folder). Is there any possibility that it is made clear that such pointless questions are something unwanted?

**Comment by PapaJoesSoup** [comment]
The Wiki, has gone the way of the dodo... it is now contained in KSPedia, ingame.  I will be removing links to the old Wiki, and redirecting them to the inGame KSPedia.  

Unfortunately, you cannot stop such posts, as there are as many "stupid" questions as there are people in the world.  and it is my guess, the there are as many stupid questions as there are sentient beings in the universe... ad infinitum...

**Comment by DoctorDavinci** [comment]
Dolphins definitely ask stupid qiestions ... normally related to fish 

The wiki is now, for all essential purposes, defunct ... all pertinant information previously contained in the wiki has now been imported to an in game KSPedia

Consult it ... there is much valuable information contained within

**Comment by gomker** [comment]
Cleaning up and closing out issues.

**Comment by Guard13007** [comment]
Related to this @PapaJoesSoup you (or someone with access) should edit the settings of this repo to remove its wiki..or just take the brief edit I just did pointing people to the in-game KSPedia instead of the defunct wiki.
