### ISSUE TITLE
AI Pilot does not use controls to eliminate horizontal rotation when below minimumAltitude

### ISSUE THREAD

**Issue by Gedas-S** [PapaJoesSoup/BDArmory#112]
When a plane is below minimumAltitude the AI does not try to correct for horizontal rotation of the plane. This is a small problem for planes with strong yaw stability, but for planes with weak yaw stability entering the minimumAltitude zone at high horizontal rotation speed it often results in an avoidable flat spin.

To replicate I made a plane which is a bit unstable on the yaw axis. It flies just fine with normal autopilot (or on manual with SAS on), but when in liftOff mode it starts spinning to the side and the AI does not touch the Yaw controls at all.
https://vimeo.com/194536619

I suspect setting the goal based on vesselTransform.up is the problem (BDModulePilotAI line 1356), setting it based on srf_velocity might work better, however srf_velocity may be zero, which would be bad. :)
`Vector3 forwardPoint = vessel.transform.position + Vector3.ProjectOnPlane(vesselTransform.up * 100, upDirection);`

Also including the test craft I used (just rename to .craft).
[Yaw Stability Test Craft.txt](https://github.com/PapaJoesSoup/BDArmory/files/634558/Yaw.Stability.Test.Craft.txt)

**Comment by Gedas-S** [comment]
Tried this myself, changing it to something along the lines of
`Vector3 forwardPoint = vessel.transform.position + Vector3.ProjectOnPlane((vessel.horizontalSrfSpeed < 10 ? vesselTransform.up : (Vector3)vessel.srf_vel_direction) * 100, upDirection);`
fixes the problem.

Shall I create a pull request?

**Comment by Nerfclasher** [comment]
> Vector3 forwardPoint = vessel.transform.position + Vector3.ProjectOnPlane((vessel.horizontalSrfSpeed < 10 ? vesselTransform.up : (Vector3)vessel.srf_vel_direction) * 100, upDirection);
yes

**Comment by jrodrigv** [comment]
Thanks for this finding and the fix. I´m going to merge yout PR

**Comment by Gedas-S** [comment]
Thanks for the nice mod. :)
