### ISSUE TITLE
weapon manager

### ISSUE THREAD

**Issue by milos55** [PapaJoesSoup/BDArmory#116]
I can open weapon manager, but when I click on weapons or modules and the other thing, they show that they are clicked but I can't see anything open. Here is a picture
![untitled](https://cloud.githubusercontent.com/assets/24484185/21065445/8e039478-be60-11e6-86c6-95583b8d11e8.png)

**Comment by DoctorDavinci** [comment]
KSP Version? ... BDAc version? ... Log files?

Check that your KSP version is compatible with the BDAc version you are trying to use ... there is a white block in place of where the BDAc weapon manager button is which leads me to suspect that your likely using the 1.2 pre-release 

Either the above is true or somehow you have made a mistake installing the mod

**Comment by milos55** [comment]
ksp version is 1.2.1.1604 you were right
bda version is for 1.2
here is the ksp log 
[KSP.txt](https://github.com/PapaJoesSoup/BDArmory/files/643926/KSP.txt)
here is the output log
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/643927/output_log.txt)
no mistakes made while installing i just moved the gamedata file to ksp gamedata, I only changed the bda gamedata name to gamedata 1 because i have other mods.

**Comment by DoctorDavinci** [comment]
So you have a gamedata2 inside your gamedata folder ... this is wrong and a big no no

When installing any mod put the contents of the gamedata folder contained in the mod zip file into the KSP gamedata folder ... do not put a gamedata inside of a gamedata

**Comment by milos55** [comment]
no no no here a pic
![untitled](https://cloud.githubusercontent.com/assets/24484185/21079135/240f0286-bf88-11e6-8233-d6afba317c19.png)
they are all alone and work execpt the ones that are not for ksp 1.2 and bdarmory

**Comment by milos55** [comment]
should they be like this
![untitled](https://cloud.githubusercontent.com/assets/24484185/21079156/991e3538-bf88-11e6-8826-8ab69a38f5c3.png)
i took all of them from the mods gamedata and just put them in the ksp gamedata folder.

**Comment by milos55** [comment]
it works now thanks
