### ISSUE TITLE
Low TWR AI pilot issue "proof"

### ISSUE THREAD

**Issue by FourLeopard** [PapaJoesSoup/BDArmory#123]
As you can see the AI pilot cant seem to handle low twr planes and only seems to orbit at the minimum altitude. Changing steer damping, steer factor, idle speed etc. doesn't help either. 

https://youtu.be/hNT3qbEN2_8

**Comment by DoctorDavinci** [comment]
Could you post your logs and the craft file

Just from a cursory glance (which is all I can get with your video) it appears that your plane is nose heavy ... this is why when it gets to the minimum altitude it tends to drop below the minimum when it begins to turn

**Comment by gomker** [comment]
Please do not open up another issue for one you already have open

#105
