### ISSUE TITLE
shortName is not functional for MissileBase class

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#126]
`shortName` when defined for `ModuleWeapon` and others works however, it is not working with `MissileBase` 

Recreate by setting `shortName` in any missile configuration and you will not see the name set, it will default to the part's title.

**Comment by gomker** [comment]
@jrodrigv  can you take a look at this one, I am going in circles in the code and do not see why this is not working.  The only difference is the new class structure

**Comment by jrodrigv** [comment]
I will do!

**Comment by jrodrigv** [comment]
@gomker  Sorry for the delay. 

MissileBase is not meant to be used as a normal Module as we do with MissileLauncher. Currently, MissileBase is just an abstract parent class with the common functionality to both child classes MissileLauncher and BDModularGuidance.

**Comment by gomker** [comment]
Yes, and the `shortName` has moved into that abstract parent class and no longer seems to inherit the value from PartModule (MissileLauncher)

**Comment by jrodrigv** [comment]
Sorry but maybe I'm not understanding the problem. For example for the sidewinder.cfg we have
shortName = AIM-9
title = AIM-9 Sidewinder Missile

The shortName is then used properly by the Weapon Manager when the weapon is listed and also for the vessel name when it is fired,

**Comment by gomker** [comment]
Let me do some tests again, I tried adding a short name to RBS15 Cruise Missile and it would not update.

**Comment by gomker** [comment]
Hmmm, I don't know what I was doing before, it seems to be working OK :)
