### ISSUE TITLE
Weapon Manager GUI Window position

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#13]
This is could be a feature request or a bug depending on the way you look at it.
The weapon manager GUI or other module windows (FLIR Radar) do not remember their positions. 
I would request that they remember their positions similar to MechJeb windows and are persistent across any crafts you may be jumping to.

**Comment by Nerfclasher** [comment]
I consider this a feature request but it could be considered a bug

**Comment by DoctorDavinci** [comment]
This is definitely a feature request although one that would solve much frustration for the users of BDAc

**Comment by PapaJoesSoup** [comment]
I think window persistence is a pretty standard feature with KSP mods.  It is a feature request, but should be addressed.  I have some code that does this in other mods already.  Let me see what it would take to port it over to BDA.

**Comment by PapaJoesSoup** [comment]
Ok, I've implemented window position persistence with the settings window and the main toolbar window.  what other windows need this feature?  This will help me track them down in code as they are NOT obvious...

**Comment by gomker** [comment]
A quick list from a hierarchy perspective

Weapon Manager
      - FLIR
      - RADAR
      - RADAR Warning
      - Wing Commander
      - Vessel Switcher

The rest are show/hide within Weapon manager I believe

Thanks

**Comment by PapaJoesSoup** [comment]
Thanks that helps loads.

**Comment by gomker** [comment]
It remembers! Changes merged in master.

**Comment by Guard13007** [comment]
This isn't in the latest release yet, is it?
