### ISSUE TITLE
Certain Missiles Failing clearance check

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#130]
Missiles with boosters (like SMArmory ASM13) are failing forward clearance check causing fire by Action Group to fail

https://github.com/gomker/BDArmory/blob/Feature_ProximityDetonation/BahaTurret/MissileFire.cs#L4231

**Comment by SpannerMonkey** [comment]
Further research on this bug 
To remove possible model problems that contribute 

Unit test on Long range boosted missile x1  which displays this problem and cannot be fired from most launchers with clearance check enabled

Remove all except primitive colliders . fail
Adjust model bounds to prevent possible interference . fail
Remove all external fins. fail
Remove booster collider leaving simple capsule collider on missile body. fail
Remove all colliders .  FAIL???
Change node assignment method to pre NODE method. fail
Remove any part animation . fail 
Remove booster . Pass
Rework and try all possible combinations of part hierarchy (11 variations) . Fail
Offsetting missile using in game tools , to clear any obstruction, way beyond reasonable limits. fail

 Launcher types tested 
 multiple rail  launcher turret. possible rail interference expected. PASS

24 cell VLS unit  fail

Single TEL launcher with fully retracting mast, which leaves missile hovering above a plate with no objects around missile circumference FAIL???   The failure of this unit to launch a missile makes no sense, within my understanding of the system,  there are no obstructions whatsoever anywhere near the missile.  

Missiles tested 2 x  radar guided ground to air missiles. 

Short range boosted x1   Passes all tests  this missile is identical to the long range version in all but booster length. This short range boosted missile CAN be fired with clearance check enabled from all the launchers described 

All launchers operate  normally for any other missile type that fits within the launcher geometry

I currently have 4 missiles of different dimensions and appearance displaying the same symptoms of  clearance failure.  I have carried out the above procedure  on all but one and in every case the only successful firing comes once booster is removed. 
 I also have 5 other boosted type missiles that fire perfectly in any situation in which they fit the launcher.

**Comment by gomker** [comment]
The clearance checks I believe were intended to detect the presence of a cargo bay. I think there is some flaw in the logic that is triggering (why yet to be determined) My first thought was the booster, as the ASM13 is stacked one on top of the other.

Are you seeing this issue with any missiles that are of one single piece? I cannot recall if I ran into this problem with missiles other than "multi part" ones with boosters. But I do see that you removed the boosters in your testing. A bit of thinking out loud right now.

**Comment by SpannerMonkey** [comment]
Yes I have a single part boosted missile that displays exactly the same symptoms .  you will be able to access 3 of the affected missiles in the downloads made available earlier and all the tested launchers
To clarify there are two virtually identical missiles in SMM the Aster 15 and the Aster 30 differing only in booster length ,  the 15's fire from most launchers without issue while the 30's will not.

**Comment by gomker** [comment]
I wanted to note that I was seeing the clearance check fail even without launchers. My test has the missiles attached to a Flat platform pointing straight up.

**Comment by gomker** [comment]
Fixed by TheDogKSP
