### ISSUE TITLE
Weapon Manager Not Recognized

### ISSUE THREAD

**Issue by Pichuadam** [PapaJoesSoup/BDArmory#131]
I downloaded the mode, and I took the 'BDArmory Folder' Out. When I attach the Weapons Manager, it says that it is not found. Help?

**Comment by jrodrigv** [comment]
Sorry but you need to provide the logs if you want us to help you.

**Comment by DoctorDavinci** [comment]
From what I can tell, with the wealth of information you have provided us, is that the parts are able to be attached to your craft but will not be recognized when you launch said craft

This tends to happen for 2 reasons, which are:
1 - you have incorrectly installed BDAc ... Try reinstalling if this is the case
2 - You are using the wrong version of BDAc for the version of KSP that you are using

Please provide us with the log file and other information as described in the following thread: http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/
