### ISSUE TITLE
Guard Mode + Slave turrets 

### ISSUE THREAD

**Issue by docmop** [PapaJoesSoup/BDArmory#132]
Setup:
- Turret Weapon
- Tracking Radar
- Guard Mode ON
- Slave Turrets ON
- Vessel is the active vessel

Behaviour:
As soon as the Guard Mode selects a weapon, the turret rotates to the mouse instead of aiming at the locked target.

Suggestion:
Slave Turrets should deactivate mouse aim.

Version used: v0.11.1.6

**Comment by gomker** [comment]
Yes, I have noticed this myself on occasion, I will investigate our options.

**Comment by gomker** [comment]
New release is forthcoming with options to choose target preferences , Air, Ground, Missile and this should not be an issue anymore.
