### ISSUE TITLE
AI with different fighting styles

### ISSUE THREAD

**Issue by G-U-A** [PapaJoesSoup/BDArmory#139]
This is a feature request for ai with different fighting styles.

Uses: You might want a plane that just does turn fighting to get behind its opponent as it has high maneuverability or a plane that uses boom and zoom tactics to get strafing runs on a  plane its faster than but turns worse than and quickly run away instead of turn fighting.

this would mean a wider variety of competent planes could be flown.

Another example would be for land units which could operate without needing to climb to altitude or perhaps even move fully using wheels for mobility.

This would allow more functionality for ground units and even ships.

**Comment by Hector919** [comment]
sorry, I made a mistake when referencing issues - please ignore the reference from issue #173

**Comment by supedog** [comment]
and we need submarines

**Comment by gomker** [comment]
Closing as this is close to issue #172
