### ISSUE TITLE
Bombing command for WingCommand

### ISSUE THREAD

**Issue by MuricanJeb** [PapaJoesSoup/BDArmory#141]
This would be useful for when you have a bomber formation and you want to drop bombs without switching crafts all the time. So for example you open your cargo bays (You can already make the AI do this with action group command) but say you have more than 10 bombs (Because there are only 10 action groups)

What do you guys think?

P.S. I understand if to hard to code, it's probaly impossible.

**Comment by DoctorDavinci** [comment]
Use the 'Attack Pos' button in wing commander to have your wingman to attack an area ... Consult the ingame KSPedia for more information on the wing commander module

Currently you are not able to designate a specific target among many targets grouped relatively close to each other ... Consult the following video: https://www.youtube.com/watch?v=h2i-wZ6tD24&t=314s
