### ISSUE TITLE
AI Pilot 'Freezes' and flies straight after some time during duels

### ISSUE THREAD

**Issue by supergamervictor** [PapaJoesSoup/BDArmory#142]
As mentioned in the BDA forum thread, after an undetermined varied amount of time in duels, the AI simply flies straight ahead, constantly changing between weapons and does not return to circular flight path when turning off guard mode. In fact, turning off and on the AI result in it simply flying straight ahead. 
This has been tested on a stock 1.2.2 KSP with BDArmory and the test craft. In most instance, the aircraft that is being viewed enters this behavior.

https://www.dropbox.com/s/duvr6vdyjt124im/StockBDA2.rar?dl=0

**Comment by MuricanJeb** [comment]
Apperantly, I had this bug yesterday. The AI pilot would fly straight for some time and then turn a bit, fly straight, turn a bit, and that is all it does. Even when I shoot at it and score a hit, it just keeps on flying straight or making slight turns.

**Comment by MuricanJeb** [comment]
I can comfirm in a 1v1 dogfight this always happens. It just happened right now.

**Comment by jrodrigv** [comment]
I will try to reproduce this issue using the support branch

**Comment by DoctorDavinci** [comment]
Can you upload the craft you were using when this happened

**Comment by jrodrigv** [comment]
@supergamervictor @MuricanJeb  Would you mind to test this scenario using this dev version of https://github.com/jrodrigv/BDArmory/archive/support.zip

Just delete your bdarmory folder and drop in the folder Distribution/GameData/BDArmory from the Zip file

**Comment by MuricanJeb** [comment]
I actually redownloaded BDA (NOT THE LINK ABOVE) and now in duels it's fine...

**Comment by supergamervictor** [comment]
Two test with the dev version, resulted in the same issue.
Stock BDA, 64bit, BDA Test Plane A, Using Infinite Fuel and Electricity, No Crash Damage, No Heat Limit and Unbreakable Joints.
First test resulted in the AI  I was controlling to climb and lose speed. Turning off Guard Mode does not stop this behavior and continues to climb.
Second Test, I removed all weapons accept the vulcan. After some time, the one I was controlling flew straight and unresponsive to gunfire from the back and switching off guard mode. 

Logs : https://www.dropbox.com/s/kind7upsr3nn2hn/TestingLogs.rar?dl=0

**Comment by MuricanJeb** [comment]
I also forgot to metion I had to delete my KSP and reinstall it (Im a steam user so I can re install)
@supergamervictor Maybe try reinstalling KSP and then use original BDA, not the link, and see what happens.

I know that means RIP craft files, but at least theres a chance to get BDA working.
But if it still doesn't work, you can slap me in the face with a big, fat, wet, fish 🐟

**Comment by jrodrigv** [comment]
@supergamervictor  please can you attach your craft files? I need them to reproduce the issue. So far It was not possible for me to reproduce it?

**Comment by supergamervictor** [comment]
@jrodrigv The craft files I used for testing are the ones included in BDA, ie Gamedata/BDArmory/craft/BDA - TestPlaneAI - v3.

**Comment by jrodrigv** [comment]
So I have been  doing several 1 vs 1 competition mode at 8 km using that craft and everything works as expected.

But I have an idea about what can be happening. Can you try to force 50 km physics range and re-test it?

**Comment by jrodrigv** [comment]
Can anyone confirms if this still happening on the lastest BDArmory release and KSP 1.3.1?
 I have to say that I have not seen this again.

**Comment by supergamervictor** [comment]
I'm still using KSP 1.2.2 for now. I can install the latest version and do some stock testings. I'll inform you of any developments.

**Comment by Vladokapuh** [comment]
It's still happening for me. Fresh install of KSP 1.3.1, fresh download of BDAc 1.0.0. (the most recent release)
Other mods i use are:
AirplanePlus
AirplanePlusTweakscale
CameraTools
FerramAerospaceResearch
Firespitter
ImprovedChaseCamera
KAX
KerbalEngineer
KerbalJointReinforcement
ModularFlightIntegrator
MouseAimFlight
PhysicsRangeExtender
Tweakscale

ModuleManager is 2.8.1

All mods in most upto date versions i could find.

Video: https://www.youtube.com/watch?v=e6Q2OqVUSlo

Also im attaching planes used in the video. Only difference is removed all external equipment besides Vulcans. 

[SPH.zip](https://github.com/PapaJoesSoup/BDArmory/files/1524758/SPH.zip)

**Comment by Vladokapuh** [comment]
I forgot to add a few things:
-i changed PRE range from 100 to 50km, issue is still present.
-i noticed it seems to happen to the plane you're looking at
-reengaging AI will not "unstuck" it, but switching vessels will
-after switching vessels, it will get "stuck" again after a few turns

In one of duels, plane 2 shotdown plane 1 which got "stuck", and after plane 1 remains dropped below combat altitude, plane 2 got "stuck".

**Comment by Vladokapuh** [comment]
Updated BDAc to 1.1.0 public beta.
Evrything else stays unchanged.

Uploading logs (as requested on forums), and video just incase.
This time bug occurs, plane visibly starts just flying forward, and after letting it fly like that for a short moment, i switch vessels to wake it up. (otherwise it will just accelerate to 800m/s, as set, and fly out of physics range)

[logs.zip](https://github.com/PapaJoesSoup/BDArmory/files/1641023/logs.zip)

https://www.youtube.com/watch?v=dPXG-VfLu9I

**Comment by Gedas-S** [comment]
Should be fixed with #488
