### ISSUE TITLE
Turrets always receive full damage, no matter armored or not

### ISSUE THREAD

**Issue by flywlyx** [PapaJoesSoup/BDArmory#144]
Since the bullet fail to penetrate armor should not damage the turret function so much, we should able to recognize if bullet is explode inside armor collider or not .
Then an armored turret, could add armor colliders to act as armored. And armor don't need a extremely high maxtemp to prevent been destroyed by 5mm hand gun.

**Comment by MuricanJeb** [comment]
Armor is WIP, so there is probaly gonna be some bugs. Also, I don't think they added armor to turrets.

Infact, the new armor thing was bullet penetration, not really armor.

**Comment by flywlyx** [comment]
BDArmor.ca now defines armored part and armor collider, adding an additional 
> bool lackofpenetration = (armor == null) ?false:true; //line 265
> heatDamage = lackofpenetration? heatDamage:heatDamage/8; //line 332
to PooledBullet.ca will achieve similar effect.

**Comment by Guard13007** [comment]
@MuricanJeb Can you explain / link to where the armor mechanic is explained?

**Comment by flywlyx** [comment]
@Guard13007 
You can get armor definition here "BDArmory/BahaTurret/BDArmor.cs"
You define the armor there, and each hit will catch the armor and do the penetration.
2 conditions the damage will be reduced.
`                            if (!penetrated) //Ricochet
                            {
                                heatDamage = heatDamage / 8;
                            }
                            if (fulllyPenetrated)//Overpenetration
                            {
                                heatDamage /= 8;
                            }`
The problem is, full damaged is deployed no matter bullet explode inside armor or core.
Which means, you can't make an armored turret.

**Comment by AbtdQ** [comment]
@flywlyx 
I am working on a new damage system based on PartModule which will solve the problem.

**Comment by Guard13007** [comment]
@flywlyx I meant from a player's perspective, sorry for the confusion.
