### ISSUE TITLE
I dont have all parts

### ISSUE THREAD

**Issue by hejsxdd** [PapaJoesSoup/BDArmory#146]
I installed the mod for ksp but alot of parts are missing like weapon manager and turrets and 

the mod folder looks like this
ksp->gamedata->bdarmory

**Comment by DoctorDavinci** [comment]
KSP.log please

**Comment by hejsxdd** [comment]
where can i find the .log file?

**Comment by DoctorDavinci** [comment]
In your KSP directory ... KSP.log is the filename

**Comment by hejsxdd** [comment]
http://pastebin.com/Vd6gfiGS

**Comment by jrodrigv** [comment]
I can't see nothing on that link. You can just drag and drop the log file here

**Comment by hejsxdd** [comment]
word limit

**Comment by DoctorDavinci** [comment]
Try dropbox or google drive

**Comment by flywlyx** [comment]
Could you use Mehcjeb?
