### ISSUE TITLE
Is this BD Armory continued? 

### ISSUE THREAD

**Issue by seads23** [PapaJoesSoup/BDArmory#147]
I am looking to install the Future Weapons mod, and it says that I need BDaC for it to work. Is this the right thing for me to install if I want BDaC, or is there someplace else I need to look? Thanks!

Future weapons mod: https://spacedock.info/mod/209/Future%20Weapons

**Comment by DoctorDavinci** [comment]
Yes, this is the mod that you are looking for

Click on the 'releases' tab to download ... enjoy
