### ISSUE TITLE
[Support Branch] Cluster bomb explode on load.

### ISSUE THREAD

**Issue by Qromodynmc** [PapaJoesSoup/BDArmory#151]
Hello, 
Im not sure if this is right place to say but i found an issue in latest bda dev build
I loaded up cluster bombs on one plane, click to lauch and even before loading everything, clusters started to explode. I decided to try in stock and got same problem. I know dev builds can be buggy, i just decided to tell so you can fix it before release. Here are some screenshots about it;
http://i.hizliresim.com/O0AZyn.jpg (example plane)
http://i.hizliresim.com/z35VJR.jpg (starts to explode even in black screen)
http://i.hizliresim.com/yE5lzn.jpg (oddly, tail section stays there, also i can still drop them like usual bombs.)

thanks for your efforts, good luck on your work.

**Comment by jrodrigv** [comment]
Thanks for the feedback! I will take a look.

**Comment by jrodrigv** [comment]
Hi @Qromodynmc . I think I've fixed the issue. Would you mind to re-test again using the support branch?

Thanks!

**Comment by Qromodynmc** [comment]
Yeah i can confirm it works properly now! thanks for efforts.
