### ISSUE TITLE
Reenable guard mode setting in vehicle assembly

### ISSUE THREAD

**Issue by DracheTek** [PapaJoesSoup/BDArmory#156]
For the convenience of military mission making, it is better re-enabling default guard mode setting in vehicle assembly building, so that we can make vehicles spawned with guard mode enabled, without needed to tweak them in .craft file.

**Comment by DracheTek** [comment]
Currently I am trying to use standby mode of AI computer. I am not sure if it works well with ground vehicle.

**Comment by DoctorDavinci** [comment]
You can set up an action group to turn on guard mode once your craft is loaded

As for using the AI Pilot on ground vehicles, this is not what the AI Pilot was designed to do ... you will have little success with this as the AI Pilot (notice the 'Pilot' part) is meant to be used with aircraft and not ground vehicles

**Comment by flywlyx** [comment]
AI will go straight and try to take off. Maybe try them on the highland will help?

**Comment by jrodrigv** [comment]
I don't think this is an issue or request.

**Comment by Guard13007** [comment]
@jrodrigv I am confused by your statement, he is clearly requesting the ability to set the default state of guard mode from within the VAB/SPH, for convenience.

**Comment by jrodrigv** [comment]
Yes, but it only takes one click of a mouse or your keyboard to enable the guard mode after spawing a vessel. 

I don't mind to reopen this request if more people thing that is very useful to have.

**Comment by Guard13007** [comment]
It's something I commonly forget while launching several defense vessels to set up a scenario. While it is relatively simple to activate manually, it is one extra step in a slow and tedious process due to KSP's loading times, which makes it harder to remember.

**Comment by jrodrigv** [comment]
Fair enough :) it is also very easy to implement.

**Comment by gomker** [comment]
In latest release https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.3.0.0
