### ISSUE TITLE
RocketLauncher will not fire with short name selected in WM

### ISSUE THREAD

**Issue by flywlyx** [PapaJoesSoup/BDArmory#157]
RocketLauncher will fire with turret activated by toggle turret. will not fire with short name selected on WM.
RocketLauncher.cs#L431
`else if((!weaponManager || (weaponManager.selectedWeaponString != GetShortName() && !weaponManager.guardMode)))`
Should be 
`else if((!weaponManager || (weaponManager.selectedWeaponString == GetShortName() && !weaponManager.guardMode)))`

**Comment by jrodrigv** [comment]
Thanks for the solution. Fixed applied
