### ISSUE TITLE
Crash on 1.2.9 (Possibly from BDA)

### ISSUE THREAD

**Issue by MuricanJeb** [PapaJoesSoup/BDArmory#159]
My game crashed on the 1.2.9 pre release

Mods:
BDA (Duh)
BDModularMissleParts
PhysicsRangeExtender(Came with BDA)
ProceduralParts (For BDModularMissleParts)

**Comment by jrodrigv** [comment]
Logs please :)

**Comment by MuricanJeb** [comment]
Yes, sir :)

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/871026/output_log.txt)

**Comment by jrodrigv** [comment]
Can you attach also the ksp.log?

**Comment by MuricanJeb** [comment]
[KSP.txt](https://github.com/PapaJoesSoup/BDArmory/files/871033/KSP.txt)
Here you go.

I had to change it into a .txt file to upload it here.

**Comment by MuricanJeb** [comment]
Hold on, I think I found the problem.
I think I used the "wrong" v.2.0.0 version.
I might have downloaded the one for 1.2.2 instead of 1.2.9. Standby.

**Comment by jrodrigv** [comment]
Just in case.
Are you using this release ? https://github.com/PapaJoesSoup/BDArmory/releases/tag/v.2.0.0-KSPv1.2.9

**Comment by jrodrigv** [comment]
haha I'm going to close this issue

**Comment by MuricanJeb** [comment]
Yep, I think that was the issue.
Thanks man!

**Comment by jrodrigv** [comment]
BTW try to delete module manager maybe it is not working with 1.2.9

**Comment by MuricanJeb** [comment]
> BTW try to delete module manager maybe it is not working with 1.2.9

Is that why I couldn't see the BD tab?

**Comment by jrodrigv** [comment]
Not sure but I don't have it installed and I can see the BD tab

**Comment by MuricanJeb** [comment]
Do you have all the mods I have? If you do, I could probaly only need to delete the module manager mod.

**Comment by jrodrigv** [comment]
Yes. The only differences are the 1.2.9. x x build number (mine is from steam latest update). And module manager

**Comment by MuricanJeb** [comment]
I use steam too.

Btw check out the pic above :)

**Comment by jrodrigv** [comment]
Nice!! BTW suggest to always disable aero fx graphics settings with BDA it makes a huge performance impact

**Comment by MuricanJeb** [comment]
I don't know how to do it
Man, I'm a guy full of derp :)

**Comment by MuricanJeb** [comment]
I still can't find the fudging BDA tab in 1.2.9 😢

**Comment by MuricanJeb** [comment]
Noth that the problem I'm having is happening for others too (Issue #160)
