### ISSUE TITLE
KSP 1.2.9 does not load BDArmory

### ISSUE THREAD

**Issue by Guard13007** [PapaJoesSoup/BDArmory#160]
I installed the pre-release compile for 1.2.9 from here, and no BDA parts loaded. No other mods have been installed and it is a fresh copy of the 1.2.9 pre-release.

I assume you want a [KSP.log](http://pastebin.com/kbTH5iKq)? :P

**Comment by MuricanJeb** [comment]
This may be related to my issue as you can see further down in the comments of issue 159

**Comment by MuricanJeb** [comment]
#159

**Comment by Guard13007** [comment]
@MuricanJeb I didn't read into the comments much because the initial issue posted was using multiple mods, I am using a pure new install + BDA pre-release only. In the past, many issues reported here have been due to incompatible mods or versions, and I wanted to make it clear this wasn't that.

That said, I will now edit the initial post to make it more clear.

**Comment by jrodrigv** [comment]
I have done a clean install and I've reproduced the issue. 

It is due to the new localization system that Squad has implemented

 I already fixed the issue :) I'm going to do some more testing and I will publish a new release today  

Thanks guys.
