### ISSUE TITLE
Modular Missle Issue and Spawning issue.

### ISSUE THREAD

**Issue by MuricanJeb** [PapaJoesSoup/BDArmory#161]
BUG REPORT INCOMING!!!

It's about the modular missle parts and how I spawn.

So when I try to fire my missle, it decouples, but it doesn't activate the thruster. The only solution is to launch the missle and switch to it, then activate the booster manually.

I also noticed that when I spawn, I'm about 2 or 3 meters off the runway. Luckily, the drop is small enough that the craft I lauch doesn't get destroyed.

**Comment by jrodrigv** [comment]
Please can you attach the craft file?

**Comment by MuricanJeb** [comment]
As I said in the other forum, I reinstalled ksp without the misssle mod to see if I could solve the problem.

I'll install Modular Missles later because I want to teast more the Physics Range Extender.
