### ISSUE TITLE
Warhead and Procedural High Explosive cannot be detonated via Action Group

### ISSUE THREAD

**Issue by KerbheedMartin** [PapaJoesSoup/BDArmory#162]
As the title says, the Small Warhead cannot be detonated. No errors show up in the log. Other BDAc parts can do things via Action Group, just not these two.

**Comment by jrodrigv** [comment]
Thanks for your feedback.

**Comment by KerbheedMartin** [comment]
To clarify, this is an existing feature that is broken. The Small Warhead can be set to detonate via action group, however it does not actually detonate when the action group is activated.

**Comment by jrodrigv** [comment]
This issue is now closed the last release includes the fix.
