### ISSUE TITLE
Crash during part loading

### ISSUE THREAD

**Issue by williambl** [PapaJoesSoup/BDArmory#163]
In the new release v2.0.0, my KSP crashes while loading BDArmoury Parts. Once I downgraded to v0.11.1.6, the issue stopped. I am running Linux (Ubuntu 16.04). 

Here are my logs (Player Log includes the stacktrace, KSP Log just stops while loading.):
[Player.log.txt](https://github.com/PapaJoesSoup/BDArmory/files/905648/Player.log.txt)
[KSP.log.txt](https://github.com/PapaJoesSoup/BDArmory/files/905646/KSP.log.txt)

**Comment by jrodrigv** [comment]
There are two releases. One for KSP 1.2.9, and one for KSP 1.2.2.

Please double check that you are using the right ine

**Comment by williambl** [comment]
I am using CKAN, which I assume has downloaded the correct one. I shall check.

**Comment by jrodrigv** [comment]
Yes, please. I will check too. Maybe CKAN is downloading the wrong one

**Comment by Muzlie** [comment]
I have had this same issue and looking at Ckan's version I believe they are using the 1.2.9 mod for install on 1.2. However now another mod is making my KSP crash 👎

**Comment by jrodrigv** [comment]
Thanks for your feedback. I'm going to try to fix the problem
