### ISSUE TITLE
Spotlight

### ISSUE THREAD

**Issue by OmegaForce** [PapaJoesSoup/BDArmory#164]
This is an idea for a possible addition. 

In one of BahamutoD's previous mods there was a spotlight that could be controlled like a turret. This would be useful in BDA for ground AA emplacements in early was scenarios or used for lighting up targets on the ground from the air during night missions. Many possibilities for such a part can be thought of. Tweakscale for size would be a plus if possible.

**Comment by SpannerMonkey** [comment]
Not regarding spotlight turret, turret was driven by the animation plugin modules  mod http://forum.kerbalspaceprogram.com/index.php?/topic/64646-wip-plugin-bdanimationmodules-v061/
NOT BDA and BD has gone on record as stating that it was/is (still) not possible to have such devices in BDA.
 I have fully explored what is and is not possible with BDA turret code (see impossibles) and can state with some confidence that, within that current turret frame it is not possible for the turret module to operate without an associated weapon module of missile launcher.

**Comment by gomker** [comment]
Closing as Spanner is our Part Master and has stated the definitive answer.
