### ISSUE TITLE
Crashes while loading part upgrades

### ISSUE THREAD

**Issue by WDayneHS** [PapaJoesSoup/BDArmory#166]
I am unable to run BD Armory in my PC. While loading the Part Upgrades, the game crashes. The only mods I have installed are BD Armory and Kerbal Joint Reinforcement. I have ran KJR alone before and worked just fine, and even tried running BDA alone but it crashed. I haven't the slightest clue on how to interpret the error files' contents, but they're attached. 
PC Specs:
Dell Optiplex 7010
16GB RAM
Intel Core i5 3.4GHz
Windows 10 Professional

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/923181/output_log.txt)
[error.txt](https://github.com/PapaJoesSoup/BDArmory/files/923184/error.txt)

**Comment by jrodrigv** [comment]
You are not using the latest BDArmory version. 

Please remove your BDArmory folder and install this version https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.2.1.0
