### ISSUE TITLE
Bomb aiming indicator doesn't adjust for speed

### ISSUE THREAD

**Issue by doxlulzem** [PapaJoesSoup/BDArmory#167]
As mentioned in the title, the small circular recticle for aiming bombs with does not adjust for the aircraft's speed, and sits perpendicular to the plane's angle. I did notice it worked as normal very briefly once when turning, however have not been able to recreate it since.

**Comment by jrodrigv** [comment]
Can you attach the KSP.log generated during your gameplay and also can you list the steps to reproduce the issue?
Thanks

**Comment by doxlulzem** [comment]
The steps to reproduce would be to get into a plane using any form of bombs (Mk 82, Mk 82 Snake Eye, JDAM, CBU, etc.) and look at the reticle, I suppose.. [Here is the KSP.log file](https://www.dropbox.com/s/y2ujrkbw0rnxgb6/KSP.log?dl=0) (Dropbox as neither pastebin nor github would let me post it)

**Comment by jrodrigv** [comment]
You are using an old version of BDArmory. (BahaTurret v1.0.0.0 / v0.11.1.5). Please grab the latest release https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.2.1.0

**Comment by doxlulzem** [comment]
Bugger... Well this is embarrassing

**Comment by jrodrigv** [comment]
No worries. I will close this issue then. I think we already solved that problem before.
