### ISSUE TITLE
GPS system (seemingly) broken

### ISSUE THREAD

**Issue by doxlulzem** [PapaJoesSoup/BDArmory#168]
I, among others, have not been able to A. get either cruise missile to strike a GPS target, both from the same craft as the target and from another. They instead dumbfire. I'm not sure what is going on, however it looks to me that the GPS homing system doesn't work and B. get the JDAMs to strike a GPS target, again, from both the same craft and another, with and without the bombs being in the preview-aim-recticle-crosshair-thingy. I do remember utilising this sytem in 1.1.3 and it worked fine. This leads me to conclude that the GPS system must be broken

**Comment by jrodrigv** [comment]
My previous comment applies also here :)

**Comment by jrodrigv** [comment]
I'm going to close this issue too, the same applies :)
