### ISSUE TITLE
Premature detonation

### ISSUE THREAD

**Issue by Deathpuff12** [PapaJoesSoup/BDArmory#176]
Another issue I have experienced recently is that missiles always explode before they hit their target. This is fine for AA missiles, but for ATGMs it means they're terrible. 
I made a video just to show what's going on. It seems like the detonation distance is a little messed up. Maybe it should only be for AA missiles?

https://www.youtube.com/watch?v=r_MpX4eQXyA&feature=youtu.be

Even though I only show TOW missiles in the video, all missiles are affected by this.

Also, I tried doing this with my newest jet, but the other issue I submitted struck. So sad, I really wanted to show off my cool Viggen :(

**Comment by jrodrigv** [comment]
There is a workaround for this. You just need to set the field 'Detonation
distance override' of each missile to something like 5 meters.

**Comment by jrodrigv** [comment]
By default is 0 that means that you are using the default Detonation
distance for that missile (explosive blast radius)

**Comment by Deathpuff12** [comment]
Ahh, ok. I'll try that. Thanks!
