### ISSUE TITLE
the game crashes when it trys to load

### ISSUE THREAD

**Issue by opseee** [PapaJoesSoup/BDArmory#177]
the game crashes when it trys to load 
i have KSP v1.2.9.1727
please help me 
the crash file:
http://www.mediafire.com/file/l0a2ka2ilb8404r/2017-04-24_193430.rar

**Comment by jrodrigv** [comment]
At the moment we only have this pre-release version for 1.2.9
https://github.com/PapaJoesSoup/BDArmory/releases/download/v0.11.1.3Beta/BDArmory.0.11.1.3Beta_09132016.zip

**Comment by opseee** [comment]
the game still crashes

**Comment by jrodrigv** [comment]
I will do a new pre-release for KSP 1.2.9

**Comment by opseee** [comment]
thx
