### ISSUE TITLE
weapon manager broken

### ISSUE THREAD

**Issue by Lucifer112358** [PapaJoesSoup/BDArmory#178]
The weapon manager is acting like #116, but I don't have a GameData folder inside the other GameData folder. I extracted the BDArmory folder directly into GameData. The log says "File 'GameData/BDArmory/settings.cfg' does not exist", but the file does exist and GameData is in the same folder as the KSP executable.
[KSP.txt](https://github.com/PapaJoesSoup/BDArmory/files/966459/KSP.txt)

**Comment by DoctorDavinci** [comment]
I looked through your log and it leads me to believe that you used ckan to install BDAc ... if this is the case I recommend installing manually

If this is not the case I recommend reinstalling as there are references to a folder hierarchy that should not exist

**Comment by Guard13007** [comment]
To extend what DoctorDavinci said, if you installed BD Armory through CKAN, it currently (last I knew at least) installs the incorrect version, which could be the cause of your problem.

**Comment by Lucifer112358** [comment]
I have never used CKAN. I downloaded from curse and reinstalled manually and I'm getting the same results. Here's the new log: [KSP.txt](https://github.com/PapaJoesSoup/BDArmory/files/968402/KSP.txt)

**Comment by jrodrigv** [comment]
Looking during 2 seconds at the log file I've seen this. BahaTurret v1.0.0.0 / v0.11.1.5

I recommend to download KSP mods using **always** github releases . You can find our latest release here https://github.com/PapaJoesSoup/BDArmory/releases
