### ISSUE TITLE
(Request) Radar images 

### ISSUE THREAD

**Issue by TonyDE94** [PapaJoesSoup/BDArmory#18]
Is it possible to include a system that takes radar images of a target area from space or from a airplane? Like the american Keyhole spy satellites?

**Comment by TheDestroyer111** [comment]
Keyhole/corona spy sats? They only had cameras, no radar... Ok nvm about these sats, what exactly do you mean by a "Radar image"? You already have radars in BDArmory. And if you mean that the radars have a kinda short range (4km for landed vessels and 22,5km for flying ones), then remember that this is exactly the unload range in KSP. If you go farther from a vessel than these distances, they get unloaded and most physics stops affecting them, and they won't be visible no matter how big they are and/or how strongly you zoom in. Also, KSP's stock vessel labels are a long range radar system by themselves, so why ask for such things in BDArmory?

**Comment by jrodrigv** [comment]
As TheDestroyer111 said there is a hard limitations like the render range that will make not possible to take an real image from vessel beyond the 22.5 km limit.

I think this request can be closed

**Comment by TheDestroyer111** [comment]
Oh, I think that also about the long range radar possibility, that the detection radars should have a longer range and work just by finding the vessels via the same mechanics as in the stock game. You know what I mean? It should just see everything that can be seen (even when it's just a vessel label) no matter if it is loaded or not.

**Comment by TonyDE94** [comment]
I was thinking about a radar system simmilar to the ones described here: https://en.m.wikipedia.org/wiki/Radar_imaging

**Comment by PapaJoesSoup** [comment]
I think there is a mod like that already..  Scan sat?

**Comment by gomker** [comment]
I was just about to say [SCANsat](http://forum.kerbalspaceprogram.com/index.php?/topic/72679-113-scansat-v163-real-scanning-real-science-at-warp-speed-june-27-2016/)

IMHO this would not be in scope of BDArmory and something best suited to mod all in its own.
I would assume that the request would be to make the imaging more ground level for recon of vessels
