### ISSUE TITLE
Update Release Version on Spacedock.Info

### ISSUE THREAD

**Issue by pirateswarm** [PapaJoesSoup/BDArmory#180]
Please update on Spacedock!:
https://spacedock.info/mod/867/BDArmoryContinued

**Comment by gomker** [comment]
@PapaJoesSoup  There is a way to add "additional" authors to Spacedock now. Feel free to add me so I can update on release as well

**Comment by NextStarIndustries** [comment]
Curse needs an update as well if possible.

**Comment by PapaJoesSoup** [comment]
Yes.

**Comment by gomker** [comment]
SpaceDock has been updated
