### ISSUE TITLE
BDA Weapon Manager

### ISSUE THREAD

**Issue by ignis81** [PapaJoesSoup/BDArmory#181]
I cant get access to the weapons, Guard menu or the modules. Any help? or is a common bug?

**Comment by jrodrigv** [comment]
This a very common bug that is related with a wrong installation process. I
recommend to review the 'closed issues'.

I'm pretty sure that you will find an issue titled like this one.

**Comment by Guard13007** [comment]
As @ignis81 originally posted this issue on the origin BDArmory repo as well, I would guess the same. I have asked them what version they are attempting to install and where over there. Bahamuto/BDArmory#60
