### ISSUE TITLE
Radar Warning Receiver window not appearing

### ISSUE THREAD

**Issue by GoldVinyl** [PapaJoesSoup/BDArmory#184]
The following mods are installed:
http://imgur.com/a/eY4N4

In flight, if I click the RWR module button, it turns on, I hear the pinging of a scanning radar, but no window appears. I'm not sure if this is some new change to how it works, or if it is a serious issue. Any help would be appreciated.

**Comment by GoldVinyl** [comment]
And, I figured it out. Probably should have fiddled with it some more before posting the issue. Basically, the RWR window was set to 0 width and 0 height in the settings, switched that back to some regular numbers, and it appeared again.

**Comment by Guard13007** [comment]
@GoldVinyl But do you know how it got set to zero? This could still be a bug with defaults if you didn't change anything prior to the issue. o.o
