### ISSUE TITLE
Guided Munitions Air-burst at blastRadius distance

### ISSUE THREAD

**Issue by SleepyGuardian** [PapaJoesSoup/BDArmory#185]
In the current BDAc version guided munitions airburst at the distance set for the weapons blastRadius. 
For example, for my jdam the radius is set to blastRadius = 45. Once it comes with in 45 meters of the GPS targeted point it will detonate. This causes issues with effectively damaging crafts on the ground since the target is at the very limit of the blast radius. I have determined the root of the problem is somewhere in the BahaTurret.dll because I conducted the same test using the .dll from ver 0.2.0.0 and the problem wasn't present. 
Can anyone else duplicate this?

**Comment by jrodrigv** [comment]
Thanks for your feedback. I think I will change this for ground missiles and bombs. 

But there is a workaround that you can use. There is a field called Detonation distance override, you just need to set it to 10 meters for example and It will destroy your target.

**Comment by SleepyGuardian** [comment]
Thanks for the response. I'll mess with that feature again. Last time I tried it it caused the bomb/missile to detonate even further from the target. Once I test it again I'll post here again with the result.

**Comment by SleepyGuardian** [comment]
Finally got a chance to test it today. Looks like I misunderstood how the detonation override behaved. A lower number results in closer detonation distances. Should I close this issue or leave it open since the blastRadius causing air bursts isn't exactly right?

**Comment by jrodrigv** [comment]
Let's leave it open. I want to improve it to make it more effective by default. 

Thanks for your feedback!

**Comment by jrodrigv** [comment]
Let's leave it open. I want to improve it to make it more effective by default. 

Thanks for your feedback!

**Comment by gomker** [comment]
My thoughts are when set to Zero (0) we just remove the check all together, we want to ensure contact for some ordinance such as Anti ship missiles or torpedos. Need to review the current logic and do some experiments.

**Comment by jrodrigv** [comment]
We can do that, but now is 0 by default so I think by default is should have a sensible value instead of 0. I'm thinking that by default it should have something like blastRadius ^0.5 to ensure massive damage to the target.
Then if a user wants to set it 0  the missile will only explode on collision. 

However I would like to say that to set the missile to only detonate on collision it would not be a smart idea in most cases, the current guidance algorithms are not that accurate and we can see the missile hitting the ground instead of the target ( equally destructive if the missile has enough explosive material).

@gomker I have reviewed your changeset but I think that would not be enough. I will take care of this issue if you are fine with it ;)

**Comment by gomker** [comment]
@jrodrigv during my testing it mostly works, but the case you described happened a few times where the missile bounced around on the ground (is there a ground collision check?) If you have some ideas I am open, update is on my fork only.

**Comment by jrodrigv** [comment]
I need to check, I think missiles should explode on collision when they have been fired but maybe you have found a bug :)

**Comment by gomker** [comment]
I uncommented that collision check, it was taken out awhile back when we started working on detonation distance. My logic was to only allow it to trigger when Detonation distance was 0. 

Use case is say a anti ship missile, I may want it to hit the armor plate for maximum effect, the Radius check based on COM may cause some funny calculations with very large ships.

**Comment by gomker** [comment]
I believe we are good to close this now, with TheDogs updates in last merge it finished off any lingering issues.
