### ISSUE TITLE
Ground Radar does not use any resources

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#19]
Not sure if this was by design but the Ground Radars do not seem to use any Electrical Charge.

I would say as realism factor they should use some EC.

**Comment by TheDestroyer111** [comment]
As do air radars. I think that BahamutoD deliberately made them not use electricity :P 
If he wanted to, he could do it, jammers use EC.

**Comment by jrodrigv** [comment]
I agree. It's not a bug but I like to be realistic so I think this can be tagged as Enhancement

**Comment by PapaJoesSoup** [comment]
Agreed.  The issue will be how much?  This kind of arbitrary, so we need to consider other mods, balance, and technology.

**Comment by gomker** [comment]
At first I would think the same EC used in a large Comms dish but that may be overkill.

My suggestion is just to use a small amount to start in the next release and get people used to it using it first then adjust to what works for gameplay and realism.

**Comment by TheDestroyer111** [comment]
Comms dish ec usage would definitely be overkill.
From what I see, the jammer uses 5 ec/s. Although real jammers use more and I think the jammer chould be reworked at some point, it is less effective than real ones so it kinda counterweights its lower ec usage. So I think that all radars should use 1 ec/s to scan and one more ec/s (2 total) for locking targets. This way they wouldn't affect much the working of planes with alternators, but are likely going to affect any plane with less power generation or one that is operating its jammer.

**Comment by TheDestroyer111** [comment]
@PapaJoesSoup @jrodrigv Hello?
And I have another suggestion. That there should be two types of jammers: A "self-protection jammer" that is a small part (a bit bigger than WM/AI parts) and works roughly like the current jammer with the same EC usage, and instead the current jammer could be used to completely screw up the radars of a single enemy just like real jammers do, at the cost of using, let's say, 10 ec/s.

**Comment by gomker** [comment]
EC usage added. Its currently very small. Will look to add values based on each radar type and size to the part configs
