### ISSUE TITLE
Keeps crashing on startup

### ISSUE THREAD

**Issue by Blifaloo** [PapaJoesSoup/BDArmory#193]
https://gyazo.com/f2abeb9741787d25840857c9e495a5bb
And even if I remove all those and keep module manager it still crashes, and if I remove it, doesnt crash. I have tried everything.

**Comment by jrodrigv** [comment]
We need the KSP logs after the crash.

**Comment by ThisGuyKai** [comment]
Having the same issue. Here is my crash logs. https://dbr.ee/4Bwb

**Comment by Blifaloo** [comment]
[error.txt](https://github.com/PapaJoesSoup/BDArmory/files/1053434/error.txt)
The error log

**Comment by jrodrigv** [comment]
I need the KSP. log file

**Comment by TheDogKSP** [comment]
@ThisGuyKai 
Your install is somehow completely messed up:
from your logs:
_Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
BahaTurret v1.0.0.0 / v0.11.1.6
BahaTurret v0.2.1.1
BahaTurret v1.0.0.0 / v0.11.1.6
BahaTurret v1.0.0.0 / v0.11.1.6_
Load(Assembly): BDArmory/BahaTurret/bin/Debug/BahaTurret
AssemblyLoader: Loading assembly at F:\SteamLibrary\steamapps\common\Kerbal Space Program\GameData\BDArmory\BahaTurret\bin\Debug\BahaTurret.dll

**=> Please delete the complete BDArmory foilder in your gamedata, re-download the most current release for KSP 1.3 (BDAc v0.2.1.1), and install that.**

**Comment by jrodrigv** [comment]
Thanks @TheDog.

2017-06-06 9:23 GMT+02:00 TheDog <notifications@github.com>:

**Comment by Blifaloo** [comment]
https://www.dropbox.com/sh/1idydxtx61bonb5/AACA-lcCq3v1JsaInasWcrCra?dl=0 Ill send you my entire log :/

**Comment by Blifaloo** [comment]
I reinstalled my game and installed bdarmory continued off of github and got module manager 2.8.0 and started up ksp and it crashed.

**Comment by jrodrigv** [comment]
@Blifaloo you are not using a Clean installation. 

You have a KSP full of mods and you are trying to run KSP 1.3. YOU EVEN HAVE 3 DIFFERENT VERSIONS OF MODULE MANAGER! 

Now, please for the next time I suggest to review the basics before opening an issue. 

- Everytime KSP is updated I suggest to backup you KSP folder, uninstall and delete KSP folder, install again.
