### ISSUE TITLE
AI Switching between vessels causes Guard Mode to lose target

### ISSUE THREAD

**Issue by Nerfclasher** [PapaJoesSoup/BDArmory#2]
I've noticed in a few videos I've recorded that when using CameraTools with dogfight BD AI target mode that when I switch to an enemy missile, and back to a craft, or between crafts quickly, with f2 hiding GUIs or hiding the BDA GUI, that sometimes the AI forgets either to use canons, or canons fire but no visual appear. The issue is resolved by simply toggling the BDA GUI on (off and on), or any GUI for that matter. The instant the GUI is toggled, the AI starts firing canons finally.

I've not been able to duplicate steps for it, but based on some of the videos in the KSP ASC youtube playlist (especially the early videos) this happens frequently to the point that planes begin playing chicken with each other.

This may not even be a CameraTools issue, as I also see it here: [](https://www.youtube.com/watch?v=WS4bCUywCkg=1m40s)
from [](https://github.com/BahamutoD/BDArmory/issues/43)

**Comment by gomker** [comment]
I think this is not just related to Camera tools. I am close to being able to reproduce this consistently, when switching vessels during a battle AI will stop targeting and firing at opponent. As soon as I toggle teams and guard mode again they re-engage

**Comment by Nerfclasher** [comment]
@gomker this has been a issue even before the bdac team took over for example https://github.com/BahamutoD/BDArmory/issues/43

**Comment by jrodrigv** [comment]
I can acknowledge that I've seen this issue a couple of time during my time playing BDArmory. but I don't have a clue about in which exact circumstances.

Taking into account that:
- Camera tools is broken in KSP 1.2.
-  We don't have a way to reproduce this issue.

We have to suspend this issue unless someone can provide the exact steps to reproduce this issue on KSP 1.2.1
