### ISSUE TITLE
Jammer does nothing

### ISSUE THREAD

**Issue by TheDestroyer111** [PapaJoesSoup/BDArmory#20]
The ECM Jammer only drains electricity when activated, otherwise it does nothing. Radars still work properly even with a jammer nearby.

**Comment by Alphasus** [comment]
What ranges was this tested at? In my experience, they work better at longer ranges. Try it at ranges from 10-20 km if you haven't already.

**Comment by TheDestroyer111** [comment]
Does it work AT ALL for you? And if it does work for you AT ALL, what does it do for you?

**Comment by TheDestroyer111** [comment]
This chould be closed, cuz i think the topic is exhausted.

**Comment by PapaJoesSoup** [comment]
Agreed.  Wiki page entry sounds good.
