### ISSUE TITLE
Beam-riding missiles and detonation distance...

### ISSUE THREAD

**Issue by Deathpuff12** [PapaJoesSoup/BDArmory#200]
When using the TOW missile, I've found that the missile itself flies just underneath the laser. Sometimes, for whatever reason, the user may need to adjust the targeting pod. This means adjusting the targeting pod to aim slightly further in one direction. If a downward adjustment is necessary, that means the laser will be on the missile, instead of the target, for a split second.
With the recent addition of the detonation distance, this causes an obvious problem. The missile sees itself as the new target, and it sees that the distance to the target is under whatever its detonation distance is set to, so it detonates. The missile has now self-destructed long before it reached the target. This can be very frustrating, and it's even more annoying because there's no way to make the missile explode on contact with the target.

**Comment by gomker** [comment]
@Deathpuff12 logic has been added to allow to set the detonation distance to 0 and this will bypass this check changing the detonation trigger to OnCollision()

**Comment by gomker** [comment]
Latest release has fix implemented
https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.3.0.0
