### ISSUE TITLE
All gui window resizable Enhancement

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/BDArmory#202]
Hi, would it possible to add some kind of size adjustment to BDA gui windows?
 Currently the amount of active BDA windows on one screen can reduce the viewable area to 50% or less .  
This would suggestion would ideally cover all guis in BDA VesselMover and LVS 
Cheers

**Comment by gomker** [comment]
Done by @PapaJoesSoup  I believe
