### ISSUE TITLE
Throttle Mirroring on vessel switch

### ISSUE THREAD

**Issue by XOC2008** [PapaJoesSoup/BDArmory#203]
Tested with as stock as possible, Lander can, beam, wheels, and RTGs with BDA Weapon Manager. Throttle on Team A affects throttle on Team B.

Using the latest support branch release candidate: BDArmory.0.2.1.2_06152017.zip

**Comment by gomker** [comment]
Noting this build is from support branch.

**Comment by gomker** [comment]
Testing Now.

**Comment by SpannerMonkey** [comment]
Confirmed in several variations and video evidence created 
[https://www.youtube.com/watch?v=mUfzJ4Ft-jQ&feature=youtu.be](url)

**Comment by gomker** [comment]
Installed [previous release](https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.2.1.1) and confirmed issue. Throttle will mirror to next vessel you switch to. Only applies to vessels with Weapon Manager

**Comment by gomker** [comment]
Testing shows that with latest `support` branch build that issue only manifests when selecting next vessel with BDAVessel Switcher

**Comment by jrodrigv** [comment]
I think the issue name should be : Throttle value is not updated  when switching vessels. 

I think this problem  has been always there.

**Comment by gomker** [comment]
@jrodrigv  To clarify the throttle is updating the next vessel you switch to. 

Example:

Vessel A (Active) = 0%
Vessel B (Inactive) = 100%

Click BDAVessel Switcher 

Vessel A (Inactive) = 0%
Vessel B (Active) = 0%

You would not want the throttle to update unless using Wing commander.
Checking the code it does all look to be the same method `FlightGlobals.ForceSetActiveVessel` 
I may have not noticed much in the past as most of my vessels will have Guard mode on when switching.
