### ISSUE TITLE
Explosion and damage issues

### ISSUE THREAD

**Issue by NextStarIndustries** [PapaJoesSoup/BDArmory#208]
After detonation explosions follow craft. After explosion the damage area far exceeds blastRadius and destroys craft no matter how far away you are.

**Comment by NextStarIndustries** [comment]
KSP 1.3 BDAc newest version release NKD newest version realease

**Comment by jrodrigv** [comment]
I think this issue was already reported #171

**Comment by gomker** [comment]
@NextStarIndustries  Thanks for the report, I assisted Harpwner in testing NKD in his last release and this indeed is an issue already reported.  It began to manifest after KSP update and we are looking into it in #171 as mention by JR.

To confirm - were you using stock BDA parts when this issue occurred or using NKD's Nuclear weapons, as they have known issues on blast radius that is still being worked on by Harpwner

Regards

**Comment by NextStarIndustries** [comment]
I'm using Harpwner's nuclear explosion module on my own parts. Thanks for the response I'll move over to #171 and follow it. It appears the explosion jumps over to what ever vessel is activated after NDK's explosion happens and then runs the explosionfx of BDAc on that vessel.
