### ISSUE TITLE
Hidden Vulcan Not Firing After Switching To M230

### ISSUE THREAD

**Issue by WhiteWeaselMLAS** [PapaJoesSoup/BDArmory#210]
-KSP version 1.3
-BDarmory Version v0.2.1.1
-Win7

This seems like a bit of an odd one, but when using the hidden vulcans, then switching to the M230's and firing them, it will cause my hidden vulcans will no longer fire (the sound plays and only fires a single shot, if at all) when switching back to them. Has anyone else encountered this issue?

**Comment by gomker** [comment]
Hello,
Can you let me know if this issue exists when using the reference test vessels, specifically BDA - Test Platform.craft.   You can find a copy in `\GameData\BDArmory\craft` or [here](https://github.com/PapaJoesSoup/BDArmory/tree/master/BahaTurret/Distribution/GameData/BDArmory/craft) 

Regards,

**Comment by WhiteWeaselMLAS** [comment]
The test vessels seem to work fine when switching between weapons. The only other things of note is that I switch between them via action groups and using the buttons on my joy stick, but doing the same exact thing on the test bed didn't result in the glitch.

**Comment by gomker** [comment]
We have seen some reports awhile back of this same issue however, as you noted it is hard to replicate consistently. 
When you are doing the weapon switch how have you mapped it in action group? I usually map mine to (7) next weapon and them map the number key to my joy stick. I haven't seen problems with this method. Let me know if this seems to help.

**Comment by TheDestroyer111** [comment]
This is exactly the same issue as #17

**Comment by TheDogKSP** [comment]
not reproducible, closed
