### ISSUE TITLE
No GUI

### ISSUE THREAD

**Issue by BigLDP** [PapaJoesSoup/BDArmory#211]
I recently downloaded the latest version of the mod and can say that it works (model wise). I can not, however, say that the weps are functional being that the manager does not even have a GUI. Any fix for this or nah?

**Comment by jrodrigv** [comment]
Can you provide a KSP.log file? Inside your KSP installation folder you will find it.

**Comment by BigLDP** [comment]
Sorry, I was using BDArmory Master, not the actual game install :p I have fixed it now.

**Comment by jrodrigv** [comment]
No worries :)
