### ISSUE TITLE
Competition mode not working.

### ISSUE THREAD

**Issue by SquaadZulu** [PapaJoesSoup/BDArmory#212]
When I select the teams, the other plane does not appear on the other team in bda bessel switcher, and when i attempt to start a competition, the mod says that a team is empty, when there is a plane on each team.

**Comment by jrodrigv** [comment]
Have you attached a Weapon Manager to each craft?

**Comment by jrodrigv** [comment]
Do you have PhysicsRangeExtender installed?

**Comment by SquaadZulu** [comment]
I have a weapons manager on each craft, but i don't have physics range extender.

**Comment by jrodrigv** [comment]
Physics Range Extender is a requirement for BDArmory. It allows to extend the standard physics range of KSP

**Comment by SquaadZulu** [comment]
ok. i just downloaded it. my concern though, wwas the fact that the planes were almost next to each other.

**Comment by SquaadZulu** [comment]
alright. that fixed it. thanks.
