### ISSUE TITLE
Missiles need more rigorous miss target check

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#213]
Very consistently I can recreate cruise missiles missing their targets will go on almost forever and into space (contributing factor #21 )
Need to review target miss logic for auto destruct.

![screenshot25](https://user-images.githubusercontent.com/3577339/27512910-882d06b8-5917-11e7-93f5-1db474166213.png)

Perhaps the simplest way to handle this would be a maximum altitude check part config option

**Comment by mzzcrs** [comment]
What Version of KSP and BDarmory are you using?

**Comment by gomker** [comment]
1.3 and a development build of KSP as I am on the dev team :)
 This is an issue I will be working on, we sometimes start issues to let the team know what we are working on.

**Comment by jrodrigv** [comment]
@Derek I will review the implementation of the CheckMiss done  for Modular
Missiles, maybe we can reuse it for MissileLauncher class.

**Comment by gomker** [comment]
@jrodrigv doing a few more traces in debug - looking at the code I don't think any Check miss was implemented much for Cruise + Radar (which Spanner and I have been using for Anti Ship Lately)

**Comment by jrodrigv** [comment]
You are totally right. I think only AAM missiles are using it

**Comment by gomker** [comment]
Looks like the check is very basic that is why its only for a small subset. This would not work for AGM or Cruise, it would need a more sophisticated check

     if (sqrDist < 160000 || (MissileState == MissileStates.PostThrust && (GuidanceMode == 
     GuidanceModes.AAMLead || GuidanceMode == GuidanceModes.AAMPure)))
