### ISSUE TITLE
Crash on startup. 

### ISSUE THREAD

**Issue by Arcamenal** [PapaJoesSoup/BDArmory#215]
Fresh Install of KSP, [this](https://i.gyazo.com/88155e85a9349a9588a8fcdb4dd645f6.png) is my GameData setup and below are all of the log files created after the crash

https://www.dropbox.com/sh/uwoc6smgk4n31xz/AAASsDpZ0iyypPyiNyxiJdNaa?dl=0

**Comment by jrodrigv** [comment]
You are not using the latest version of Vessel Mover mod. You need to double check that you are using the KSP 1.3 version of all your mods.
