### ISSUE TITLE
Verify locking and detonation distance

### ISSUE THREAD

**Issue by SquaadZulu** [PapaJoesSoup/BDArmory#216]
I was playing around with BDAc and tried to fire a laser missile at a tank I positioned on the ground. Despite me having been targeting the tank with a FLIR, The missile wouldn't target, Later, I used a heat seeker on a drone I set up with no countermeasures and flying straight. The missile went through the plane, dealing no damage. The missile exploded shortly afterwards. Based on this. I think that the hit checking system needs to be looked at again.

**Comment by gomker** [comment]
Hey there @SquaadZulu  first lets get the "support" questions out of the way, want to make sure you are running the latest [release](https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.2.1.2)  

When reporting issues please provide the following information:

- Version of KSP
- Version of BDA
- OS Build and Version
- Link to a full KSP log if reporting a problem

[See this for more information
](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)

**Next** - can you let me know if this issue exists when using the reference test vessels. You can find a copy in `\GameData\BDArmory\craft`  or [here]( https://github.com/PapaJoesSoup/BDArmory/tree/master/BahaTurret/Distribution/GameData/BDArmory/craft)

When you targeted the vessel did you "lock" the laser to the target? The KSPEdia in game has some detailed instructions on how to lock and fire the various missiles.

Now that last part of the missile striking - yes we are looking at doing some tweaks on the "detonation" distance". Try setting it to (1) the default is (0) I believe for the laser guided missiles.

Regards,

**Comment by gomker** [comment]
Hm. Ok, running some tests and I did see some issues locking when I set the range to 0. I am taking a closer look

**Comment by gomker** [comment]
[LOG 17:55:22.772] [BDArmory] : BDA - Test Platform - Missile - Det Distance - Checking engagement envelope of AGM-114
		[LOG 17:55:22.775] [BDArmory] : BDA - Test Platform - Missile - Det Distance - Checking engagement envelope of AGM-114
		[LOG 17:55:22.778] [BDArmory] : BDA - Test Platform - Missile - Det Distance - Selected weapon AGM-114
		[LOG 17:55:22.782] [BDArmory]: BDA - Test Platform - Missile - Det Distance is engaging the least engaged target with AGM-114
		[LOG 17:55:22.784] [BDArmory]:BDA - Test Platform - Missile - Det Distance launchAuth=True, pilotAut=True, missilesAway/Max=0/1
		[LOG 17:55:22.786] Setting target camera parent
		[LOG 17:55:25.793] [BDArmory] : BDA - Test Platform - Missile - Det Distance - Checking engagement envelope of AGM-114
		[LOG 17:55:25.796] [BDArmory] : BDA - Test Platform - Missile - Det Distance - Checking engagement envelope of AGM-114
		[LOG 17:55:25.799] [BDArmory] : BDA - Test Platform - Missile - Det Distance - Checking engagement envelope of AGM-114
		[LOG 17:55:25.802] [BDArmory] : BDA - Test Platform - Missile - Det Distance - Checking engagement envelope of AGM-114

Log notes : engagement settings authorizing launch but does not fire

**Comment by gomker** [comment]
Latest release has fix implemented
https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.3.0.0
