### ISSUE TITLE
Increase resolution of missile/launcher decouple speed

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/BDArmory#217]
AT present the missile decouple speed  is locked to a maximum of value of ten  with a resolution of  0.5 per step 
 A setting of 0.5 is powerful enough to send a lightweight projectile of 28kg several KM into the air.
Currently the only way gain some form of control is to make the projectiles much heavier and in the process more than double the combined weight of launcher and 28 projectiles. A higher resolution would allow for higher levels of control over launch behavior 
A value of 10 on the decouple is enough to send the same lightweight projectile into orbit
Ideally the resolution would be 0.1 with the maximum value still being 10.

**Comment by gomker** [comment]
In next release
