### ISSUE TITLE
Disabling Weapons after Part Destruction

### ISSUE THREAD

**Issue by Wernher-vonBraun** [PapaJoesSoup/BDArmory#218]
After a part is destroyed, all the weapons are disabled. It would be very appreciated for this feature to be exterminated, and I may not be the only one.
Thanks,
Fritz

**Comment by gomker** [comment]
Hello,
If the weapon manager is destroyed or not attached to the weapons any further they cannot be controlled. This is due to the way BDA is designed inherently for control of the weapons, AI and targets. Nothing can be done about it at the moment.

Regards,
