### ISSUE TITLE
Enhanced Physics Range not working 

### ISSUE THREAD

**Issue by Battle8111** [PapaJoesSoup/BDArmory#222]
I noticed that BDArmory continued supported extended physics range with the default setting being @ 200000 KM in the settings file, I tried to test this in-game with just the mod itself and was unable to load vehicles at this distance what so ever, not even at 20 KM. I noticed its at the default of 2.5 KM (I think if I am correct). 

I have no other mods that could conflict with this and have started a fresh in-game save file to eliminate any mod/or save file issues, I am gonna provide some screen shots to show that its not working for me. I am also running the game in 64 bit. Hopefully this is a bug and I am not providing information to an issue that is non-existent, maybe I am doing it wrong. 

Attachments below with pictures. Will be willing to provide any more info if asked. 
![20170704184854_1](https://user-images.githubusercontent.com/29904151/27844699-b156b75c-60ea-11e7-90a4-41aa8cc3d497.jpg)
![20170704184904_1](https://user-images.githubusercontent.com/29904151/27844700-b1572ea8-60ea-11e7-8532-1fea1d7d8c95.jpg)
![20170704184910_1](https://user-images.githubusercontent.com/29904151/27844702-b157ee74-60ea-11e7-9ec7-0c8ff0708bdd.jpg)
![20170704184920_1](https://user-images.githubusercontent.com/29904151/27844701-b1579f1e-60ea-11e7-92a7-95310cfa6d93.jpg)
![20170704184925_1](https://user-images.githubusercontent.com/29904151/27844703-b157fd56-60ea-11e7-800e-1342d9cc0d33.jpg)

EDIT:

Enhanced or Extended Physics range? Not quite sure. Also gonna try and see if the issue is happening in 32 bit with me. 

EDIT2: 

Game is 1.3 and is latest version of BDArmory continued

EDIT3: I tested it in 32 bit and did not have a difference.

**Comment by gomker** [comment]
Hello, 

Would you mind opening an issue here :  https://github.com/jrodrigv/PhysicsRangeExtender/issues
JR Maintains PRE and this is not fully integrated into BDA.  He does monitor this issue list as well but for visibility its best to be in the PRE repository. 

Thanks

**Comment by Battle8111** [comment]
@gomker Will do! Did not know that, thank you!

**Comment by gomker** [comment]
No problem. All on the same dev team but JR wrote PRE from scratch.
