### ISSUE TITLE
RBS-15 Cruise missile just keeps flying into the sky without going anywhere near the target

### ISSUE THREAD

**Issue by Jake762x51** [PapaJoesSoup/BDArmory#224]
RBS-15 Cruise missile just keeps flying into the sky without going anywhere near the target and either explodes a few hundred meters above the ship i'm firing it from or just flies around in the sky until it detonates itself.

I am using the latest versions of the mods, i used a clean install and no matter what my cruise missiles never hit the target even tough mavericks and all other missiles work perfectly on the same platform!

Shot both cruise missiles from a plane and the same thing happens too.

Really unfortunate...

**Comment by gomker** [comment]
Hey Jake, 
Have you set a GPS target for the Cruise missile?

If so when reporting issues please provide the following information:

- Version of KSP
- Version of BDA
- OS Build and Version
- Link to a full KSP log if reporting a problem

[See this for more information
](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)

**Comment by Jake762x51** [comment]
Newest Version of KSP
Newest Version of BDA
Newest Version of Windows 10 Pro 64Bit
Log is attached

**Comment by SpannerMonkey** [comment]
RE above issue.  Test fired 20 RBS 15 missiles on test range , to ranges from 10 up to 45km.   All missiles without exception tracked to target with a very stable flight path. all missiles struck target area with an acceptable for type CEP  (performance would be rated as good to very good )  

 After checking through your log i can see what missiles you fired and cannot find one incidence of attempted firing of the RBS 15 cruise missile. Perhaps you restarted since the problem was discovered?  

 Should your problem persist please supply a clean log in which the only missile tested is the RBS15 and should not consist of numerous destroyed vessels.  Create a GPS ground target instead. Cheers

**Comment by Jake762x51** [comment]
Reporting in. The RBS-15 missiles still do not work.
After firing they either head to the target and then straight fly above the target and then explode or they explode shorty after firing them off in the air.

Here is a log of my recent test:

[KSP.txt](https://github.com/PapaJoesSoup/BDArmory/files/1178087/KSP.txt)

**Comment by gomker** [comment]
"explode shorty after firing them off in the air."
RBS 15 is meant to be ground launched - are you firing these from a plane?

**Comment by gomker** [comment]
@Jake762x51  Can you also check to see what the "detonation distance override" is set to - try setting it to 0. Also I have noticed that my GPS targets sometimes will be "inside" territory. Try and make sure something was "locked" when setting the GPS target. 

Here is a demo showing a few hits/misses at 30KM distance with RBS15

https://youtu.be/falMzf48ELs

**Comment by Jake762x51** [comment]
I did exactly what was done in the video and the Missile either hit the ground or impacted in front of the target from a good distance into the ground.

Here is the log:

**Comment by Jake762x51** [comment]
[KSP.txt](https://github.com/PapaJoesSoup/BDArmory/files/1179695/KSP.txt)

**Comment by TheDogKSP** [comment]
I have most of the mods you are running, except SXT, so maybe you could post your SFS file (of the Ace Combat save) here, then we can have a look at it directly...

**Comment by Jake762x51** [comment]
[Ace Combat.zip](https://github.com/PapaJoesSoup/BDArmory/files/1180257/Ace.Combat.zip)

**Comment by TheDogKSP** [comment]
Congrats on the good looking B2 and F16, nice craft!
Though I have never flown something as bitchy as this F-16... it definitely should not carry 2 heavy cruise missiles...

anyway, I loaded your save, took the F-16, and successfully fired both RBS-15 onto the KSC tracking station. No issues (aside from the F-16 being awfully unbalanced with one missile fired)

See here: http://imgur.com/a/OU8Iu

So, seriously, you must be doing something wrong, it works perfectly for me with your save and your crafts...

**Comment by Jake762x51** [comment]
I'm not ready to give up yet, so please, give me a very detailed step to step instruction what you are exactly doing to do it successfully.

**Comment by TheDogKSP** [comment]
Handling procedure for all gps guided weapons is the same:

1. Well, lock the FLIR targeting ball onto something (display shows LR), click "send gps".
2. show the gps coordinate (weaponmanager modules -> gps) and click (select) the one you just created. It is now active, the gps label is shown with a brown/yellow background.
3. Activate the weapon, confirm it has locked the coordinate (somewhat of a "double ring" around the gps dot, as visible in my first screenshot)
4. Ensure you have some minimum range for the weapon. I had like 5km, at very close range a gps weapon does not work well.
5. Fire and enjoy.

**Comment by TheDogKSP** [comment]
if it still does not work for you, please record the next ksp.log with "debug labels" enabled in the BDA options, and if possible maybe provide some screenshots like I did. We will figure it out eventually... :)

**Comment by PapaJoesSoup** [comment]
My I also suggest the same, detailed steps to reproduce the problem, like @TheDogKSP provided.

**Comment by TheDogKSP** [comment]
closed (not reproducible / no more info provided)
