### ISSUE TITLE
Game crashes and wont open pls help

### ISSUE THREAD

**Issue by aceofkings** [PapaJoesSoup/BDArmory#225]
My game crashed when loading in 1.3 help me # @ @

**Comment by MuricanJeb** [comment]
You forgot to cut the **.log** from the very tall file trees.

You also forgot to show us which **version** your axe is to cut the tree

You should figure what I mean in a few seconds.

**Comment by gomker** [comment]
As inelegantly pointed out by MuricanJeb, we do noeed more information

When reporting issues please provide the following information:

- Version of KSP
- Version of BDA
- OS Build and Version
- Link to a full KSP log if reporting a problem

[See this for more information
](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)

**Comment by aceofkings** [comment]
issue was fixed
