### ISSUE TITLE
[Feature Request]Armored Turret

### ISSUE THREAD

**Issue by flywlyx** [PapaJoesSoup/BDArmory#226]
https://github.com/PapaJoesSoup/BDArmory/blob/master/BahaTurret/PooledBullet.cs#L360
```
                           if (fulllyPenetrated)
                            {
                                heatDamage /= 8;
                           }
```
to

```
                            if (fulllyPenetrated || armor != null)
                            {
                                heatDamage /= 8;
                           }
```

or
```
                            if (fulllyPenetrated)
                            {
                                heatDamage /= 8;
                           }
                            else( armor != null)
                            {
                                heatDamage /= 4; //Adjust lack of penetration damage ratio
                           }
```

Armored turret should take less damaged than non-armored one.

Modified after @gomker suggest to avoid affecting ricochet mechanism.

**Comment by gomker** [comment]
If this refers to https://github.com/PapaJoesSoup/BDArmory/blob/master/BahaTurret/PooledBullet.cs#L343
That section of the code is dealing with ricochet, specifically that if/else section is for ricochet off the ground.

**Comment by flywlyx** [comment]
When a armored turret got hit and no ricochet, there should be 3 conditions apply,
1, penetrate armor and hit core. Full damage.
2, penetrate armor and hit nothing, over penetration.
3, fail to penetrate armor. less damage.
But currently, there is only 2 conditions applied, this is why I trying to add a armor sensor there to reduce the damage. But looks like this will result ricochet.
Modify line 360 might be a better idea.

**Comment by gomker** [comment]
I need to walk through the damage logic be sure. We are testing a few things right now and I will look into this soon after.

**Comment by gomker** [comment]
@flywlyx  Going through these code sections now, I found some other oddities that are having an effect. I am redoing some of the code to a proper part module instead of config nodes as some of the logic is not triggering correctly

**Comment by gomker** [comment]
Everything will be able to get armor in next release and will integrate many of the items mentioned.
