### ISSUE TITLE
Modular Missile improvements

### ISSUE THREAD

**Issue by jrodrigv** [PapaJoesSoup/BDArmory#229]
Hi all,
I will be using this issue for tracking new development for MM

**Comment by jrodrigv** [comment]
- New improvements: Auto SAS activation when the missile is fired. Before it was only activated if the parent vessel had it switched on.
-  I have improved the Cruise and Ballistic Guidance. Ballistic Guidance will switch to AGM guidance as soon as it reached the 50% of the distance. 
- I have made the engage enveloped switchable .

**Comment by TheDogKSP** [comment]
v1.0.0 released, closing this issue
