### ISSUE TITLE
[Request] Guard mode enhancements 

### ISSUE THREAD

**Issue by FourLeopard** [PapaJoesSoup/BDArmory#23]
Would it be possible to add a feature where you could configure guard modes accuracy with turrets. Possibly implementing a slider to control whether guard mode will be 100% accurate (How it is currently) or a lower percentage (Having incorrect lead, or aiming to the left or right etc.). Also, you should be able to select whether or not guard mode can intercept incoming projectiles (Missiles, bombs etc.) I think these two (_hopefully_) simple additions could add great depth to the guard mode.

**Comment by TheDestroyer111** [comment]
With making it possible to switch off missile interception, I absolutely agree and I don't think it could be anything hard to code. But for controlling guard mode accuracy, it should first become able to fire properly. Right now there are at least 2 main reasons for GM to miss its target (with guns): First of all, gun inaccuracy and recoil. This should stay for I hope obvious reasons. But the other reason is that guard mode really sucks at air-air leading: although it leads perfectly if the guard itself is stationary, it doesn't account for its own velocity, thus making it ineffective when, for example, you want to challenge yourself to destroy an AI bomber armed with defensive turrets.

**Comment by FourLeopard** [comment]
Huh thats strange, the AI bomber armed with defensive turrets was the whole reason I wanted to adjust the turret accuracy. For me even when on moving vehicles turrets are almost 100% accurate, a little unrealistic when you are trying to replicate WW1/2 gunners ;). As soon as a bombers turrets fire, the bullets land perfectly on opposing fighters and they instantly scatter. The only way I was able to reliably balance this was reduce the gun range of the bombers turrets to say 400 while keeping the fighters at 500. Its almost impossible for fighters to attack anything with AA turrets, and I think adding an accuracy slider would help with that and generally increase the amount of customizability of guard mode.

**Comment by TheDestroyer111** [comment]
Hmm... Wait. I know what is your issue. Did you sit on the tail of the bomber in such a way that your relative movement is lower than 50 m/s (it sounds like you did)? If yes, then you are doing it totally wrong-In World War II, bombers were NEVER attacked like in a typical fighter-fighter tail chase engagement. Bombers were virtually always attacked from a totally different direction to avoid turret gunners. Remember that in a tail chase engagement with little relative velocity between the craft that is also done at so short ranges like you do, the velocity of the bomber itself doesn't create much error in Guard Mode aiming. But Guard Mode does indeed suck at shooting down fighters that encounter the bomber from a different angle with high relative velocity (cause it doesn't account for the bomber's velocity).

**Comment by FourLeopard** [comment]
Yeah I think you may be right, as I was using WW1 fighters and bombers, that were going around that speed. However AI fighters simply come from the back and as soon as the bomber starts firing they scatter away and extend for miles. But that is whole other issue, honestly I think a simple option to disable/enable guard mode firing at incoming projectiles would be great :)

**Comment by Wraith977** [comment]
Could it not be made that Visual aiming (without being linked/slaved to a radar) be made much less accurate and radar assisted weapons will fire with the current accuracy? This is the most realistic: allows for high accuracy, radar assisted weapons and low accuracy visual weapons to be used in the same battle; removes the need for a slider and accurately simulates human error and machine precision.

**Comment by gomker** [comment]
Current release supports targeting configuration for Air,Ground or missile now
