### ISSUE TITLE
Impenetrable Armor Plates

### ISSUE THREAD

**Issue by sjpc302** [PapaJoesSoup/BDArmory#237]
Recently I have been both playing around with tanks and trying to make my own submod for BD armory. In the process, I believe I have discovered a bug - regardless of the penetration values, shells do not penetrate the armor panel included in BDAc. I noticed this with armor panels in my own mod first, but it appears this is in BD armory as well.

I tested this on a clean install with only BDA installed, and found that while shells would penetrate structural panneling as expected, they would not at all penetrate armor. I then went into the BulletDefs and buffed penetration into the hundreds and then thousands for the weapons I was testing, and without fail they would pass through all structural paneling but detonate or terminate on the first armor panel they hit. The same result was obtained using armor panels I made for my mod on a separate install (made from scratch, not your models), that only have 20mm of effective thickness.

![bug1](https://user-images.githubusercontent.com/30157960/28183215-a65e6eb4-67dc-11e7-9260-30cafd3c40f4.png)
![bug2](https://user-images.githubusercontent.com/30157960/28184155-31057c30-67e0-11e7-9a86-cfdf1235d79a.png)
![bug3 5](https://user-images.githubusercontent.com/30157960/28184163-3b5aeb7a-67e0-11e7-92c9-5414cbeff450.png)
![bug3](https://user-images.githubusercontent.com/30157960/28183223-aaee24f6-67dc-11e7-8f5c-830b6aaf631f.png)
![bug4](https://user-images.githubusercontent.com/30157960/28184170-439c062a-67e0-11e7-9df9-0e1baed00d1d.png)
![bug5](https://user-images.githubusercontent.com/30157960/28184173-46f79244-67e0-11e7-881a-33112ef719d7.png)
It was hard to take a good picture of the bullets hitting, but watching in real time it is apparent that they don't penetrate.
 
This bug could be very easily overlooked in testing, because most of the weapons that can penetrate 150mm of armor can also destroy it in one shot.

Note- tested on newest version of BD armory and KSP, clean install with no other mods or edits. Let me know if you want my armor panels for testing, but as I said the issue is apparent with your armor as well. It's worth noting that this doesn't actually appear inconsistent with the results in the "BDArmory Armor Demonstration" video that you posted with the release. In the video it appears that nothing ever actually penetrates the armor panels, it only destroys it.
Thanks in advance.

**Comment by sjpc302** [comment]
An output log, in case that helps anyone: 

[output_log.zip](https://github.com/PapaJoesSoup/BDArmory/files/1146594/output_log.zip)

**Comment by sjpc302** [comment]
Ok, I've been doing some further testing and it seems that weapons can actually penetrate with a ludicrously high penetration value. A weapon with 68000 penetration at 100 meters can cut through anything like a hot knife through butter. A weapon with 68 penetration can go through 1mm of armor, but not 20 or 60. A test with 680 penetration had the same results as the one with 68. 6800 passes through 1mm, 20mm and 60mm, but is defeated by your 150mm plate. This is what 68mm of penetration should yield, meaning that penetration is about 100th of what it should be.

**Comment by gomker** [comment]
@sjpc302  Thanks for the research. There definitely needs to be some improvement of the system to be more accurate.

When you run your tests and record logs can you turn on "debug labels" from the BDA menu, that triggers more verbose logging and will show more of the damage stats in the log from your hits. That will also help determine what needs to be tweaked.

**Comment by sjpc302** [comment]
Ok, so should I do a couple different tests with different penetration values and provide the logs for each?

**Comment by gomker** [comment]
Noting related #174

For now tests should be run with the "stock" BDA Armor to make sure we are all testing with the same parameters.

**Comment by sjpc302** [comment]
I did a couple of tests. Each test used a millennium cannon and then a vulcan cannon, first against structural  panels, and then against armor panels.

Log 1: Default values.
Log 2: 151mm Penetration (all ranges)
Log 3: 200mm Penetration
Log 4: 1000mm Penetration
Log 5: 5000mm Penetration
Log 6: 10000mm Penetration - First successful penetration I've observed- shells went through 3 armor plates
Log 7: 15000mm Penetration - Same Result

By the way, the lack of mass of the armor makes it very significantly less durable to damage compared to the structural panels.
[OutputLogs.zip](https://github.com/PapaJoesSoup/BDArmory/files/1153497/OutputLogs.zip)

**Comment by FourLeopard** [comment]
@gomker Can confirm: Using just BDAC no weapons will penetrate the default armor plates. However when you set the thickness of the armor plate to a incredibly low number (ie. 0.1), penetration seems to work flawlessly, with higher penetrating weapons going through more plates than lesser penetrating weapons etc. **The cfg values of thickness for the armor plates does not correspond to the penetration values set in the bullet defs at all**. To make penetration work with the current build, the bullet penetration must be set incredibly high as shown by @sjpc302 or the thickness of the armor plate must be set incredibly low.

**Comment by gomker** [comment]
Thanks for the info guys. We are preparing a release however, these fixes won't make into this one.

With this data we should be able to re balance the system and make the configuration variables more accurate.

**Comment by gomker** [comment]
Spanner was taking a look at the system and did a few more tests. 

https://youtu.be/-I_s-zSQxZA

From his notes "Shells penetrate. But once penetrated they do no damage to any proceeding plate or structure, seemingly to pass through"

What we are seeing here is the bullet emitter is still active even after being "stopped" by the armor.  I think we can do something where we kill it off when hit by the armor layer.

**Comment by gomker** [comment]
@sjpc302  Pending release will address many of these issues. Let me know if you would like to check out a test build, or if you already know how you can compile the latest `feature_armor` branch.

**Comment by gomker** [comment]
Features in Armor Release
