### ISSUE TITLE
Crash bugs

### ISSUE THREAD

**Issue by LordDilip** [PapaJoesSoup/BDArmory#24]
i just got the mod and whenever i launch it crashes my game and glitches everything. it says there is no atmosphere and time is messed up.

i been told to give u the dropbox link to the log?
https://www.dropbox.com/s/ghyk47etmzf0s6b/output_log.txt?dl=0

**Comment by Nerfclasher** [comment]
Did you delete the crash folder because that could give me more information if you still have it and to confirm that you have the latest version of BDA witch is 0.11.1.2

**Comment by TheDestroyer111** [comment]
No matter what the logs are, can you give us a screenshot of what happens? And even no matter what the screenshot shows, this looks like you installed BDArmory wrong. The file structure should look like this:
KSP
-GameData
--Squad
--BDArmory
---Agencies, Parts, and some other files and folders
--Folders for any other mods you have
-all the other folders in there

**Comment by LordDilip** [comment]
The crash wasn't the crash where your game freezes. This was different. Whenever you launch a craft half your screen beccomes the sun and the other pure blackness. the time is glitched with day 49 Y99 99:99 and it says there is no atmosphere. you can still access the toolbars but you cant get out.

 Ill send the screenshot of what happens but i thought the mod goes into gamedata alone with the other mods?

**Comment by LordDilip** [comment]
i put the mod into squad and it still happens

**Comment by LordDilip** [comment]
i have BDArmory.0.11.1.2_08032016

**Comment by LordDilip** [comment]
wait i think i fixed it. i was watching an installation of the mod and i had to go through the folder and get the last folder that has all the files in it. thanks for your help guys!!!

**Comment by TheDestroyer111** [comment]
Do NOT put BDArmory into squad! Put it as I told you. Yes the mod does go to gamedata, but not the main folder that is unzipped and contains gamedata which contains the actual mod folder, but the actual mod folder inside gamedata inside the folder you got after unzipping this (sorry if this sounds complicated :P)

Anyway, if it's working then I think this can be closed.
