### ISSUE TITLE
Crashing?

### ISSUE THREAD

**Issue by SergentJhonson** [PapaJoesSoup/BDArmory#244]
Always crashes as soon as it hits 50cal ammo on the ammo boxes part during loading.

**Comment by gomker** [comment]
Couple of things to try first

- Do a clean install, delete the existing folder and install from [here](https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.2.1.2)
- If you have C.A.L install please remove, this will cause a conflict in ammo types
- check the ` KSP_x64_Data/output_log.txt ` when the crash occurs, or post the log to this issue.

When reporting issues please provide the following information:

- Version of KSP
- Version of BDA
- OS Build and Version
- Link to a full KSP log if reporting a problem

[See this for more information
](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)

**Comment by SergentJhonson** [comment]
KSP: 1.3.0
-Fresh out of KSP.com
BDA: 2.1.2
-Reinstalled twice
OS Build: 14393.1480
-Version: 1607

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1151573/output_log.txt)

**Comment by gomker** [comment]
Can you remove 
`\GameData\BDALoadedVesselSwitcher`
This is now included in BDA by default.

**Comment by SergentJhonson** [comment]
*sigh*
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1151587/output_log.txt)

**Comment by gomker** [comment]
It seems it is not crashing any further on the Universal ammo box which tells me there is most likely another mod conflict. I did see that Vessel Mover is not loading properly. Have you updated to the latest version [here](https://github.com/PapaJoesSoup/VesselMover/releases/tag/1.6.1)

If this still does not load it is best to make a clean copy of KSP and only install BDArmory. Then you will know for sure if it is another mod causing the issue.

**Comment by TheDogKSP** [comment]
In the latest output_log BDArmory is not even installed.
Due to the fact it crashed during OPT part processing, I would suppose it is more likely OPT related.
That mod is not 1.3 ready, afaik.

**Comment by TheDogKSP** [comment]
closed due to no mor einfo
