### ISSUE TITLE
Patriot Missile Launcher Not Tracking Targets

### ISSUE THREAD

**Issue by WolfGeek101** [PapaJoesSoup/BDArmory#246]
MAIN ISSUE: When using a Patriot missile turret, set up properly on Guard Mode and connected properly to a TWS, the turret will fail to pitch or yaw based on radar slave input. The result is a missile fired from a static launcher, often destroying the launcher or anything nearby.

Steps to reproduce:
    1. Build, fly, and radar link a TWS system and a loaded Patriot launcher
    2. Set Patriot launcher to Guard Mode
    3. Build and fly a plane, switching to the team opposite the missile launcher after takeoff

**Comment by gomker** [comment]
Is the Tracking radar physically attached to the Launcher or are they separate crafts?
Can you also let me know if this issue occurs with the attach craft.

[Test - Platform - BDA Missile.zip](https://github.com/PapaJoesSoup/BDArmory/files/1164276/Test.-.Platform.-.BDA.Missile.zip)

**Comment by WolfGeek101** [comment]
Thus far, the bug has had no correlation to the position of the Tracking radar, be it on the craft or on another. I'll test that craft and edit this response.

**Comment by gomker** [comment]
@WolfGeek101 I would suggesting trying to do a clean install with the latest release. All turreted radar guided missiles are behaving as expected during testing with guard mode.

https://youtu.be/ZN50b74K-u4

If you are still seeing issues please turn on debug labels in the BDA Menu and send us your KSP.log

**Comment by gomker** [comment]
Closing issue  - no update and unable to validate
