### ISSUE TITLE
Ballistic Missile Improvements

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#247]
- [x] Adjust cruise phase thrust to account for atmosphere
- [x] AOA adjustments for top of boost arc
- [ ] Maximum static launch range ignored by GPS targeting - needs fix
- [ ] Additional boost stage for Ballistic missiles

Future State
- [x] True Ballistic missile capability above atmosphere , control will require RCS

**Comment by Takemorikohoto** [comment]
well gonna PAC-3 MSE all the way

**Comment by jrodrigv** [comment]
We can say this enhancement will be released with the next release :)
