### ISSUE TITLE
Slight Explosion/bullet fx bug with Bd Armory continued 1.3

### ISSUE THREAD

**Issue by RyuAzuku** [PapaJoesSoup/BDArmory#249]
Everything with the mod is working fine except for a slight bug with the fx. Sometimes when I say drop a bomb on a building via a plane the smoke/explosion fx wont be on the building I have dropped said bomb on, instead it'll pop up right in front of me. The damage delt is still the exact same, its just a visual thing. 

The plane used was stock and only included BD armory parts.

I am running multiple mods(all up to date) here's a list:
KAX
Firespitter
Infernal Robotics
Take Command
BdArmory
Kerbal Foundries
Quantum Struts
All Near Future mods
Bluedog Design Bureau
Feline Utility Rover
Mk2 Stockalike Expansion
SXT
B9 Aerospace
Tweakscale
Tweakable Everything
All Space-Y mods
Vessel Mover
KAS
KIS
Scansat
Hanger Extender
Procedural Parts
Mechjeb
Universal Storage
CxAerospace
Stockalike Station Expansion
Hooligan Labs Airships
KW Rocketry
Hullcam VDS
Hyperedit
Persistant Rotation
Heat Control

Output Log:
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1167029/output_log.txt)

**Comment by RyuAzuku** [comment]
IDK how to add lables to this sorry

**Comment by MuricanJeb** [comment]
The devs are the only ones that can add labels.
But yes, I encounter this bug. For me, it's not common but not rare either.

**Comment by jrodrigv** [comment]
Thanks, this issue was already reported here #171

**Comment by jrodrigv** [comment]
Closing duplicate issue.
