### ISSUE TITLE
HE-KV 1 is broken

### ISSUE THREAD

**Issue by TheDestroyer111** [PapaJoesSoup/BDArmory#25]
I know it is clearly written that the missile is broken, but this should be fixed. Upon firing, regardless if fired with radar lock or without one, it draws a clearly visible red line and engages both thrusters and thrust vectoring in weird directions. The bug appeared before you started developing BDA - IIRC the missile was already broken in 0.10.x.

**Comment by DoctorDavinci** [comment]
This part has been labelled as broken and as such, will not work properly. We are aware of the issue with this part and will be endeavoring to address it in due course.

**Comment by TheDestroyer111** [comment]
What exactly is the issue? I want to know the reason behind it.

**Comment by DoctorDavinci** [comment]
Consider this ... it's been 15 days since our coders started to look through code (July 28th the BDAc team was formed) and considering that the development of BDAc is voluntary and done in our spare time when we do not have real life getting in the way such as work, paying the bills, kids etc.....

**Comment by gomker** [comment]
This issue of HE-KV was discussed at length in the old forum thread when the new targeting methods were released. If I remember correctly the consensus was that the missile did not fit into what BDArmory had grown into with realistic Heat and Radar targeting.  The part was left in as not to break anyone's vessels.

The TLDR for why it does not work is that it was never updated to work with the new targeting code.

**Comment by SpannerMonkey** [comment]
I have exported and examined the model and the related source code, The missile is propelled and steered solely by RCS thrusters, possessing the transforms named in the source (hard coded) I would conclude after some tests that the RCS is either not being initialised (which it seems to be in the code) or the plugin is not talking to the right bit of ksp code. (and the part it needs to talk to may no longer be accessible) 
 When activated the missile displays what appears to be a vector indication line, this seems to be a coded item as once I'd added a thrust transform and run the model through unity (the model in unity shows no graphical additions) back into ksp, the vector line persists. I would suggest as I have previously mentioned is that the RCS issue and it's guidance element are a fault

This is not furthering the request, more putting on record that the missile has been examined at the model level and nothing (if the missile is RCS powered only) is amiss, colliders and transforms being correctly named and oriented

**Comment by NextStarIndustries** [comment]
@jrodrigv I wanted to confirm that after basic testing this issue is resolved with the testing dev build you released.

**Comment by jrodrigv** [comment]
@NextStarIndustries wow...I'm doing some orbital testing right now. I might need to do some tweaks to the cfg.

**Comment by jrodrigv** [comment]
@NextStarIndustries after some testing using two ships following the same orbit and at 4.5 km distance. The missile didn't manage to hit the target.

So I can't say it is fixed right now

**Comment by NextStarIndustries** [comment]
I'm sorry I should have been a bit more specific as to what I did. I only tested a bore site engagement at 100 meters which had a positive result. I didn't have a radar equipped vessel for radar lock and so I hadn't tested that aspect of it yet. I'll play with the configs has well when I get out of this hospital and get home. Sorry if I caused some confusion here.

**Comment by jrodrigv** [comment]
No worries :)

**Comment by gomker** [comment]
Do we still consider this fully broken after this example 
https://youtu.be/hSXVFrWRVCo

I think it's performing almost as it did before

**Comment by jrodrigv** [comment]
Yes. I think we can close this one.
