### ISSUE TITLE
My BDArmory can not find weapon manager sometimes it can not find the weapon

### ISSUE THREAD

**Issue by iamontheearth** [PapaJoesSoup/BDArmory#250]
i put every thing it need to be work on it but it is not working

**Comment by PapaJoesSoup** [comment]
Hi!.  thanks for reporting your issue on Github.  Unfortunately you have not provided enough information for us to help you.  your installation could be incorrect, or some other issue could be occurring.

Please go to the KSP forum read the original post (OP) for BDA continued (found in the Wiki link above), and follow the troubleshooting instructions there.  

For now, I will close this issue.  if you still have problems, provide the info it spells out in a comment to this issue, and then we can assist you.
