### ISSUE TITLE
Part issue

### ISSUE THREAD

**Issue by Lammet** [PapaJoesSoup/BDArmory#251]
I got BDA and the BDA parts tab where are the parts are (idk name) is not there, I found it in the filter by manufacturer and then took the module manager and placed it on a part and I could not right click on it and I tried it on launch and the little icon on the top right was not showing like wtf HELP!

**Comment by PapaJoesSoup** [comment]
Sound like the install is incorrect.  Please refer to the wiki link above.  Go to the bathroom forum thread, and follow the troubleshooting instructions there.

I will close this issue for now, as that post should answer you questions.  If you still have issues after following those steps, add a comment to this issue along with the required files (also contained in the forum op).
