### ISSUE TITLE
Defense turrets frozen. (?)

### ISSUE THREAD

**Issue by Pinecone227** [PapaJoesSoup/BDArmory#252]
Ive built some defense systems and scattered them around KSC, they include simple radars on wheels (or tracks) as well as CIWS turrets and AA guided missile trucks, the issue is, you have to switch to them or get insanely close to one for it to start firing or detecting you, from a distance i can see that the radars are stuck in place (not disabled, some are half-rotated) Like they are not loaded fully and i only see them as physicsless props.

**Comment by TheDogKSP** [comment]
BDA requires the use of physics range extender, otherwise your vessel physics load distance is like a few hundret metres only.
https://github.com/jrodrigv/PhysicsRangeExtender/releases

**Comment by Pinecone227** [comment]
Thank you, ill try it out in a few minutes,

**Comment by Pinecone227** [comment]
Yup, problem solved. Thanks!
