### ISSUE TITLE
vehicles not firing on guard mode beyond roughly 300 meters away (i suspect the physycs load distance).

### ISSUE THREAD

**Issue by jetpack14** [PapaJoesSoup/BDArmory#263]
If I set up a turret or such and put it on the enemy team and on guard mode, it doesn't fire at me or anything else until I am very close to it (roughly 300 meters). I understand this might be a problem with the  physics load distance but my settings menu does not seem to have the setting that changes it that is mentioned in the wiki. How could I fix this problem? thank you. #

**Comment by gomker** [comment]
Here are some things to check

- Do you have ammo for the turret?

- Is the turret set to engage "Air" if targeting planes ?

- Weapons now have a greater minimum / maximum engagement range. Too close and they will not fire same for too far

- Orientation of the weapon manager - make sure its "flat" or horizontal - turn on the debug options in the settings menu to see if it is scanning or locking to targets

- The "Visual range" is now really the "targeting range" (name to be updated soon) - the default is 5KM - probably not your issue just wanted to note it

There are some sample craft included in the `/gamedata/bdarmory/craft` directory  that you can use as a base line test. I  recommend launching one of the platforms against the AI plane.

Regards,

**Comment by jetpack14** [comment]
I tested it with the sample craft but the problem persisted, the turret didn't fire until I came within 300 meters or so. I found something else that seems to be related to this problem which is that the vessel switcher doesn't list ships farther than 300 (or so) meters away from me which I feel may be related to the cause of the problem.  When I said load distance I wasn't trying to refer to the visual range of the gun but to the distance from the vehicle in focus at which the game stops simulating the physics for vehicles far from you. The mod used to (or might still have but I might be looking in the wrong place) have a setting that altered this distance but it doesn't seem to show up on mine. I found a picture on the wiki of the menu in which I understand this setting is listed but the setting labeled "physics load distance" in the image the wiki provides in this link. http://bdarmory.wikia.com/wiki/Settings_Window#Dogfight_Competition 
is there any other way to change the physics load distance?
Thanks again

**Comment by jrodrigv** [comment]
@jetpack14 Please before installing a mod you should read first the OP of the forum thread.

You will see that Armory has a dependency that has to be installed first. You need to install PhysicsRangeExtender first. https://github.com/jrodrigv/PhysicsRangeExtender/releases/tag/1.4.0

**Comment by jetpack14** [comment]
I'm sorry. I had tried to find all of the dependencies but the forum link hadn't worked for me so I assumed dependencies could be found elsewhere. Thank you for being patient with me. :D Thanks
