### ISSUE TITLE
Feature: radar range & stealth

### ISSUE THREAD

**Issue by TheDogKSP** [PapaJoesSoup/BDArmory#266]
This is to keep track of the feature development for radar refactoring regarding range and stealth

##### ISSUE TYPE
 - Enhancement  (Expand on existing features)
-  Linked feature requests: #170 #84 #43 

##### KSP and BDA Version
- future bda release

##### SUMMARY
Feature components
- [x] new gpu shader to calculate radar cross section (rcs) based on reflectivity (allows for 1st generation stealth with building using angled surfaces)
- [x] in-editor addon/window to show radar cross section during craft design
- [x] radar partmodule refactoring: add FloatCurves to define exact ranges and rcs capabilities for detection and tracking/locking, add option to define how much radar is affected by ground clutter factor
- [x] reconfigure all BDAc stock radars with meaningful settings for above parameters
- [x] provide extensive documentation and part config template how to set & use these parameters
- [x] provide MM patches for all 3rd party radars as suggestion/input to modders (AN/SPY, APAR, SMART-L, ...)
- [x] balance missiles with active radar homing into this scheme (code)
- [x] balance missile detectability (part config ability)
- [x] balance ECM jammers into this scheme (code, maybe part config updates required)
- [x] provide extensive documentation and part config template how to set & use ECM jammers which act as traditional jammers (breaking radar locks)
- [x] provide extensive documentation and part config template how to set & use ECM jammers which act as "radar absorbent materials" to reduce radar cross section (allows for 2nd generation stealth with using special parts that flat out reduce a craft's rcs)
- [x] internal team review, testing & balancing
- [x] open beta with 3rd party modders

Discussion / review points:
- [x] Chaff effectiveness in air and surface scenarios
- [x] Aircraft vs ship detectability: manageable in the current system, or do we need additional options to make radars more/less eficient in surface/horizon search?

**Comment by Takemorikohoto** [comment]
who would ever think that this would be implanted into a mod but please keep the mod small because the bigger the mod more problem will have to solve and will take longer for devs to fix and update mod just saying

**Comment by PapaJoesSoup** [comment]
Too late for that! :D  However your concern is duly noted.  One of the issues the team faced early on was the sheer complexity of what BahamutoD produced.  Over the past year, as we have gained a better understanding of the mod, we have begun the process of "breaking apart the pieces" and modularizing the feature set.

Already we have begun this process and starting with the new BDA.Core, we have started reorganizing and optimizing the code.  as we progress further, we will build a "framework", so that features and components can be pluged in, and better managed.

**Comment by Takemorikohoto** [comment]
wait great but well but keep the guard up who know what happen with ksp devs maybe they decide that it would be fun to edit some file and ruin everything like now FAR is still 1.2.2

**Comment by gomker** [comment]
Not sure if you know but all the people in this thread right now are the devs :) (it says "collaborator" next to our names)

**Comment by Takemorikohoto** [comment]
also i think you guys should add IRST as it was feature on alot of plane and ECM it quite useless now in dogfight as missile just ram up the plane ass even flare and chaff and ECM is active

**Comment by PapaJoesSoup** [comment]
In reference to the KSP devs, that is a constant battle, as long as development continues on KSP.  It is both expected and planned for. In many cases the changes benefit us.

**Comment by SquaredRoot** [comment]
Man this is beautiful. Looking forwards to it! Finally, a reason to update to 1.3!

**Comment by Isenderen** [comment]
Something ive noticed on this feature in the newest dev release that implemented the RCS, is that stealth seems to be extremely overpowered. One of my Attackers with a bunch of weapon rails on it is only detectable at 35 km and lockable at 26 km with the AN/APG-63V2 which has consistently proven to be the most powerful of the radars. This seems like its way too close of a distance to me.

**Comment by TheDogKSP** [comment]
??? How can 35km be "too close" ???
35km is the configured MAX RANGE of the AN/APG-63V2... it wont detect anything further out!

**Comment by TheDogKSP** [comment]
v1.0.0 released, closing this issue
