### ISSUE TITLE
Nukes and Bombs Malfunction

### ISSUE THREAD

**Issue by JOHN-CENA21** [PapaJoesSoup/BDArmory#267]
##### ISSUE TYPE
 - Support 	    ( Need help getting something to work)

##### KSP and BDA Version

1.3

1.3

##### OS / ENVIRONMENT
???
##### SUMMARY
**Nukes and bombs just explode normally without the effect**

**Comment by DoctorDavinci** [comment]
There are no nukes in BDAc so I would assume they won't work

As for the bombs, which ones?

KSP.log?

**Comment by NextStarIndustries** [comment]
@JOHN-CENA21 There are currently 2 mods supporting nuclear weapons NKD and mine.
To report an issue with NKD go [here](http://forum.kerbalspaceprogram.com/index.php?/topic/118667-wip130-north-kerbin-dynamics-nuclear-bombs-and-heavy-ordnance-pack-and-other-things-v082)
To report an issue about mine go [here](http://forum.kerbalspaceprogram.com/index.php?/topic/162473-13-next-star-industries-bdarmory-weapons-extension-v19)
From what you have posted here it really sounds like a NKD issue.

**Comment by gomker** [comment]
Hi @JOHN-CENA21 , Nuclear bombs are not supported by base BDArmory. Those extensions live with the mods mentioned above. BDA is the base for these mods and they do have dependencies and sometimes need to be recompiled when BDA releases an update. Please check the respective forums for the nuclear weapon mod that you are using.

Thanks
