### ISSUE TITLE
torpedo isn't work correctly

### ISSUE THREAD

**Issue by cxf213** [PapaJoesSoup/BDArmory#269]
##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version

```KSP:1.3.0

```BDA：0.3.0.0

##### OS / ENVIRONMENT

Win 10 64bit

##### SUMMARY

torpedo has no buoyancy,it always sink into the bottom of the sea.
I try to change buoyancyForce in Configuration file,but it still no effect.

**Comment by TheDogKSP** [comment]
Which torpedo from which mod? I suspect you are talking about a part from NAS (naval artillery system)...

**Comment by cxf213** [comment]
yeah,NAS

**Comment by NextStarIndustries** [comment]
NAS has been broken by the recent update release of BDA 0.3.0.0

**Comment by gomker** [comment]
There is also an included torpedo in BDA now you can use until NAS has been updated.

**Comment by cxf213** [comment]
I delete NAS,but the torpedo in BDA have same problem
![zfuxy oc9ftt 3 0 jl](https://user-images.githubusercontent.com/26163328/29007419-834fe076-7b35-11e7-955a-786af5db0c30.png)

**Comment by PapaJoesSoup** [comment]
I believe PRE is required still... Do you have Physics Range Extender installed?   That is now a dependency for BDAc...

**Comment by cxf213** [comment]
yeah,i have PRE,here is output file.

[KSP.log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1203498/KSP.log.txt)
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1203499/output_log.txt)

**Comment by TheDogKSP** [comment]
Your installation looks fine, no errors in your log.

The BDA torpedos are guided torpedos, and need a radar (sonar) lock on something before they can be fired. They are not "dumb fire and go straight" torpedos like in NAS.
DId you include a sonar pod in your sub? 
Did you lock onto sth before firing?

**Comment by cxf213** [comment]
ty,it works again
