### ISSUE TITLE
Not all parts are downloaded and weapons manager doesn't work

### ISSUE THREAD

**Issue by ianmck2003** [PapaJoesSoup/BDArmory#271]
##### ISSUE TYPE

 - Support   

##### KSP and BDA Version

1.3

BD armory continued

##### OS / ENVIRONMENT
macOS Sierra

##### SUMMARY
I placed the BDArmory-master folder into my game data folder as instructed. When I opened KSP and went into the SPH, I found that the BDArmory tab didn't have a label. It was basically a white parts tab. When I opened the tab, I found that almost all of the targeting parts were missing. When I tested the weapons manager after placing some unguided bombs on a stock plane, the tabs on the interface did not work. Explosives like the small high explosive warhead also don't explode.

I do have Kerbal Konstructs downloaded if that will cause problems.

KSP log (wouldn't accept .log files)

[KSP.pdf](https://github.com/PapaJoesSoup/BDArmory/files/1206609/KSP.pdf)

**Comment by PapaJoesSoup** [comment]
You need to install the contents of the zip file, and not the source code.   your installation is incorrect.

Please refer to closed issue #264 https://github.com/PapaJoesSoup/BDArmory/issues/264
for detailed instruction on how to install BDA properly.

**Comment by ianmck2003** [comment]
Ok thanks!

You guys are the best!

**Comment by ianmck2003** [comment]
Looks like I downloaded the wrong version.

Once again, Thanks!

**Comment by PapaJoesSoup** [comment]
Glad you are up and running.
