### ISSUE TITLE
Request - Missiles become lighter as they burn fuel

### ISSUE THREAD

**Issue by goduranus** [PapaJoesSoup/BDArmory#287]
Real missiles become lighter and more maneuverable as fuel is burned. This is a request for single piece missiles that comes with BDA to have fuel in them, that burns away as the missile flies, so the missiles's acceleration and maneuverability increases as it flies off, for added realism.

**Comment by NextStarIndustries** [comment]
This is a known bug/issue and has already been reported/opened in Issue #21.

**Comment by gomker** [comment]
@goduranus If you could, please add any notes about behavior to Issue #21. We are tracking the work there. Thanks
