### ISSUE TITLE
ksp 1.3 bdarmory 3.0 wont fidn weapons manager 

### ISSUE THREAD

**Issue by toby2001** [PapaJoesSoup/BDArmory#288]
i have a weapons manager on my caft adn it wont find it at all it just says cant find it 
![screenshot 1](https://user-images.githubusercontent.com/31238989/29556792-4d0e9a48-876a-11e7-88ff-3b1dcf5983ed.png) 
 
im using the newest bdarmory and ksp 1.3 plzzz help

**Comment by jrodrigv** [comment]
We need the KSP. log. 

This seems a wrong INSTALLATION. I suggest to review the closed issues, almost every week someone is reporting something similar.

**Comment by toby2001** [comment]
where do i get the log from ?

**Comment by toby2001** [comment]
[KSP.log.docx](https://github.com/PapaJoesSoup/BDArmory/files/1241588/KSP.log.docx)
ok got it here u go

**Comment by XOC2008** [comment]
Considering he has 2 BDArmory tabs on the side there, I'd say that it is DEFINITELY an installation issue.

**Comment by jrodrigv** [comment]
@toby2001 I suggest to read this closed issue https://github.com/PapaJoesSoup/BDArmory/issues/271

I also suggest to re-read the OP (first post of BDArmory forum thread) installation instructions.

Without any doubt you did a wrong installation. I will close this issue and re-open if necessary.

**Comment by toby2001** [comment]
ok thanks i deleted it and will reinstall soon

**Comment by toby2001** [comment]
hey mate thanks it worked would u recomend getting both bda and bda continued ?

**Comment by jrodrigv** [comment]
Of course not :) There is only one valid BDArmory. BDArmory Continued

**Comment by PapaJoesSoup** [comment]
Just as a clarification, BDArmory (BDA) was the original mod.  When BahamutoD moved on, we took over maintenance.  THe mod was then renamed to BDArmory Continued (BDAc).  The original BDA is frozen at 0.11.1, and only works on Pre KSP 1.2.  So you can safely forget about the original BDA.  All that it was is included in BDAc, lus all the work we have put in to fix and enhance it.
