### ISSUE TITLE
Missile guidance bug

### ISSUE THREAD

**Issue by Laihela** [PapaJoesSoup/BDArmory#293]
##### ISSUE TYPE
```
Bug Report (unconfirmed)
```

##### KSP and BDA Version
```
KSP 1.3.0 (64-bit)
BDA 0.3.0.0
```

##### OS / ENVIRONMENT
```
Windows 10 (64 bit)
```

##### SUMMARY
```
Missiles ignore guidance loss in some cases.
```

##### STEPS TO REPRODUCE

1. Fire a missile guided by radar or a laser at a target.
1. Loose the target by turning off or destroying the radar/laser.
1. The missile will continue tracking the target despite losing guidance.

##### LOG FILES

*Unconfirmed, I will experiment later today after returning from school...*

**Comment by XOC2008** [comment]
I'm pretty sure in most cases missiles will continue towards the last known good target even if radar or laser is disabled on the originating craft.

**Comment by Laihela** [comment]
If an AMRAAM or PAC-3 turret fires a missile at you and loses radar lock, the missile won't track the vessel anymore. This means radar guided missiles are not fire-and-forget and need to maintain lock in order to track the target. If laser guided missiles would continue to fly at the last designated target then wouldn't that make smoke screens useless? Since you wouldn't have any time to dispense smoke before the missile would already be on it's way, and moving to avoid it would reveal the vehicle anyway.

**Comment by gomker** [comment]
@Laihela 
Radar Lock On After Launch is controlled by the variable `radarLOAL` of the missile. If you turn on debug labels during your game see if messages like the following are in the log

`[BDArmory]: Pitbull! Radar missileBase has gone active`
`[BDArmory]: Radar missileBase reached max re-lock attempts`
`[BDArmory]: Radar guidance failed`

The missile could be failing to re acquire the target for many reasons and the debug messages will help us determine why.

**Comment by jrodrigv** [comment]
Closing issue missing logs
