### ISSUE TITLE
Weapon Manager not found, when there is one on the craft

### ISSUE THREAD

**Issue by skitzbuckethatz** [PapaJoesSoup/BDArmory#294]
When reporting issues please provide the following information:
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version
KSP version 1.3
```
BDAc version 0.3.0.0
```
##### OS / ENVIRONMENT
macOS, Windows

##### SUMMARY
When there is a Weapon manager on the craft, the game does not detect it. I have reinstalled everything and it is all up to date. 

##### STEPS TO REPRODUCE
Place a weapon manager on craft, launch craft, click the BD tab

**Comment by PapaJoesSoup** [comment]
Please refer to this post: https://forum.kerbalspaceprogram.com/index.php?/topic/155014-13-bdarmory-continued-v0300-7282017-vessel-mover-camera-tools-bdmk22-destruction-effects-burn-together/ for insctructions on installation and troubleshooting.  as part of the instructions, it will direct you to providing log files for our review to aid you in your issue.

Please note that the error you are experiencing is almost ALWAYS related to an incorrect installation.
Refer to this Git issue for clarification on how BDA "should" be installed:  https://github.com/PapaJoesSoup/BDArmory/issues/288
and 
https://github.com/PapaJoesSoup/BDArmory/issues/271

Good luck with getting your install right.

**Comment by skitzbuckethatz** [comment]
I have read over and over the installation instructions. I have the folder with the mod in it, inside of my KSP gamedata folder. I have reinstalled a few times. I have made sure that there is no other old BDAc files anywhere.

**Comment by PapaJoesSoup** [comment]
KSP.log and output.txt files please...

**Comment by jrodrigv** [comment]
Closing issue lack of logs from the user
