### ISSUE TITLE
PAC-3 lag issue

### ISSUE THREAD

**Issue by jrodrigv** [PapaJoesSoup/BDArmory#3]
This is a well-known issue and easy to reproduce.

When you fire a PAC-3 missile the FPS drops drastically over time. I think this is due to the smoke particles.

**Comment by jrodrigv** [comment]
@PapaJoesSoup I have fixed this on the support branch (just editing the part file). Maybe you can apply this fix to Master.

I have found the problem. It seems that the PAC-3 is using the only part using the largeExhaust model and it is clearly too GPU intensive. I have changed the exhaust to the medium one and it works perfect with no lag.
Evidence here;
Before: https://youtu.be/LT5TQ8t16eA
After: https://youtu.be/Zfh3cEQqL3o

**Comment by Nerfclasher** [comment]
I have issued a pr
