### ISSUE TITLE
Jettison on the rotary bomb rack is broken #31

### ISSUE THREAD

**Issue by Nerfclasher** [PapaJoesSoup/BDArmory#30]
Using the bomb rack works, but if you jettison the active bomb/missile, it fails to cycle.
from https://github.com/BahamutoD/BDArmory/issues/31

**Comment by DoctorDavinci** [comment]
Confirmed ... Rack fails to cycle

In addition to this I have discovered that the gremlin is bigger than just the glitch as mentioned in the post https://github.com/BahamutoD/BDArmory/issues/31

I used the Mk82 and found when I jettisoned one that the rack didn't cycle as reported, however I also discovered that the jettisoned bombs were treated as debris as well as not being affected by gravity. 

Another thing of note is the drag fins deployed on the jettisoned Mk82's and they were slowing the bomb down while the bombs in question were still gaining altitude and traveling on a straight trajectory at less than 20m/s

Watch the video - https://youtu.be/iJB5DgOQvc8

**Comment by gomker** [comment]
Bomb Rack is currently out of commission for time being #76

**Comment by gomker** [comment]
Bomb Rack has been fixed a few releases ago

**Comment by jrodrigv** [comment]
I think we need to test the 'Jettison'

**Comment by gomker** [comment]
Sounds good, will test

**Comment by gomker** [comment]
Jettison confirmed working
