### ISSUE TITLE
Missiles doing no damage

### ISSUE THREAD

**Issue by ChavezAndreas** [PapaJoesSoup/BDArmory#303]
When I fire missiles at a target, they explode but do no damage. I've noticed when I'm in the VAB or SPH the missiles have a description with Blast Radius/ Blast Power/ Heat. And for the heat value, it's -1 but in the code it's either a value like 50, or there is no value at all. I'm just wondering how to make the missiles do damage. This is for KSP 1.3 and BDA 0.3 on Windows 10.

 - Support

**Comment by jrodrigv** [comment]
Hi.

I would need your  KSP.log and also I need more information about the
target vessel and the missile used.


If you can attach the craft file or a saved game files, it would be very
useful.
I would like to reproduce the issue.
.

**Comment by ChavezAndreas** [comment]
Target is a base with parts primarily from Planetary Base Systems and Stockalike Station Parts Add-on, both are up to date and compatible with 1.3. I am primarily using laser guided missiles; the maverick and the hellfire missile. I also tried with the sidewinder heat seeking missile.  I'm not sure how to attach those files on this forum.

**Comment by jrodrigv** [comment]
Which is the size of the base?

You can drag & and drop files here attaching it to your comment.

I would like to reproduce the issue using stocks parts mainly if it possible

**Comment by ChavezAndreas** [comment]
Here's the output log:
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1313216/output_log.txt)

I've tried with other targets like simple stock fuel tanks, and still no damage done.

Here's the sidewinder missile file along with a screenshot of the in game information, it doesn't do any damage in the game and has no heat in the code:
PART
{
	// Kerbal Space Program - Part Config

	// --- general parameters ---
	name = bahaAim9
	module = Part
	author = BahamutoD

	// --- asset parameters ---
	mesh = model.mu
	rescaleFactor = 1

	// --- node definitions ---
	node_attach = 0.0, 0.06188124, 0, 0, 1, 0, 0
	node_stack_top = 0.0, 0.06188124, 0, 0, 1, 0, 0

	// --- editor parameters ---
	TechRequired = precisionEngineering
	entryCost = 2100
	cost = 1200
	category = none
	subcategory = 0
	title = AIM-9 Sidewinder Missile
	manufacturer = Bahamuto Dynamics
	description = Short range heat seeking missile.
	// attachment rules: stack, srfAttach, allowStack, allowSrfAttach, allowCollision
	attachRules = 1,1,0,0,1

	// --- standard part parameters ---
	mass = 0.085
	dragModelType = default
	maximum_drag = 0.01
	minimum_drag = 0.01
	angularDrag = 2
	crashTolerance = 5
	maxTemp = 3600


	MODULE
	{
		name = MissileLauncher

		shortName = AIM-9

		thrust = 18 //KN thrust during boost phase
		cruiseThrust = 1 //thrust during cruise phase
		dropTime = 0 //how many seconds after release until engine ignites
		boostTime = 2.2 //seconds of boost phase
		cruiseTime = 10 //seconds of cruise phase
		guidanceActive = true //missile has guidanceActive
		blastRadius = 15 //meters
		blastPower = 12
		maxTurnRateDPS = 45 //degrees per second

		audioClipPath = BDArmory/Sounds/rocketLoop
		exhaustPrefabPath = BDArmory/Models/exhaust/smallExhaust
		boostExhaustPrefabPath = BDArmory/Models/exhaust/mediumExhaust
		boostExhaustTransformName = boostTransform
		boostTransformName = boostTransform

		optimumAirspeed = 450

		aero = true
		liftArea = 0.0015
		steerMult = 4
		maxTorque = 25
		maxAoA = 30
		aeroSteerDamping = 4.5

		homingType = aam
		missileType = missile
		targetingType = heat
		heatThreshold = 150
		maxOffBoresight = 50

		minStaticLaunchRange = 200
		maxStaticLaunchRange = 8000
	  	  
	}

}


![screenshot 30](https://user-images.githubusercontent.com/32087043/30578395-298eeeb8-9cd9-11e7-8480-28b82d54d847.png)

As for the craft files, they aren't dropping into the comment

**Comment by TheDogKSP** [comment]
"Missing" heat values are not to worry about: 
if heat = -1 then heat = power.
Most likely you have a problem with the detonation radius, as the missile detonates too far away from the target. Unfortunately we currently default to use the blast radius as detonation distance.
Try setting it to zero (right click the attached part on the craft and set detonation distance to zero), then it should explode on impact only.

**Comment by jrodrigv** [comment]
I agree with @TheDogKSP as the root cause. Did you try the Maverick with a Detonation range of 10m?

**Comment by ChavezAndreas** [comment]
That was the problem, thank you both!
