### ISSUE TITLE
issue #46 from Baha repository: dragAccel set in BDAirspeedControl.MaxEngineAccel() can be positive in climb

### ISSUE THREAD

**Issue by RichardDastardly** [PapaJoesSoup/BDArmory#305]
Original issue: [https://github.com/BahamutoD/BDArmory/issues/46](https://github.com/BahamutoD/BDArmory/issues/46)

 - Bug Report   (Something is broken - maybe - needs crosscheck)

##### KSP and BDA Version
KSP 1.3
BDAc 0.3.0.0

##### OS / ENVIRONMENT
w7

##### SUMMARY
Explained ( in some manner ) in previous issue: brief summary, throttle rolloff in zoom climb despite target speed > current speed ( I believe because of a faulty acceleration prediction indicating an overshoot ). I fixed my own build after raising the previous issue, but I wasn't aware of the complete intent of that function so it was mostly guesswork ( fix is also explained in previous issue ).

##### STEPS TO REPRODUCE
Craft self-reproduces on zoom-climb. Suitable debugging labels will show what's going on - important one seems to be dragAccel, output of Control/BDAirspeedControl.cs#150, but I think the actual error is in the calculation at line 148.

##### Log Files
Video link in previously raised issue.

**Comment by RichardDastardly** [comment]
Thinking about it I guess it should actually be positive in a steep dive, in which case my quick fix appeared more reasonable than I thought.

**Comment by RichardDastardly** [comment]
OK - that quick fix appears to still work ( the code looks the same, not surprising ); I haven't thoroughly checked or seen if a rewrite of the area would fix it better. Having some issues with github right now so no PR.

Line 148: add +GravAccel() somewhere outside the bracket sets - when a craft is climbing GravAccel returns a negative, so it must be added rather than subtracted.

Post fix: I added a few labels from BDAirspeedControl to the left

[extending climbing to default alt, throttle still on full](https://flic.kr/p/XLjpNA)
[after rolling over the top & dropping down again](https://flic.kr/p/XLjpNA) - note gravAccel is positive in a dive.

**Comment by DoctorDavinci** [comment]
Thanks for the info

If you have a working fix for this then perhaps you could do a pull request so that our code guru's can take a look

Thanks

**Comment by RichardDastardly** [comment]
I would if git would cooperate - my quick fix just adds "-GravAccel()" to the end of line 148 right now, I haven't actually rewritten the whole process properly yet.

**Comment by RichardDastardly** [comment]
Did a little work - I think the problem is actually in the method used to get the right vector component of various accelerations; I gave up & computed acceleration from vessel speed & it doesn't match the output of using Vector3.Project, I'll have to try computing acceleration from gravity down the velocity vector too.

My understanding of Vector3.Project ( Baha's too, by the looks of it ) is it's supposed to give you the overlap of the vector you're projecting along the vector you're projecting onto - so taking the magnitude of the craft acceleration vector projected onto it's transform forward ( up, in the case of KSP aircraft ) vector should literally be it's acceleration along the velocity vector - however it's not matching the computed figure from srf_speed unless it's flying straight & level.

**Comment by RichardDastardly** [comment]
Vector3.Project projects onto unit vectors. That's that bit fixed, using acceleration_immediate fixed some other laggy control update issues, and adding current gravity to the estimated thrust has fixed zoom climb. I've also changed the reference vector in all this from forwards on the craft to the velocity vector, but that will need some thought about dealing with supermaneuverable aircraft. I get the feeling this whole module needs some cleaning up, but that can come some other time.

What I haven't managed to do is get gh to behave, so still no way of making a PR...

**Comment by jrodrigv** [comment]
Hi @RichardDastardly . I would like to review the code changes in order to integrate them. 
Can I help you to do a Pull Request? Do you have your code changes on a fork?

Thanks

**Comment by RichardDastardly** [comment]
Hi,

Yeah, I'd have made a PR ( if I can remember how, it's been a while! ) but I've been having a lot of trouble getting my dev env to sync with this fork - just when I think I've got everything pointed at the right place it goes back to Baha's repository again. I'm going to start clean again when I have some time to do all the setup over.

**Comment by gomker** [comment]
@RichardDastardly I tried to throw together some quick docs on contribution and building BDA

https://github.com/PapaJoesSoup/BDArmory/wiki/How-to-Contribute
https://github.com/PapaJoesSoup/BDArmory/wiki/Build-Instructions

We are in the middle of the Radar updates (theDog) and JR and I are neck deep in the Armor and Damage refactor.  Please feel free to look into any AI stuff you like, the issue tagging should help you find related problems.

Also when you do fork this repo, I would recommend you start a your branch from the `dev` branch

Regards,

**Comment by TheDogKSP** [comment]
FIXED by PR #331

**Comment by RichardDastardly** [comment]
The only further issue with this might be some oddness relating to supermaneuverable aircraft in post-stall when they're *way* off velocity vector - if someone does have a problem please open a new issue.
