### ISSUE TITLE
Bullets suggestion

### ISSUE THREAD

**Issue by Colonelvinnie** [PapaJoesSoup/BDArmory#310]
- Enhancement 
While the bullets in the current mod work fine for stock BDArmory I find it very difficult to balance custom armor for NAS using the armor system.

This is mostly concerning ballistic weapons.

While unsure of the exact coding, the fact that non-penetrations still cause a sizable heat damage bothers me. Below I assume heat as the exact heat in KSP. For example if said part is at 0K and max heat is 2000, it takes exactly 2000 heat to overheat it.
Note : Explosion Heat = A number set per part as the warhead (If any) in the shell. 
Suggest "(Warhead size in kg of TNT)" for simplicity.

For non-penetrations, I suggest "(explosion heat) / (armor thickness in meters)" and have an explosion animation.

For penetrated heat damage, I think it should be changed to "[1/2*(mass of bullet in KG)*(impact velocity)^2 - (friction) * (armor thickness in meters) * (Percentage of heat generated by collision)] + [(explosion heat) / (armor thickness in meters)]". This is to assume detonation after passing through the armor. In most cases this should mean the destruction of said armor piece.

Maybe this can combine both cannon and ballistic types for guns, and perhaps any bombs or missiles can also follow the same rule?

**Comment by gomker** [comment]
Hi,  we are actually working right now to revamp the entire damage system moving away from "heat" to something more resembling a hitpoint / health system. This is very early WIP and you can see our work in the `feature_armor` branch if you would like look at the current implementation.  At the moment we are looking to fix the medium caliber weapons and move up to the larger ones once we have a good baseline and your suggestions are inline so far with what the team has been designing.

A few key points on how the new system is going to work

- No more penetration curves. We have left the system in for perhaps future use, but it is deprecated at the moment
- Armor is a "resource" - can be added via Part module or the system will add a certain amount based on mass for stock parts. Example , stock plates will be 30mm of armor default.
- Damage hit points / health will be calculated roughly based on mass and maxtemp ( its more complicated than that but I don't want to get into the details in this response)
- All values for bullets, `mass` `velocity` `power` `explosive` etc.. are being moved to central bullets config, no longer per weapon. 

This is all currently work in progress and early on in development and welcome any feedback.

Regards,
