### ISSUE TITLE
Category Duplicating

### ISSUE THREAD

**Issue by NextStarIndustries** [PapaJoesSoup/BDArmory#335]
- Possible Bug

##### KSP and BDA Version

1.3

All I believe.

##### OS / ENVIRONMENT

Windows 10 fully updated

##### SUMMARY

The part category seems to be duplicating.

##### STEPS TO REPRODUCE

Enter either editor, back out and return to the Main Menu, return to the editor and the BDA part category will be duplicated. This may be a KSP bug and not BDAc I'll test other mods.

**Comment by NextStarIndustries** [comment]
I left a step out sorry. Leave editor and Press f-12, reload the database then exit out to the main menu and return.

**Comment by TheDogKSP** [comment]
This is with the 1.3.1 beta version I assume? Or do you really mean the 1.3 version?

**Comment by NextStarIndustries** [comment]
All versions of BDAc

**Comment by NextStarIndustries** [comment]
Currently testing KSP 1.3 and BDAc 0.3.0.0

**Comment by gomker** [comment]
This sounds like the root cause may be KSP - has anyone searched the bug tracker for other reports

**Comment by NextStarIndustries** [comment]
You are correct it is a KSP root problem.
