### ISSUE TITLE
Ksp glitching (probably just me not being good at ksp)

### ISSUE THREAD

**Issue by usernameisalreadytakenwhy** [PapaJoesSoup/BDArmory#343]
so
>Game glitching

i play it on a mac
( macos )
i install ksp 1.1
sees BDArmoury v0.11.0.1
compatible with 1.1 and maybe later
nice
downloads it
puts it inside Kerbal space program/Gamedata alongside with hyperedit and module manager and physic range extender
opens kerbal space program
goes to vab
builds random vehicle
launches it
game glitches.

the speed is 100000000m/s
opens map
focusing the sun
cannot click on any planets
current craft doesn't exist anymore
cannot go to menu
cannot revert
only thing can do is press esc to pause the game and vice versa but no setting menu
game broken
cannot quit game
must force quit
pls help

ksp.log when game glitching

[EXC 17:34:50.054] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.056] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.059] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.061] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.061] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
[EXC 17:34:50.104] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.106] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.109] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.110] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.111] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
[EXC 17:34:50.137] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.139] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.141] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.141] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
[EXC 17:34:50.187] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.189] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.191] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.192] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.193] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
[EXC 17:34:50.237] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.239] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.241] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.242] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.242] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
[EXC 17:34:50.288] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.290] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.294] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.296] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.297] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
[EXC 17:34:50.337] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.338] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.341] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.342] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.343] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
[EXC 17:34:50.403] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.405] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.407] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.408] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.409] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
[EXC 17:34:50.437] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.439] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.440] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.441] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.442] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
[EXC 17:34:50.487] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.488] MissingMethodException: Method not found: 'FlightGlobals.getAltitudeAtPos'.
	PhysicsRangeExtender.PhysicsRangeExtender.AvoidReferenceFrameChangeIssues ()
	PhysicsRangeExtender.PhysicsRangeExtender.FixedUpdate ()
[EXC 17:34:50.491] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.ResourceDisplay.CreateResourceList ()
	KSP.UI.Screens.ResourceDisplay.Update ()
[EXC 17:34:50.492] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilotUI.LateUpdate ()
[EXC 17:34:50.494] NullReferenceException: Object reference not set to an instance of an object
	InternalSpace.InternalToWorld (Quaternion internalSpaceRotation)
	InternalSpace.WorldToInternal (Quaternion worldSpaceRotation)
	IVASun.LateUpdate ()
and that just goes on and on
and it's larger than 10mb!
so i can't attach it!

and yes, moving the BDArmoury folder out of ksp makes it turn back to normal.
but if i don't, even without using the BDArmoury parts ( stock parts ) it would still be glitching.

i hope that is enough information for you guys
and i am a ksp noob
i good ksp
[KSP.log.zip](https://github.com/PapaJoesSoup/BDArmory/files/1426537/KSP.log.zip)

wait

i am an idiot

i could just compress them

**Comment by usernameisalreadytakenwhy** [comment]
I know I am quite impatient
but please respond when you have the time
greatly appreciated

**Comment by PapaJoesSoup** [comment]
Hi.  Your problem is an incorrect installation.  The bdarmory folder and it's contents MUST go in the gamedata folder.  It sits side by side with the squad folder (and any other folders which are other mods.)

Please refer to the op on the forums and look over the closed issues in GitHub.  You will find numerous entries related to incorrect installations.

Also refer to the first page of the wiki here on github for additional help.

Hope that helps

**Comment by PapaJoesSoup** [comment]
Additionally physics range extender is required, but not included

**Comment by usernameisalreadytakenwhy** [comment]
Oh, I meant alongside with a additionally installed physics range extended

**Comment by DoctorDavinci** [comment]
@usernameisalreadytakenwhy - First problem is that you are running KSP v1.1.0 .... the solution is to upgrade your KSP to the latest version as we no longer provide support for KSP versions prior to KSP v1.3 .... any problems you may have with BDA Continued have most likely been fixed in later versions and these versions are incompatible with KSP versions prior to v1.3

The second problem is you have installed BDAc incorrectly ... please consult the OP of our thread where it is clearly explained how to properly install BDAc (or any other mod for that matter)

https://forum.kerbalspaceprogram.com/index.php?/topic/155014-13x-bdarmory-continued-v1000-1142017-vessel-mover-camera-tools-bdmk22-destruction-effects-burn-together/

**Comment by jrodrigv** [comment]
Closing this issue. No answers after two weeks.
