### ISSUE TITLE
Feature Idea: Multiple Teams

### ISSUE THREAD

**Issue by xxmortekaixx** [PapaJoesSoup/BDArmory#359]
- Feature Idea (Something new you want to see)

More than 2 teams.  This makes multiple player war scenarios easier to manage.

**Comment by gomker** [comment]
The team has looked at this a bit in the past.  Currently it seems for simplicity sake the original code was written for two teams. Reason being if you start to have more than two teams, Friend or Foe identification becomes more complicated. There are many places in targeting were this comes into account. 
Just wanted to give you some info on the "why" of the current state. We will look at this in our next code sprint. The pending 1.4 KSP update will probably cause us to go into bugfix mode for awhile.

**Comment by Gedas-S** [comment]
Implemented in 1.3.0.
