### ISSUE TITLE
Modular Missile Issue

### ISSUE THREAD

**Issue by MrSteve10424** [PapaJoesSoup/BDArmory#362]
##### ISSUE TYPE

 - Bug Report   (Something is broken)
 - Feature Idea (Something new you want to see)
 - Enhancement  (Expand on existing features)

##### KSP and BDA Version

``` 1.3.0

```

##### OS / ENVIRONMENT
Windows 7 64 bit

##### SUMMARY
Basically, modular missiles are simply not working, I created multiple tests with them and found out that the modular missile part is disabling itself and causing it to no longer guide

##### STEPS TO REPRODUCE
Make a missile,
Put modular missile part
Fire

**Comment by jrodrigv** [comment]
Hi!
Which version of BDArmory and KSP are you using?

Can you elaborate a bit more your steps? 
- Type of missile, guidance, targeting, stages defined.
- How are you firing it? Guard mode? Locking & firing manually?
- Are you using the procedural  missile core or the stock modular guidance part?

Have you followed this guide?
https://github.com/jrodrigv/BDModularMissileParts/wiki

**Comment by MrSteve10424** [comment]
Hi jrodrigv!

KSP 1.3.0
BD Armory Version 1.0.0.0 11/4/2017

Im using the stock modular guidance part 
So it basically goes like this
I make a standard missile, fins, booster, high explosive warhead, some batteries, an SAS unit, and the modular missile part. Im firing using guard mode with the TWS locking.
 
Guidance: AAM Targeting: Radar Staging: Action group 1 Activate booster & decouple

And ive been using BD armory for quite some time now this bug is new to me.

What happens:

After loading onto the launch pad,

1. All sources of electrical charge is working for now
2. When the missile launches it goes through its launch phase, boost then guides itself for like 0.5 secs and then it just stops working and no longer guides itself because the guidance stops working when the electical charge gets depleted. (all sources of electric charge disabled, batteries, modular missile component intergrated electrical charge) All of the electrical charge.

For the record it is on stock ksp with no aditional mods installed.

**Comment by jrodrigv** [comment]
Thanks for the details! I will do some testing.

**Comment by jrodrigv** [comment]
Hi @MrSteve10424 

I have built a stock AAM missile using KSP 1.3 and the last version of BDArmory.

Everything works as expected on my end. I think your problem was the Action 1 group.

You should not add the decouple action. The decoupling is automatically triggered by the moduler missile core.
