### ISSUE TITLE
Makeshift Radar and Stealth

### ISSUE THREAD

**Issue by MrSteve10424** [PapaJoesSoup/BDArmory#363]
I have an idea for a better solution to stealth, what about using a code which measures the contours of an aircraft when the radar wants to lock onto a target and then creates an "accuracy" value which determines how accurately the missile will be guided.

**Comment by PapaJoesSoup** [comment]
The current system models real world physics and technology.  

What problem with the existing stealth solution are you attempting to solve?

**Comment by MrSteve10424** [comment]
Uhh.... Radar literally ignoring everything and heatseekers rendered useless by a couple of flares. Chaff to evade is the only one that feels somewhat balanced. Another solution is that it calculates the amount of chaff in the area around the aircraft and gives an "accuracy" percentage to the missile.

**Comment by MrSteve10424** [comment]
And contours still dont make a difference to radar for simulating "stealth"

**Comment by PapaJoesSoup** [comment]
What kind of radar, and under what conditions?  Have you reviewed the wiki covering stealth and radars in the ver 1.0.0

**Comment by PapaJoesSoup** [comment]
Also a log would be helpful to see what mods are installed, steps to reproduce. Maybe a game save to exemlify the issue.  Radars and stealth work very differently than they did previously. 

Not trying to be difficult, but 1.0.0 was extensively play tested, so we need more than it doesn't work to help yup.

**Comment by MrSteve10424** [comment]
@PapaJoesSoup  You may have posted the comments on the wrong one :P. And yes, I have reviewed the wiki.

**Comment by PapaJoesSoup** [comment]
Actually, no.

I saw your post for 362, and you provided good data with which to characterize the bug you found.

I'm this case there is scant info with which to characterize the problem that your suggestion is supposed to address.

I realize you have been playing awhile, and I mean no disrespect, but as I said, this was pretty extensively play tested in beta.

So my above questions remain.  My understanding of your proposed solution sounds a lot like what we already do, so forgive my misunderstanding.
So, depending on the type of radar being used, the issues you have described would be correct behavior.

Finally, we freely admit we are not perfect, so there could be a bug somewhere.  Again the reason for my requests for more info.

**Comment by MrSteve10424** [comment]
Anyways thanks for considering slightly tho. Ill close the thread, Its just I feel like the radar guided Aim 120s are far too OP because chaff seemingly does nothing towards them.

**Comment by PapaJoesSoup** [comment]
Your choice of course, but we do welcome suggestions.  Since you actually described a specific weapon system in your latest response, we may be able to look into your report.  

You have a lock and the weapon has been launched.  So the issue is with the seeker guidance not being fooled by chaff.

**Comment by TheDogKSP** [comment]
Chaff balance fixes done
