### ISSUE TITLE
FLIR camera picture bug

### ISSUE THREAD

**Issue by LtRyan** [PapaJoesSoup/BDArmory#371]
##### ISSUE TYPE
- Bug Report   (Something is broken)
##### KSP and BDA Version
latest

##### OS / ENVIRONMENT
Win7

##### SUMMARY
I have the problem that in any FLIR cam a watermark like mirrored picture of normal screen appears.
Means that I see my plane mirrored like a shadow in the FLIR cam

##### STEPS TO REPRODUCE
Use the any targeting pod

##### Log Files

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1492444/output_log.txt)

**Comment by gomker** [comment]
Hello, 
This is known issue (popped up in one of the last few KSP updates) I thought we had an issue for this already but got lost. The root of it has to do with KSP changes in the way the part was constructed ( I do code not part stuff, so cannot speak exactly to the issue).
We will track this in our next bugfix review.

Regards,

**Comment by gomker** [comment]
And I found it #239.

**Comment by LtRyan** [comment]
Ty
