### ISSUE TITLE
targeting pod screen shows a static purple for all targeting pods

### ISSUE THREAD

**Issue by HJP1121** [PapaJoesSoup/BDArmory#376]
##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version
KSPx64 1.3.1
```
BDA 1.0.0 
```

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY

Whenever I try to use the targeting pod it always shows a purple screen. I've tried with all the pods and all have the same problem. I'm not sure whether it's because of the mods I've installed maybe they clash with each other. Very similar to https://forum.kerbalspaceprogram.com/index.php?/topic/152513-bd-armory-targeting-pod-problems/ but my BDArmory is already at the latest version. Hope you can help, thank you very much. You are cool : )
##### STEPS TO REPRODUCE
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1502897/output_log.txt)

There isn't steps but I'll list the mods I have installed
B9_Aerospace
B9_Aerospace_ProceduralWings
B9AnimationModules
B9PartSwitch
BahaSP
BDArmory
BDArmory Weapons Extension
BDModularMissileParts-master
Chatterer
DestructionEffects
Firespitter
JNH (Dragon_KIS)
JSI (Raster Prop Monitor)
KerbalJointReinforcement
MagicSmokeIndustries
MechJeb2
North Kerbin Weaponry
PhysicsRangeExtender
ProceduralFairings
SM_Armory
SM_Industries
TweakScale
VesselMover

##### Log Files

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1502898/output_log.txt)
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/1502899/KSP.log)

**Comment by DoctorDavinci** [comment]
As mentioned in our forum thread, you are forcing opengl which is the reason you are seeing purple/magenta

The only solution is to NOT force opengl

**Comment by jrodrigv** [comment]
In addition to what @DoctorDavinci said. I suggest forcing DX11 I have been playing with Dx11 for the last couple of years, no problems at all.

**Comment by HJP1121** [comment]
Sorry for me being an idiot, i thought of using opengl to reduce ram usage

**Comment by gomker** [comment]
No problem. This was rooted in  KSP/Unity changes a few releases ago.
