### ISSUE TITLE
Modular missiles are not usable without Guard mode

### ISSUE THREAD

**Issue by jrodrigv** [PapaJoesSoup/BDArmory#377]
##### ISSUE TYPE
 - Bug Report   (Something is broken)
##### KSP and BDA Version
KSP 1.3.1 & BDA dev

##### SUMMARY
A modular missile can't be fired manually. (eg. locking on the radar and then firing manually)

##### STEPS TO REPRODUCE
Build an AAM modular missile and try to lock a target and fire the missile. It would fly straight-

**Comment by Memeconnoisuer** [comment]
Laser Guided AGM's also suffer from this issue 

Not sure about other guidance types

**Comment by MrSteve10424** [comment]
You see, I have the exact same issue with it, can you check if the electric charge on your missile is disabled? This is what happened to me.
