### ISSUE TITLE
BUG NEEDS TO BE FIXED

### ISSUE THREAD

**Issue by mgreen442** [PapaJoesSoup/BDArmory#4]
i just got a new computer and it is a window10 gaming pc/ desktop and i installed bdarmory and when i start with a ship of and kind on the launch pad and o rrunway the camara goes into orbit. it says year 599 day 59 min 59 and sec 59 i cant do anything and i had to uninstall bd armory. i have tried doing all 3 links i could find and nothing worked, what do i do? this has happened before (and now) in the first BDarmory (BDarmory) and continues to BDarmory continued.

Why

**Comment by Nerfclasher** [comment]
can you please give me logs and reproducing steps

**Comment by mgreen442** [comment]
?????

**Comment by Nerfclasher** [comment]
I need logs if I want to help you

**Comment by mgreen442** [comment]
when i launch a ship the camara goes into orbit. it says year 599 day 59 min 59 and sec 59 i cant do anything and i had to uninstall BDarmory continued. that also happened on my old computer when i had normal BDarmory (BDarmory). i installed it from 3 websites:
Space Dock,
Cursesforge and
GitHub.

**Comment by mgreen442** [comment]
i have all the parts and textures but cant launch any ship with any parts.

i also play in 1.1.3

**Comment by mgreen442** [comment]
it can be a rocket or a plane

**Comment by mgreen442** [comment]
just does not work

**Comment by mgreen442** [comment]
it could even be a car

**Comment by mgreen442** [comment]
i have no other mods

**Comment by Nerfclasher** [comment]
There is a prerelease you can try on GitHub

**Comment by mgreen442** [comment]
even without BDarmory parts

**Comment by mgreen442** [comment]
i think i tryed that too

**Comment by mgreen442** [comment]
yea i did

**Comment by mgreen442** [comment]
i will try. again talk to you later

**Comment by mgreen442** [comment]
i already installed it before so what now

**Comment by mgreen442** [comment]
i tryed before with it

**Comment by mgreen442** [comment]
i was just in the ksp gamedata folder

**Comment by mgreen442** [comment]
i already hqad it in there

**Comment by mgreen442** [comment]
had typo

**Comment by mgreen442** [comment]
do i have to do more than just put it in the gamedata folder??????

**Comment by mgreen442** [comment]
u there?

**Comment by Nerfclasher** [comment]
did you put bdarmory into gamedata

**Comment by PapaJoesSoup** [comment]
Checking in.  Did you solve your problem or does it remain?

**Comment by PapaJoesSoup** [comment]
Closing issue due to lack of response from original author.
