### ISSUE TITLE
Autopilot Improvements

### ISSUE THREAD

**Issue by XOC2008** [PapaJoesSoup/BDArmory#403]
ISSUE TYPE

 - Enhancement  (Expand on existing features)

SUMMARY

- [x] Add a higher altitude limit (12-15k) suitable for spy planes. (PAI)

- [x] Add an Orbit slider to adjust for port or starboard orbits over positions. (suitable for air support like AC-130 types) (PAI)

- [x] Add a higher maximum speed to the max speed slider. (PAI)

- [ ] More Teams, with Friend or Foe options. (Then team A and team B could have different formations and be assigned different tasks while not attacking one another, with extra teams C and upward with the same sort of options.) (Weapon Manager)

- [ ] Add an "Orbit at Position" button. (WingCommander)

**Comment by XOC2008** [comment]
Added another improvement I think we need, higher max speed on the slider in the AI pilot.

**Comment by Gedas-S** [comment]
1, 3 and the additional comment were added via the tuning unclamper button (visible with advanced tweakables on) #534 
2 we'll see about, not sure how the craft orbit currently
4 the request as written is already present in #359 however as I understand it you'd actually want the ability to easily group vessels in the wing commander :) I'll see how hard that would be to do. :)
5 is exactly what the "fly to position" button already does

**Comment by XOC2008** [comment]
5. Yes and no. Ideally I'd want the position marker to be the center point for the orbit, instead it serves as the initial point of the turn. This would work in conjunction with having the ability for a port or starboard orbit selection.

**Comment by Gedas-S** [comment]
Fair enough. 2 and 5 are related then. :) I'll see if this is an easy fix, or will require an additional orbiting system. :)

**Comment by Gedas-S** [comment]
Added 2 in #570 
For 5, I checked, based on the code, a fly to command will serve as the target point, yes, but after the target is reached, it should become the centre of the orbit. I'll have to test if that is actually how it works though, before saying that 100% :)

**Comment by Gedas-S** [comment]
Should be fully implemented in 1.3.0.
