### ISSUE TITLE
Standby Mode is being bypassed if there is an active radar on one of the teams

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#406]
ISSUE TYPE
 - Bug Report   (Something is broken)

KSP and BDA Version

KSP v1.3.1
KSP v1.3.0 
BDAc v1.1.0.0 Public Beta
BDAc v1.0.0.0 

OS / ENVIRONMENT
Windows 10

SUMMARY
Standby Mode is being bypassed if there is an active radar on one of the teams. 
In addition to this, if Debug Labels and Debug Lines are turned on in BDAc settings then the same thing will occur

STEPS TO REPRODUCE
- Place aircraft without radar at the island airport on standby mode and visual range set to default (10000) with the AI Pilot and Weapon Manager activated
- Place radar dish (Jernas Turret or other radar system) on the same team as the aircraft without radar at the island airstrip without it's radar engaged
- Launch aircraft from KSC that does not have a radar as well as set to be on the opposite team and use Wing Commander to tell the craft to attack the island airport (See Video Linked Below)
- Switch to the radar system at the island airport and aim your camera at the aircraft on standby
- Turn on the radar dish and the craft on standby will immediately start to take off (second clip in video) 

OBSERVATIONS
- Occurs whether guns are present or not
- Standby Mode works as intended unless there is an active radar in play
- Standby Mode is also bypassed if you turn on Debug Lines and Debug Labels then switch your craft to the opposing team (Last clip in video)

I have encountered this bug as far back as KSP v1.2.2 (BDAc, v0.2.0.0 ????) but it was not present in KSP v1.1.3 using BDAc v0.11.1.2 through v0.11.6 as evidenced by the videos contained in the following threads
- https://forum.kerbalspaceprogram.com/index.php?/topic/148410-its-waldos-island-a-bdac-development-group-challenge-ksp-v113/&do=findComment&comment=2769908
- https://forum.kerbalspaceprogram.com/index.php?/topic/152608-bdac-challenges-youre-surrounded/&do=findComment&comment=2864716

Logs and Save Files
These are from the same session as when the second and third clip in the video below were taken
- https://www.dropbox.com/s/rplc15vp30cd3a1/BDAc%20Standby%20Mode%20Issue.zip?dl=0

VIDEO LINK
- https://youtu.be/F0tXcHb0Ta8

**Comment by XOC2008** [comment]
I can confirm this happens to me too. While I cannot provide logs as I am having some other issues related to the game, I can tell you that Standby was interrupted with debug lines and labels.

With debug off, I had three craft on the island on standby, radars inactive. I launched from KSP and they remained inactive until I switched back to them and turned on one radar. All three launched. I repeated this with gun drones as well as fully loaded planes.

**Comment by TheDogKSP** [comment]
Will look into it...

**Comment by TheDogKSP** [comment]
OK, findings so far:
- it is not even related to radar, I can produce the problem even with pure visual range
- problem is the "target database" per team: the active vessel registers itself in the target database as a valid target for the opposing team.
- the pilot AI then queries the target database if there is anything, and takes off if yes (which is always the case when you are piloting the active vessel on the other team).

What is lacking here is a "can actually be detected" check inside the pilot AI. I will patch sth in...
