### ISSUE TITLE
Trigger arming not used 

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#41]
Looking through code I see that `isArmed` is actually not used anywhere. Perhaps a feature that was yet to be implemented such as a "safety" to make sure a weapon does not fire?

**Comment by MuricanJeb** [comment]
Well in old versions of KSP like 0.90 instead of that trigger thing, it was Sytem Armed to activate missles.

**Comment by gomker** [comment]
Trigger arming is used with Mouse fire
