### ISSUE TITLE
Toggle button to hide BDAc windows

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#410]
##### ISSUE TYPE
 - Feature Idea (Something new you want to see)

##### KSP and BDA Version
All future versions

##### OS / ENVIRONMENT
Any

##### SUMMARY
Add a toggle button to enable a user to minimize any of the BDAc GUI windows that inevitably pop up and get in the way ... Something like Windows Blinds or like the current MechJeb has, a drop down or side slide deal with user controllable settings such as having the windows appear in a minimized state instead of blocking your screen

Possibly add resizable windows as well, if possible

Many times I have had the radar and RWR pop up while while trying to do something with the Wing Commander and the screen gets cluttered with windows which has lead to my attack force going out in a blaze of glory

**Comment by SpannerMonkey** [comment]
I strongly support any move to reduce the size of the BDA GUI on screen elements , it's been mentioned many times before, and still the gui devours more than 40% of onscreen space , leaving very little room for craft interaction.  
[https://i.imgur.com/PaXziyf.png](url)

**Comment by TheDogKSP** [comment]
That is a <full-HD resolution on your display, is it?
I am playing with 1920x1024 (full HD), and while the gui does take quite some space, I find it mostly ok.
If we could have dynamic gui scaling, that'd be awesome, but I dont know whether the KSP gui framework supports that, or if we'd have to roll our own...

**Comment by DoctorDavinci** [comment]
Probably have to roll our own .... I'm thinking something like the MJ system of a drop down menu in the flight scene would be the way to go

Have each of the windows appear anchored to the edge of the screen in the flight scene with the ability to click on the title bar in said windows to have them slide into the edge of the screen along with the ability to reposition them

Perhaps also have 2 display sizes ... normal like they are now and a smaller half scale size

**Comment by PapaJoesSoup** [comment]
Changes implemented in v1.2.1.1.  minor bits added in v1.2.1.2
