### ISSUE TITLE
Ability to change hitpoints value on parts?

### ISSUE THREAD

**Issue by MuricanJeb** [PapaJoesSoup/BDArmory#431]
##### ISSUE TYPE
 - Enhancement  (Expand on existing features)

##### SUMMARY
It's kinda weird how we can't change the hitpoint values on parts, since some might want to make the parts a bit weaker (think wood and canvas WWI biplanes)

**Comment by gomker** [comment]
You can via MM patches. The default hit points are calculated on surface area  and density of the part. This formula works OK for most parts but custom parts from mod makers will require some balance.

Documentation here : https://github.com/PapaJoesSoup/BDArmory/wiki/1.2.1-Hitpoints-&-Armor

You can also see some manual adjustment that needed to be made here:

https://github.com/PapaJoesSoup/BDArmory/blob/dev/BDArmory/Distribution/GameData/BDArmory/MMPatches/000000_HitpointModule_PartFixes.cfg

**Comment by MuricanJeb** [comment]
I know, but what if you had the same part, and one was on a WWII plane and the other was on a WWI plane? Or maybe you want to change the hitpoints without having to load and reload the game all the time.

I think I'm getting pretty annoying with you guys now that I'm requesting so many stuff. If you want me to close the issue then please notify me.

**Comment by gomker** [comment]
Lol - you're fine , we need other perspectives on how things could be used. #429  is related, I think I may combine these two items for a feature set like a window to control the values. Or a setting that switches it up to allow editing. 

Here is the thing, it probably will be All or nothing, meaning if you switch to "manual" mode you will need to define the Hitpoints for all parts on your vessel, set with a low or manually set default value.

**Comment by MuricanJeb** [comment]
Okay, thanks for considering and thank you for your patience with me 😄

**Comment by gomker** [comment]
I think Doc has some extra tools for tweaking HP values as well
