### ISSUE TITLE
Hitpoint values

### ISSUE THREAD

**Issue by SuicidalInsanity** [PapaJoesSoup/BDArmory#432]
ISSUE TYPE

    Enhancement (Expand on existing features)

SUMMARY

Increased Hitpoint calc granularity; hitpoint values bottom out at 500 and increase by multiples thereof

Al present it looks like part HP pools are divisible by 500 for things like ProcWings/messing about with FAR wingstrength - would it be possible to have a lower multiplier value? I.e. scaling a procedural part/wing, or scaling Wing mass with FAR, having HP increase more smoothly, say by 100/250 point increases, rather than 500 point jumps, Additionally, once mass and/or size drops beyond a certain point, HP values will not go below 500 points, mainly an issue for things like canards/small fins/greebly bits.

**Comment by MuricanJeb** [comment]
I think once #431 (my issue) is solved then it should fix this one too. If you can change a value with a slider, then stuff that uses tweakscale and possibly things like procedural parts or B9 wings would be automatically compatible with the hit point changes.

**Comment by jrodrigv** [comment]
This is going to be fixed on the next release. Hitpoints resolution reduced to 100 hp.
