### ISSUE TITLE
Issues with Penetration and Distance

### ISSUE THREAD

**Issue by sjpc302** [PapaJoesSoup/BDArmory#434]
Before we get started:
Fully updated ksp, running BDA public beta v1.1.0, using updated version with fixed bullet config, clean installation and save, no other mods besides module manager and physics range extender.

So, I have noticed when trying to test the new armor system that penetration seems to behave quite weirdly for me. At decent ranges of over 20 meters or so, penetration seems to work as normal, though it is hard to tell if this is because it works as expected or because it doesn't penetrate. At close range, the Abrams turret, the only one I have tested thus far, seems to have infinite penetration.

I created a test, with a testing platform with several armor plates in a row. The first 2 have thickness of 100 mm, and the following couple plates have thickness of 500 mm.  When firing at this setup at close range, the shell goes through all plates. At longer ranges, it looks like it explodes on the first plate. Based on the logs, which I will provide, the shells have "Armor penetration = 351.1632", so they should go through the first two 100mm plates and terminate on the third 500mm plate.

I have attatched
 KSP.log and output_log.txt, and I'll link a video that I took of the test that corresponds with those logs.

https://youtu.be/Scz5GEfDsH0

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/1587969/KSP.log)
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1587970/output_log.txt)

**Comment by sjpc302** [comment]
Issues seem to also exist with the .50 cal, I'll test further and provide logs/video soon.

**Comment by gomker** [comment]
Try testing with the Howitzer as well, what you are seeing is the explosive detonation logic. If a shell is explosive and has penetrated it will explode shortly after penetration. If an explosive shell is stopped it will explode on impact.  In this case the explosive detonation triggered due to penetration

	[LOG 16:55:40.192] [BDArmory]: Armor penetration = 351.1632 | Thickness = 100.0009
	[LOG 16:55:40.193] [BDArmory]: Armor Removed : 3.97
	[LOG 16:55:40.196] [BDArmory]: mass: 19.6 caliber: 120 multiplier: 19.6 velocity: 1717.322 penetrationfactor: 3.511601
	[LOG 16:55:40.197] [BDArmory]: Ballistic Hitpoints Applied : 3666.95
	[LOG 16:55:40.197] [BDArmory]: Detonation Triggered | penetration: True penTick: 1 airDet: False
	[LOG 16:55:40.200] [BDArmory]: Enqueueing Blast Event

The Howitzers shells are non-explosive and you will see more of the penetration effects

Also each penetration causes a severe drop in velocity. Also in order not to have a bunch of slow moving game objects lagging around the bullets are destroyed when they drop below 100 m/s

**Comment by sjpc302** [comment]
I thought something like that might be the case in regards to the penetration at normal range, though the main issue to me was the infinite penetration at close range. If you have a look at that second video with the .50 cal, you will see it flying through 500mm armor plate. This might have something to do with code to try and make sure a weapon doesn't shoot itself, or it might be a bug.

**Comment by gomker** [comment]
Yes, I think what you are seeing there is the initial velocity and position being set forward of the barrel too much. We have seen some reports of that as well, bullet is actually jumping ahead in the frame

**Comment by sjpc302** [comment]
Huh, ok. Shouldn't cause huge issues since combat shouldn't really be happening that close anyway. Thanks for the help, and best of luck!

**Comment by gomker** [comment]
No problem, we are trying to fix that jumping issue at close range, messes up the Kerbal FPS mods

**Comment by sjpc302** [comment]
You know, now that I have been messing around with it it appears that explosive shells that penetrate really do explode on the outside. I didn't really test for this as I figured it wasn't actually the case, but now that I've made actual tanks and pitted them against each-other I have never seen an explosive shell from the abrams hurt the components on the inside of the tank unless the outer armor is destroyed. I even checked the logs once or twice and it said it penetrated. I have no issues with the howitzer though, works as expected, and can destroy components after going through armor without destroying it.

**Comment by sjpc302** [comment]
Did a little test.

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/1590324/KSP.log)

https://youtu.be/C4z2dABcguA

**Comment by gomker** [comment]
Can't really see from that angle, also the movement forward is not very much. The following section of code is where I try and move the bullet forward a bit on explosion.

https://github.com/PapaJoesSoup/BDArmory/blob/dev/BDArmory/Bullets/PooledBullet.cs#L345-L358

So two things
1) the bullet pretty much destroyed the panel as well, so you will see that immediately
2) moving the bullet in each frame tick is tricky - at the velocities we are calculating its hard to get the precision 

Try a target with stacked plates, say 3 deep and you can see the explosive effect after a bit more clearly.

**Comment by gomker** [comment]
Related to PR #448
