### ISSUE TITLE
Guns shouldn't target the root part.

### ISSUE THREAD

**Issue by starshipkerbal** [PapaJoesSoup/BDArmory#441]
Imagine it: you've built your badass space warship. Giant guns, multiple layers of heavy armor, it looks awesome!

But, when you take it into battle, the enemy weapons instantly lock onto the root part of your glorious space steed. Perhaps that root part is your bridge, or your main fuselage, or a tiny little girder buried beneath all the guts of the behemoth. Locking onto your root part, the enemy ship focuses fire and tears a precise hole through your hull and cores you like an apple!

In my opinion, the solution to this should be that each weapon will target a random part instead of the root; meaning that every gun will shoot a different part of the target, scattering the fire and prolonging battles so that some enjoyment can be gained from them. Not to say that focused fire should be impossible, the player should have the ability to mark a point on the target vessel for the guns to focus on -- say, the engines, or a command pod.

##### ISSUE TYPE

 - Feature Idea (Something new you want to see)

**Comment by XOC2008** [comment]
From my experience they don't target the root part so much as the weapon manager. If the WM is the root part (like a WM-enabled cockpit) then they target that. Otherwise they fire guns at wherever the WM happens to be buried in a vessel.

**Comment by gomker** [comment]
It depends , some calls use vessel COM some pick up the WM as the target, it needs to be made consistent. 
Also this is covered in #22 in great detail
