### ISSUE TITLE
Weapon Manager not in parts

### ISSUE THREAD

**Issue by Legoclub22** [PapaJoesSoup/BDArmory#447]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE
 - Support

##### KSP and BDA Version

KSP is 1.3.1.1891

BDA is 1.1.0.23471_12292017

Windows 7 OS

##### SUMMARY
The Weapon Manager part is nowhere to be found. I've scoured through all the parts, re-installed it, installed the latest version I could find, nothing works. It's still not there.

##### STEPS TO REPRODUCE
Installed the latest version of BDArmory, enter downloaded zip file, GameData, take the BD Armory folder out of the downloaded GameData, put it in the KSP GameData. Install BDArmoryExpanded, repeat above, go to downloaded SourceCode folder, take NextStarIndustries from downloaded SourceCode folder and put it in KSP SourceCode folder. Launch game, go to VAB, no Weapon Manager to put on my ship.

##### Log Files

I can't seem to figure out how to put up log files.

**Comment by DoctorDavinci** [comment]
Remove NSI and see if the problem persists

I suspect that NSI is where your problem is ... nothing we can do about that as it is not a mod that we have control over

**Comment by Legoclub22** [comment]
That's odd, I downloaded it along with the BDArmory Extended mod. I'll try removing it, and respond with results.

**Comment by DoctorDavinci** [comment]
NextStarIndustries: BD Armory Weapons Extension is not our mod ... The creator of that mod has named it so as to imply compatibility with BD Armory 

Only download BD Armory from reputable sources such as the releases section of this repository ... NextStarIndustries has no affiliation with BD Armory Continued nor the BDAc team

**Comment by XOC2008** [comment]
Also there's no reason to do ANYTHING with the contents of Source Code folders unless you plan on messing with the code. So don't even install those.

**Comment by gomker** [comment]
No response in some time  - closing issue
