### ISSUE TITLE
GuArD moDe AIn'T WoRkinG fAM

### ISSUE THREAD

**Issue by PleASeHElpMEandFiXMYpROblEms** [PapaJoesSoup/BDArmory#456]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

 - Support 	    ( Need help getting something to work)
GuaRd ModE dOEsN'T let targets Be ChoSen TO AttACk.
 - Bug Report   (Something is broken)
THe GuaRD MOde ain't working, IT KEePs NoT lEtTing aNYthING TarGet/ AttACk each other.
 - Feature Idea (Something new you want to see)
Idk
 - Enhancement  (Expand on existing features)
hELp

##### KSP and BDA Version

```

```

##### SUMMARY

PleasE hElp
##### STEPS TO REPRODUCE
legit just use guard mode

aaaaa

**Comment by MuricanJeb** [comment]
How about you type this out properly first?

**Comment by XOC2008** [comment]
Type this out properly. Make sure you have radar. Make sure you have visual detection set. Make sure you have any number of things that can't be determined because the amount of information you're giving is insufficient. Guard mode works for me.
