### ISSUE TITLE
Torpedo thrust only under water

### ISSUE THREAD

**Issue by Acea-K** [PapaJoesSoup/BDArmory#459]
Is it possible to give missiles with "torpedo = true" zero cruise phase thrust when they are not under water?
Most torpedoes would have a very large thrust to resist drag under water, which may cause them to behave crazily in the air like this.
![image](https://user-images.githubusercontent.com/6168892/36083733-f47d1b10-0ff0-11e8-8a50-a6637bed8357.png)

**Comment by gomker** [comment]
Chatting with Spanner I believe he has mentioned a few tweaks to fix this and its an older issue.
If its still something you want to address comment and I will re-open
