### ISSUE TITLE
Stabilistaion of manually aimed turrets 

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/BDArmory#46]
How difficult would it be for the stabilisation that the current BD camera system uses to be applied to manually aimed turrets?
I know the AI uses it or something similar as  AI shots from a moving ship always land within the allowed dispersion radius, so not prone to the pitching and rolling of the vessel as manually aimed shots are.
 When manually aiming a turret form a moving ship it is very difficult  to keep the reticle over the target as the movement of the ship is shared by the reticle, So manually aimed shots have to be timed to coincide with the roll of the ship on which the turret is mounted
SO stabilisation for manually aimed turrets, possible or not?

**Comment by jrodrigv** [comment]
@SpannerMonkey Is this still relevant? I think Gedas has done a lot of improvements about this.

**Comment by SpannerMonkey** [comment]
situation much improved since posting this, shells go where they are supposed to these days, cloasing
