### ISSUE TITLE
RWR not appearing when selected

### ISSUE THREAD

**Issue by Catahism** [PapaJoesSoup/BDArmory#461]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version
KSP v.1.3.1804

BDA v0.2.2.0 (may be wrong, I got this number from the .VERSION file)

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY
RWR Display does not appear when chosen from the module list. I can hear the alert if a missile is fired on me but the display itself is not there.

##### STEPS TO REPRODUCE
Just click on the RWR. Although I know I am a minority with this issue, so most will not be able to reproduce it.

##### Log Files
(Ask me to include this in a separate post if it is needed)

**Comment by DoctorDavinci** [comment]
Related to https://github.com/PapaJoesSoup/BDArmory/issues/411

**Comment by PapaJoesSoup** [comment]
Fixed with changes made to support #411.
