### ISSUE TITLE
300m/s afterburner threshold

### ISSUE THREAD

**Issue by Box-of-Dust** [PapaJoesSoup/BDArmory#466]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Bug Report   (Something is broken)
 - Enhancement  (Expand on existing features)

I mean it's kinda all both. Not really a bug... but it's an odd bit in the programming.

##### KSP and BDA Version

KSP 1.3.1

BDA 1.0.0

##### OS / ENVIRONMENT

Windows 10

##### SUMMARY
AI Pilot behavior is such that 300m/s is an automatic 'turn on the afterburners' threshold. Bit annoying that a plane has enough thrust to supercruise, but it'll turn on the burners anyways.

Setting max speed of 300m/s, the AI pilot will fly that plane as fast as it can up to 300m/s without using afterburners (unless max speed cannot be attained without afterburners, which is reasonable behavior). Setting max speed of 301m/s, it'll turn on afterburners and then put throttle down to whatever low value it needs to keep a limit of 301m/s, even if a plane has enough dry thrust to maintain higher speeds (e.g., 320m/s).

Behavior was observed during AI Dogfight Competitions, when aircraft are approaching each other from starting positions.

**Comment by Gedas-S** [comment]
I can confirm this. We'll see if taking this logic out doesn't break anything. Thanks for the report!

Last part of line 160 in BDAirspeedControl:
`if (allowAfterburner && (accel < requestAccel*0.2f || targetSpeed > 300))`

**Comment by gomker** [comment]
Closing as this will be in merge branch
