### ISSUE TITLE
BUG  Encoding Format Error BDAmmo_Universal.cfg

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/BDArmory#470]
##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version

All recent dev versions 

##### OS / ENVIRONMENT
ALL

##### SUMMARY
The encoding format for the above resource cfg is incorrect, supplied it is UTF8 when KSP cfgs are  usually ANSI.
This causes certain characters to be misread by the game and leads to various turrets malfunctioning due to missing resources 

##### STEPS TO REPRODUCE
Browse any recent BDA log and search for 7.92x57mmMauser, Note absence. 
Open BDA bullet resource definition , scroll down to 7.92x57mmMauser,  Note using notepad++.   change file encoding to ANSI .
Note that  7.92x57mmMauser now reads  name = 7.92Ã—57mmMauser.   This strangely named new ammo is the one the game is loading as evidenced by logs, not the correct 7.92x57mmMauser

**Comment by XOC2008** [comment]
Can confirm this is also happening to me and seems to be happening with at least one forum user. I even corrected the badly encoded resource manually and the problem persists after saving the cfg and game restart.

**Comment by gomker** [comment]
my encoding was set to update all files to UTF 8 in notepad ++ changed to ANSI

**Comment by gomker** [comment]
in next branch for testing
