### ISSUE TITLE
Autocalculated HP does not remain the same when launching vessel

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#477]
##### ISSUE TYPE

Bug

##### KSP and BDA Version

BDAc v1.1

##### OS / ENVIRONMENT

All

##### SUMMARY

I have found that the Mk3 liquid fuel tank is autocalculated to have 3000 HP but only has 2000 HP when launched

##### STEPS TO REPRODUCE

Enter SPH
Select an Mk3 Fuselage
Stick as many as you want together
Check HP ... Each fuselage will have 3000 HP
Launch vessel and check HP ... every Mk3 fuel tank will now have 2000 HP

Untested against other autocalculated parts

**Comment by jrodrigv** [comment]
I have fixed this with a complete overhaul in the Dev brach. I'd like to
have some feedback about it.
