### ISSUE TITLE
PreRelease IR/ Camera view screen not displaying correctly

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/BDArmory#48]
PreRelease IR/ Camera view screen not displaying correctly
Reproduce fit bd targeting camera to any vessel, Launch, select camera from weapon manager modules section and view , see image below.
Display is failing in both modes, normal and night vision, possible related to #47 emissive issues as I believe the display module uses emissives
http://i.imgur.com/cYZWJM2.png

**Comment by KerbalPete** [comment]
I can second this issue. Should be high priority.

**Comment by GoldVinyl** [comment]
I can also confirm this issue.

**Comment by gomker** [comment]
Corrected in  v0.11.1.5
