### ISSUE TITLE
Targeting cameras appears in weapon manager module list twice

### ISSUE THREAD

**Issue by Gedas-S** [PapaJoesSoup/BDArmory#481]
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version
KSP 1.4.1 64-bit
BDA dev version

##### OS / ENVIRONMENT
Win10 64 bit

##### SUMMARY
Targeting cameras appear in weapon manager module list twice when they come after the WM in the part hierarchy.

This is because WM finds all cameras, and then the camera adds itself to the list, resulting in two entries.

##### STEPS TO REPRODUCE
Take cockpit, place a WM on it, place a targeting camera, launch. Targeting camera will appear twice in the module list. This is the same camera. Turning one on will show both as turned on.

##### Log Files
N/A
![screenshot249](https://user-images.githubusercontent.com/8385798/37737692-4134e5d0-2d5d-11e8-911c-f42d8bb3dfae.png)

**Comment by Gedas-S** [comment]
Ok, I cannot replicate it that reliably, seems WM does not always call RefreshTargetingModules on start, nvm for now. Still probably there should be only one way the modules are added.
https://github.com/PapaJoesSoup/BDArmory/blob/c4440579cf4d0790174f8a83ca4366b06f052931/BDArmory/MissileFire.cs#L2873

**Comment by SpannerMonkey** [comment]
OS win7 BDA dev
Same symptoms , occasionally shows doubles of radar units also.  Not easily replicated .  Of note in my case seems to be mainly older,  frequently modified test craft that present the issue

**Comment by PapaJoesSoup** [comment]
If you added refresh on start how does that affect scope.  meaning is the module start event call occurring to keep the list fresh enough to account for changes to the list?  I'm not close to the code, but I know start occurs typically once per module per scene for each module...

**Comment by Gedas-S** [comment]
A refresh occurs on:
- Part death: https://github.com/PapaJoesSoup/BDArmory/blob/8fe6fefcf4145b94799ca156096bc9c5fe57e3cc/BDArmory/MissileFire.cs#L768
- Vessel create: https://github.com/PapaJoesSoup/BDArmory/blob/8fe6fefcf4145b94799ca156096bc9c5fe57e3cc/BDArmory/MissileFire.cs#L774
- Part joint break: https://github.com/PapaJoesSoup/BDArmory/blob/8fe6fefcf4145b94799ca156096bc9c5fe57e3cc/BDArmory/MissileFire.cs#L786

Start was a special case, where a refresh did not occur, but instead each module would find the weapon manager, and add itself to the list. I'm not touching all the other events, just making Start use the same method.

**Comment by PapaJoesSoup** [comment]
Ok.  that covers my concern.  merging.

**Comment by Gedas-S** [comment]
I am not sure if it covers all the cases (e.g. vessel docking), but the other modules adding themselves on their own Start events does not really change that. I cannot really think of a scenario where the Start methods would be called at different points in time for different parts of same vessel. :)
