### ISSUE TITLE
No suitably configured/efficient radar for decent ground detection in BDA 

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/BDArmory#484]
##### ISSUE TYPE
 - Enhancement

##### KSP and BDA Version
131 on wards
BDA under the radar and on 

##### OS / ENVIRONMENT
ALL

##### SUMMARY
NO suitable radar for ground use currently packaged within BDA,  without exception all are much better or completely oriented toward airborne/aircraft detection 

Suggestion
Either via module manager and a texture tweak or new parts, create two suitable radar for use in ground detection. One for use by aircraft and one for use by landed vehicles    

WHY?
Without a valid example of ground detecting radar, BDA falls down in it's desire to provide good examples of "how to"  for future mod makers/maintainers

##### STEPS TO REPRODUCE
Attempt as average user to lock normal sized kerb vehicles with any of the BDA supplied radar 

##### Log Files
Non required

**Comment by Edward-Snowcone** [comment]
If you are talking about detecting vehicles on the ground from the air, or even from the ground, this most likely isn't in the mod because it's not very possible in real life. Radar gets confused and has extreme trouble differentiating trees and buildings and such from whatever you are trying to target.

**Comment by SpannerMonkey** [comment]
RE the above.  BDAc has allowed for many variations in radar setup.  I already have specialist ground and air search radar in my mods. I think it only fair that those players who are for some reason restricted to minimal mods to not have access to a similar part 

All it takes is a slight tweak to the radar cfg, although it can be done by simply changing 1 number , the effect  can be refined by adjusting the detection and lock curve to max out detection at a particular range, and as it is a float curve it can be tuned to finite levels

With a properly configured BDA radar it is possible to detect and lock a tank sized target from LKO (several proofs now on you tube, and the BDA team is well aware of our antics, as the  unofficial BDAc Skunkworks)

**Comment by XOC2008** [comment]
As to Edward's argument that it's not very possible: https://en.wikipedia.org/wiki/Airborne_ground_surveillance. As well as ASMs which often use active or passive radar homing.

**Comment by XOC2008** [comment]
More: "The AN/APY-7 radar can operate in wide area surveillance, ground moving target indicator (GMTI), fixed target indicator (FTI) target classification, and synthetic aperture radar (SAR) modes.

To pick up moving targets, the Doppler radar looks at the Doppler frequency shift of the returned signal. It can look from a long range, which the military refers to as a high standoff capability. The antenna can be tilted to either side of the aircraft for a 120-degree field of view covering nearly 50,000 km² (19,305 mile²) and can simultaneously track 600 targets at more than 250 km (152 miles).[1] The GMTI modes cannot pick up objects that are too small, insufficiently dense, or stationary. Data processing allows the APY-7 to differentiate between armored vehicles (tracked tanks) and trucks, allowing targeting personnel to better select the appropriate ordnance for various targets.

The system's SAR modes can produce images of stationary objects. Objects with many angles (for example, the interior of a pick-up bed) will give a much better radar signature, or specular return. In addition to being able to detect, locate and track large numbers of ground vehicles, the radar has a limited capability to detect helicopters, rotating antennas and low, slow-moving fixed-wing aircraft."

For radar to be able to know the difference between armored and non-armored vehicles, that seems quite opposite of being confused.

**Comment by Edward-Snowcone** [comment]
Oh huh I never knew that was possible. Excuse my first comment then.

**Comment by gomker** [comment]
Ground radars are in current release
