### ISSUE TITLE
PreRelease Weapons freezing when firing

### ISSUE THREAD

**Issue by Wraith977** [PapaJoesSoup/BDArmory#49]
Weapons freeze in position during firing and can no longer be aimed or fired, weapons can still be switched and different weapons can still fire properly although frozen weapons will not become aimable again, the laser turret will also appear to still be firing its laser.

Log shows spamming this output:

"
NullReferenceException: Object reference not set to an instance of an object
  at BahaTurret.ModuleWeapon.InitHeatGauge () [0x00000] in <filename unknown>:0 
  at BahaTurret.ModuleWeapon.UpdateHeatMeter () [0x00000] in <filename unknown>:0 
  at BahaTurret.ModuleWeapon.FixedUpdate () [0x00000] in <filename unknown>:0 

(Filename:  Line: -1)
"

Reproduction steps:
1: Spawn craft with any turret, a missile and weapon manager.
2: Fire missile.
3: Switch to missile and switch back.
4: Fire weapons in bursts at nearby KSC.
5: Repeat step 4 until weapons freeze.

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/475581/output_log.txt)

EDIT: This seems to only occur after switching to another craft and switching back.

**Comment by SpannerMonkey** [comment]
I can confirm this. It's also happening when the AI is using purely turrets. It fires one shot and stops firing , while the weapon remains targeted and uncontrollable .  43 weapons systems tested form various mods, and all display the same behavior Manual firing seems unaffected except for the exclusions mentioned by Wraith

**Comment by jrodrigv** [comment]
I think I have fixed this with 4c238f4.

**Comment by jrodrigv** [comment]
I need to work on this a bit more. Turrets are not stuck now but I still getting the null reference exception

**Comment by jrodrigv** [comment]
Fixed with bf1aa5

**Comment by gomker** [comment]
Tested  - no freezing or null reference exceptions against 1.2.0.1569 
Will wait for @SpannerMonkey  to confirm for close

**Comment by gomker** [comment]
After re-reading the OP I did some AI testing - I experienced the same described behavior with the laser locking up and turrets locking up after doing an AI battle.

**Comment by gomker** [comment]
Release  v0.11.1.5  Does not exhibit this behavior
