### ISSUE TITLE
Order of Firing

### ISSUE THREAD

**Issue by byongtube** [PapaJoesSoup/BDArmory#492]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Enhancement  (Expand on existing features)

##### KSP and BDA Version

```
BDA 1.1.0
KSP 1.3.1
```

##### OS / ENVIRONMENT
Windows 10 Pro

##### SUMMARY

Can you make it that we can set the order that the same type of missile will be fired?

**Comment by gomker** [comment]
Missile types are determined by "Smart" targeting functionality. The code will determine the most effective missile based on , targeting type (Ground, Air, Sea)  and engagement range. Those are controlled in the VAB where you can decide how "close" or "far" it is before firing
