### ISSUE TITLE
Armor Slider is adjustable in flight scene

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#493]
##### ISSUE TYPE
 - Bug Report  

##### KSP and BDA Version
BDAc v1.1 Final
BDAc Dev for KSP 1.4.x

##### OS / ENVIRONMENT
All

##### SUMMARY
Armor Slider is adjustable in flight scene

##### STEPS TO REPRODUCE
launch a craft then right click on a part ... the armor slider is adjustable

See video: https://www.youtube.com/watch?v=h5JhyJ4vssA

**Comment by PapaJoesSoup** [comment]
This should be closed.  I tested this in BDAc 1.2.1.3 and in 1.2.1.4  Slider works in Editor, not in flight.
