### ISSUE TITLE
Incorrect drag values

### ISSUE THREAD

**Issue by L0ck0n** [PapaJoesSoup/BDArmory#498]
I've noticed issues with drag on some parts. For example "Radar data receiver"  has drag similar to that of Mk2 or Mk1 fuselage, isn't that too much? Similar thing with "Weapon manager". It is very visible when these parts are attached to the plane (speed is greatly reduced, especially at low altitudes). 
IMO these lines in config files are incorrect (values should be muuuuch smaller):

maximum_drag
minimum_drag
angularDrag

 

Currnetly for "Radar data receiver" it looks like:

maximum_drag = 0.2
minimum_drag = 0.2
angularDrag = 2

 

Similar values are used in Mk1 fuselage config.

**Comment by jrodrigv** [comment]
I think this has been already tackle
