### ISSUE TITLE
Selected weapon message missing

### ISSUE THREAD

**Issue by Wraith977** [PapaJoesSoup/BDArmory#50]
Some time back when a weapon was switched to with the weapon manager a message would appear in the centre of the screen indicating which weapon was selected, this allowed easy tracking of which weapon was selected if action groups were used to switch between weapons. In both the 1.1.3 and 1.2 prerelease this message only shows when no weapons are selected, displaying "Selected Weapon: None".

Reproduction steps:
1: Spawn craft with any single weapon and weapon manager.
2: Select attached weapon, no message will display.
3: Select the 'none' option in the weapon manager, message "Selected Weapon: None" will display in the centre of the screen.

**Comment by DoctorDavinci** [comment]
Confirmed ... This occurs whether selecting manually with the weapon manager or by using action groups set up for previous weapon/next weapon

Tested on KSP Win x64 v1.2 pre-release - 01494

See video here: https://youtu.be/9ujDm51OUlk

**Comment by gomker** [comment]
Need to add this line to function

`selectionMessage.textInstance = null;`

https://github.com/PapaJoesSoup/BDArmory/blob/master/BahaTurret/MissileFire.cs#L847

Fixes null reference exception for PostScreenMessage()
