### ISSUE TITLE
KSP crashing on first initialization with new BDA

### ISSUE THREAD

**Issue by DatCrazyDelphox** [PapaJoesSoup/BDArmory#503]
- Bug Report   (Something is broken)

``` KSP 1.4.2

``` BDA 1.2

Windows 10 Pro Build 17134.1

##### SUMMARY
Since i've installed the new BDA, every first ksp initialization crashes when loading any save. after the crash, it just start up normally

##### STEPS TO REPRODUCE
<!--
listed above

-->
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/1950542/KSP.log)

**Comment by PapaJoesSoup** [comment]
I have reviewed the log.  This is a heavily modded install.  I suspect a mod interaction somewhere.  I do see a lot of errors being generated in part loading, but cannot be sure that these are the issue.  I noted that the crash seems to appear when you switch to the space center.  Did you load an existing save game?  If so, did you first remove existing bda parts from your existing vessels?  

I suggest you try a clean install with just BDA and PRE installed, to see if you still have the issue.  Also, you could try loading a new game when you start the existing install.

**Comment by DatCrazyDelphox** [comment]
@PapaJoesSoup look, it somehow worked...
I'll need to tweak some cfgs for everything to work smoothly for now.
BTW, thank you for the help. :)

**Comment by PapaJoesSoup** [comment]
Awesome.  you might want to share your story about solving this in the forum thread for others that may also have the same problem.  Closing issue.
