### ISSUE TITLE
Add .template files to aid new missile and part complete configuration 

### ISSUE THREAD

**Issue by DatCrazyDelphox** [PapaJoesSoup/BDArmory#504]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Feature Idea (Something new you want to see)
 

##### KSP and BDA Version

``` KSP 1.4.2

``` BDAc 1.2

##### OS / ENVIRONMENT
Any


##### SUMMARY
<!-- Explain the problem briefly -->
Hello again!
So, when I was editing the cfgs to fix those problems in issue #503, i was suffering to find all necessary things to implement on my Howler UCAV missiles to fix them. 
So y'all could implement some templates of every type of missile, radar, gun, etc. To make things easier for modders and beginners. 


##### STEPS TO REPRODUCE
<!--
For bugs, show exactly how to reproduce the problem, using a minimal test-case.
For new features, show how the feature would be used.
-->
This feature would be useful for easing things up when it comes to updating and creating weapons of any sorts from scratch. 
It will be like searching in a manual for how to build a GPS cruise missile in example.

**Comment by TheDogKSP** [comment]
Not exactly what you are asking for, but at least we do have some extensive documentation on parts and what config options you can set for them:
https://github.com/PapaJoesSoup/BDArmory/wiki/1.-Developer-Documentation
