### ISSUE TITLE
Module manager missing (Bullets pass through other ships)

### ISSUE THREAD

**Issue by The-Borg-Captain** [PapaJoesSoup/BDArmory#506]
##### ISSUE TYPE
 - Support

##### KSP and BDA Version

- KSP 1.4.2/1.4.3

- BDA 1.2.0

##### OS / ENVIRONMENT
Xubuntu / Xfce 4.12

##### SUMMARY

When firing at another aircraft, bullets pass through (bullets also bounce off the ground), not causing damage. I've also seen missiles detonate near aircraft in competition, with no affect. When flying craft and clicking on the BDA tab on the right, red text appears in the middle of the screen, stating that the Module manager is missing, and BDA may not work correctly. Where do I get this Module manger that's needed? 
I looked around for .dll files and found ones named BDArmory.Core.dll nad BDArmory.dll in .steam/steam/steamapps/common/Kerbal Space Program/GameData/BDArmory/Plugins/

##### STEPS TO REPRODUCE

Place two craft in front of each other and fire.

##### Log Files

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/1957188/KSP.log)

Was unable to find the Output.txt file in KSP_x64_Data, just see a folder called mono.

**Comment by SpannerMonkey** [comment]
https://ksp.sarbian.com/jenkins/job/ModuleManager/lastSuccessfulBuild/artifact/ModuleManager.3.0.6.dll

**Comment by The-Borg-Captain** [comment]
Thanks for the help
