### ISSUE TITLE
Feature Idea: MOAR MISSILES!!

### ISSUE THREAD

**Issue by RichTheWolf257** [PapaJoesSoup/BDArmory#508]
##### ISSUE TYPE

 - Feature Idea (Something new you want to see)

##### KSP and BDA Version

```
BDA 1.2.X
KSP 1.4.3
Making History 1.2
```

##### OS / ENVIRONMENT
Windows 10 home

##### SUMMARY
Since the BDA Add-ons and extentions that have them show no sign of updating any time soon, I'd really like to see more Air to Air missiles added to the core BDArmory mod.

Specific suggestions:
-US:

- AIM-120C "Cropped AMRAAM" (the one with shorter fins)
- AIM-123 ASRAAM
- AIM-7 Sparrow
- AIM-54 Phoenix

-Europe:

- Magic
- MICA
- Meteor
- Skyfash
- IRIS-T

-Russia:

- K-13 (AA-2 Atoll)
- R-40R (AA-6 Acrid, Largest AAM ever produced)
- R-40T
- R-23R / R-24R (AA-7 Apex)
- R-23T / R-24T
- R-33 / R-37 (AA-9 Amos / AA-X-13 Arrow, Soviet equivalent to AIM-54 Phoenix)
- R-27R (AA-10 Alamo)
- R-27T
- R-27ER
- R-27ET
- R-73 (AA-11 Archer)
- R-77 (AA-12 Adder, "Amraamski")
- R-77T
- R-77PD (Ramjet version of R-77)
- K-77M (New, Upgraded variant of the R-77)
- K-77ME (Ramjet version of K-77)

##### STEPS TO REPRODUCE
The new features would simply add more customizeability to BDA-equipped craft. Players could experiment, and mix and match missiles to see which combinations preform the best. For players participating in competitions such as Plane Fight Club or Fighter Jet Showdown, these options would give the most dedicated and serious of participants the opportunity to fine tune and optimize their aircraft further than beofre.

**Comment by RichTheWolf257** [comment]
If I had to pick just a few, I'd want the AIM-7, AIM-54, All 4 R-27 variants, R-73, both K-77 variants, and either the R-37, or both R-40 variants.

**Comment by jrodrigv** [comment]
Have you seen the SM parts packs?

**Comment by RichTheWolf257** [comment]
I have. They have not been updated for 1.4+ My suggestion still stands.

**Comment by RichTheWolf257** [comment]
I'll have a look later. If it works, I'll edit my list to include only missiles that are NOT provided by SM.

**Comment by RichTheWolf257** [comment]
As promised, I installed the entire SM mod suite, and edited the list in my original post to reflect what was already covered. I would still like to advocate adding the 10-11 missiles in my abridged list, or at very least the AIM-7 and AIM-54 for a more complete U.S. missile inventory.

**Comment by jrodrigv** [comment]
@RichTheWolf257 Do you know that you can build your own replicas using the Modular missile parts?

**Comment by RichTheWolf257** [comment]
Not very good ones.

**Comment by jrodrigv** [comment]
So as @XOC2008 mentioned. We are not going to add any more missiles to BDA

**Comment by RichTheWolf257** [comment]
...Kinda disappointed that my request was dismissed seemingly without much consideration at all, even after a LOT of fat-trimming, but I can live with it. Thanks for at least having a look.

**Comment by jrodrigv** [comment]
Don't get us wrong. We have discussed a lot about this during the last two years.

And this the vision of the team.

It is better to not create false expectations :)
