### ISSUE TITLE
Tracers are invisible, everything else works fine and seems to be bug free.

### ISSUE THREAD

**Issue by MuricanJeb** [PapaJoesSoup/BDArmory#509]
##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version

KSP 1.4.3

BDA 1.2

##### OS / ENVIRONMENT
PC

##### SUMMARY
Everything is fine actually. Guns do damage and their normal thing. It's just that the guns don't have tracers.

##### STEPS TO REPRODUCE
I don't really know, I guess just open KSP v1.4.3 and use BDA with it? I saw someone else with the issue too, so...
##### Log Files
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/1959233/KSP.log)

**Comment by DoctorDavinci** [comment]
Ecerpt taken from the forum thread:
'Do note that many turrets do not fire tracer constantly, the amount of tracer can be changed in cfg. We have found that large amounts of tracer being in the scene can cause very large performance drops in lower end machines . Lower settings for graphics can also reduce visible effects"

Link to post: https://forum.kerbalspaceprogram.com/index.php?/topic/155014-14x-bdarmory-continued-v12-4232018-vessel-mover-camera-tools-bdmk22-destruction-effects-burn-together/&do=findComment&comment=3366214

**Comment by MuricanJeb** [comment]
Ahh, I see! Thank you!

**Comment by PapaJoesSoup** [comment]
See Issue #520
