### ISSUE TITLE
Weapon Manager Not found

### ISSUE THREAD

**Issue by GeneralCaden** [PapaJoesSoup/BDArmory#510]
[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 
 - Bug Report   (Something is broken)

##### 1.4.3 and 1.2.0 Version

```

```

##### SUMMARY
Even though I have a Weapon Manager on my air craft I am not able to access it and use it, this is bad because I love dog fights and bombing runs. Please tell me how to fix the problem and make the Weapon manager appear.

**Comment by MuricanJeb** [comment]
Can't find anything without log files...

**Comment by RichTheWolf257** [comment]
Do you have Module Manager installed?
