### ISSUE TITLE
Guard mode not using timed fuse 

### ISSUE THREAD

**Issue by oliver1221** [PapaJoesSoup/BDArmory#511]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

```

```
KSP Version 1.4.3 BDA Version 1.2

SUMMARY
In older versions the guard mode set the detonation distance automaticly now it doesnt do it it just leaves the detonation distance how I set it.

STEPS TO REPRODUCE
Have a vessel with a weapon with air detonation and a timed fuse fly out a plane with a weapon manager set them on different teams turn on guard mode and watch

**Comment by Deathpuff12** [comment]
I seem to be having the same issue: the Millennium Cannon's auto-fusing doesn't properly work. The rounds detonate at the default detonation distance.

**Comment by gomker** [comment]
I did see this when I had to re-write those sections of code - it needs some work

**Comment by Gedas-S** [comment]
Should be fixed in the next release by #626 by @SuicidalInsanity

**Comment by Gedas-S** [comment]
Should be fixed in 1.3.0.
