### ISSUE TITLE
Radar window glitch

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#516]
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

KSP v1.4.3
BDAc v1.2.1

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY
The radar window will rotate in conjunction with the orientation of the vessel it is attached to .. If using a CIWS with rotating radar the radar window will rotate with the radar when active (see video linked below)

##### STEPS TO REPRODUCE
Fly craft with radar or use a rotating ground radar, launch and turn on radar ... see video: https://youtu.be/9ac0EPornHo

##### Log Files
Nothing in log showing errors

**Comment by PapaJoesSoup** [comment]
This was scan mode correct?  Let me look at the bg texture.  The lack of a background and  guiclips error means something in the texture load failed.  could be the texture image size in pixels.

**Comment by PapaJoesSoup** [comment]
Corrected.  Merged with Support Branch.  Will release with next scheduled BDAc release.
