### ISSUE TITLE
Tracers not Rendering

### ISSUE THREAD

**Issue by lancefoxcia** [PapaJoesSoup/BDArmory#520]
##### ISSUE TYPE
Tracers not Rendering - Bug Report   (Something is broken)

##### KSP and BDA Version
KSP 1.4.3
```
BDAc 1.2.1.1
```

##### OS / ENVIRONMENT
Windows 7

##### SUMMARY

Tracers for the bullets are not rendering at all when the turret fires a round.

##### STEPS TO REPRODUCE

Posting a video for steps

https://www.dropbox.com/s/aqcd8i0g7jusols/Video_Steps.mp4?dl=0

##### Log Files
https://www.dropbox.com/s/8lqfctids284nu5/KSP.log?dl=0

**Comment by jrodrigv** [comment]
You need to increase your KSP texture settings.

2018-05-21 9:46 GMT+02:00 lancefoxcia <notifications@github.com>:

**Comment by lancefoxcia** [comment]
Ah I see, I did a fresh ksp install and didn't touch the settings to make sure something was working for my mod. I thought something was wrong.

**Comment by PapaJoesSoup** [comment]
There is a problem in BDA supporting lower resolutions.   I have addressed this issue.  Tracers now render correctly in lower resolution settings In KSP.  Will be include with the next release of BDAc.
