### ISSUE TITLE
Radar window scale (bigger radar window)

### ISSUE THREAD

**Issue by L0ck0n** [PapaJoesSoup/BDArmory#521]
Currently there is only option to scale down radar window (below 100%), there is no option to make Radar window ﻿bigger than 100% (like 150% or 200%). Bigger radar window is especially usfeul for ﻿selecting swarm of ﻿missiles or crafts at bigger distances.

**Comment by PapaJoesSoup** [comment]
Implemented changes into Support Branch.  
New Behavior:
RWR and Radar windows now have 2 new persistent parameters each.  
RWR_WINDOW_SCALE_MIN, RWR_WINDOW_SCALE_MAX and 
RADAR_WINDOW_SCALE_MIN, RADAR_WINDOW_SCALE_MAX.  

By default these values are set to 0.50 and 1.50 respectively.  The scaling code now honors these persistent settings.  No provision has been made to allow alteringthe min and max values in the UI, but they can be changed in the settings.cfg file if the user desires to increase/decrease the limits.

Will be included with the next release of BDAc
