### ISSUE TITLE
ModuleManager Missing

### ISSUE THREAD

**Issue by fireblade599** [PapaJoesSoup/BDArmory#525]
##### ISSUE TYPE

 - Support

- Bugs...?

##### KSP and BDA Version

 1.4.3.2152

 1.2.1.2

##### OS / ENVIRONMENT

Windows 10 x64 bit

##### SUMMARY

When to go launch a craft using a BDArmory asset, it displays a message across the screen that BDArmory won't work without ModuleManager, which makes sense, however ModuleManager is non-existent in both the .zip at a face value or anywhere in the GameData.

##### Log Files

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2065610/KSP.log)

**Comment by Wraith977** [comment]
Module manager can be downloaded on this page under "downloads" and is omitted on purpose by the developers to reduce the occurrence of duplicate versions of MM

https://forum.kerbalspaceprogram.com/index.php?/topic/50533-141-module-manager-307-may-5th-2018-its-dangerous-to-go-alone-take-those-cats-with-you/

**Comment by fireblade599** [comment]
Ah. Thanks!
