### ISSUE TITLE
Increase Max G

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#528]
https://github.com/PapaJoesSoup/BDArmory/blob/support/BDArmory/Control/BDModulePilotAI.cs#L99

Kergan suggests 45

**Comment by TheKurgan** [comment]
My logic;
If it's a pure drone aircraft, it should be capable of pulling very high Gs. The breaking point is always 50, so something close like 40 or 45 should be allowed for the max... this allows for some SUPER maneuverability for AI operated drones. 

It would help with my missile tuning, as I have gotten to the point where the AI cannot dodge any of my (our) missiles.

**Comment by Gedas-S** [comment]
Is the 50 hardcoded in the game? Some mods might increase the values even higher?

Though, tbh, I've made plenty of text-edited airplanes with MaxG set to to 200, with only limited effects on performance. The main bottleneck is the dodging logic, but that one is not quick to revamp. :)

As an alternative, I can drop some code into the `PilotAI` to give it a button like the `SurfaceAI`'s `Goes to eleven`.

https://github.com/PapaJoesSoup/BDArmory/blob/c90b487b1abdb784024e624385b9a599a63d969d/BDArmory/Control/BDModuleSurfaceAI.cs?ts=4#L197

**Comment by TheKurgan** [comment]
All I am asking is that the maxValue = 25 be changed to maxValue = 45 here:

https://github.com/PapaJoesSoup/BDArmory/blob/c90b487b1abdb784024e624385b9a599a63d969d/BDArmory/Control/BDModulePilotAI.cs#L99

**Comment by TheKurgan** [comment]
If it works awesome, if it doesn't, no harm done.

**Comment by Gedas-S** [comment]
@gomker @TheKurgan felt like doing something tonight, so I added a parameter tuning unclamper to PilotAI and made a PR with it. It has been bothering me since January that I cannot make the minimum speed Mach 2. ;)

Also increased max maxG to 45 while I was at it. :)

**Comment by TheKurgan** [comment]
Awesome! Thanks!

**Comment by gomker** [comment]
Merged in Dev
