### ISSUE TITLE
New Weapon Type: EMP

### ISSUE THREAD

**Issue by XOC2008** [PapaJoesSoup/BDArmory#531]
##### ISSUE TYPE
 - Feature Idea (Something new you want to see)
 - Enhancement  (Expand on existing features)

##### KSP and BDA Version

1.4.X

##### SUMMARY

Create and implement a new weapon type (EMP) that will drain EC, damage or disable engines and EC producing parts, and delay the ability to restart for an as of yet unspecified amount of time. This opens the doors to all kinds of new weapons to build. Bombs, missiles, EMP mines, etc.

**Comment by gomker** [comment]
Questions on behavior

- do we want this to completely drain EC  -and- stop new EC generation?
- duration of effect
- thinking the effect will be weaker from the center of detonation, what kind of drop off, exponential, set range?
- one time use? burns out after detonation? or recharge cycle 
- manual only or some sort of proximity
- Friend or Foe - or is it Friendly fire capable

**Comment by SpannerMonkey** [comment]
```
do we want this to completely drain EC -and- stop new EC generation?
```
definitely drain all EC of all in range affected vehicles , If possible prevent EC gen for X time following event. This opens a window for  maybe a repair option.
```
duration of effect?
``` 
5 mins could seem like an eternity if under fire 
```
thinking the effect will be weaker from the center of detonation, what kind of drop off, exponential, set range?
```
Same as current blast radius 
```
one time use? burns out after detonation? or recharge cycle?
```
The intention was to have it delivered by device, Missile/Bomb,  so one shot 
```
manual only or some sort of proximity?
```
Based on device as above 
```
Friend or Foe - or is it Friendly fire capable?
```
Indiscriminate, will  affect any craft within range
