### ISSUE TITLE
[Feature Idea] Make rocket pods effected by "Unlimited Ammo"

### ISSUE THREAD

**Issue by TrueGkoliver** [PapaJoesSoup/BDArmory#533]
##### ISSUE TYPE

 - Feature Idea (Something new you want to see)

Right now, rockets aren't affected by the Unlimited Ammo option, which means no matter what, you will have a limited amount of rockets. I'm no master modder, but I'd imagine that  it wouldn't be that hard to make unlimited rockets the same way you make unlimited bullets for turrets.

Extra Idea: Make an "unlimited attachable rockets" option, too? It's certainly not necessary, but it would be awesome if you could!

Thanks in advance, your mod's awesome!

**Comment by TheKurgan** [comment]
@TrueGkoliver  Rockets and their launchers are a strange beast to me... they actually contain a physical limited number of rockets. This can't be changed. It's just like loading missiles in to a launcher... once the missiles are gone, they're gone.

**Comment by TrueGkoliver** [comment]
If I am correct, the way the system works for the infinite bullets is not reloading them right away, because what it does is it

**Comment by Gedas-S** [comment]
@TheKurgan no better way to motivate a dev to do something than to say it's impossible, eh? ;)

Made a PR for this. It's not quite perfect, but it works.

**Comment by TheKurgan** [comment]
I intentionally neglected to use the word impossible... I been here long enough to know the difference. LOL!

**Comment by gomker** [comment]
In dev branch
