### ISSUE TITLE
Enhancement: reducing Wing Command minimum formation spacing

### ISSUE THREAD

**Issue by nofabe** [PapaJoesSoup/BDArmory#543]
##### ISSUE TYPE
 - Enhancement  (Expand on existing features)

##### SUMMARY
Reducing the minimum spacing setting between vessels in formation, at least for ground vehicles, as the current minimum is at 20, which is still pretty far - giving a minimum of like 1 wouldn't change much about the mod itself as the default could just stay as it is, while giving players more freedom when it comes to configuring, if they so desire

**Comment by gomker** [comment]
I envision a slider for configuration in AI settings, maybe a review to consolidate those interfaces in Weapon Manager

**Comment by nofabe** [comment]
there already is, but the slider only goes to a minimum of 20

**Comment by gomker** [comment]
Oh, easy enough then :)
