### ISSUE TITLE
(Bug report) - Weapons automatically turn off when a part explodes.

### ISSUE THREAD

**Issue by Sticky3002** [PapaJoesSoup/BDArmory#546]
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

BDArmory Continued v1.2.2.1 (Installed via CKAN) and Kerbal Space Program 1.4.4

##### (I'd like to include the mod list I have installed just in case)
-Chatterer (and Chatterer Extended)
-Eva Follower
-Kerbal Engineer Redux
-Module Manager
-Physics Range Extender
-PlanetShine
-Show FPS
-Trajectories
-VesselMover Continued
(All installed via CKAN)

##### OS / ENVIRONMENT
Windows 7 Ultimate

##### SUMMARY
When any parts from any other crafts within the physics range explodes, any activated weapons from the vessel being controlled manually will automatically toggle off.

##### STEPS TO REPRODUCE
- Deploy a craft with weapon manager alongside any type of gun.
- Toggle on any gun.
- Shoot another craft.
- If the target part from the target craft receives enough damage, it will explode and therefore causing the issue. See example: Part 1: https://i.imgur.com/vlDMp6D.png 
                                      Part 2: https://i.imgur.com/pgf1Y35.png
Additional scenario/steps:
- Deploy a craft with weapon manager alongside any type of gun.
- Toggle on any gun.
- Have another aircraft within the physics range slam into the ground.
- When the parts explode, the issue will happen.

##### Log Files
No log files indicating there's a problem...? I'm not entirely sure how this one works, but after looking up in tutorials on forum threads and following the instructions, the log file is not found in the KSP_Data nor KSP_x64_Data folder. I may have not followed the right step/not looked up in the correct place, but I still haven't found the log file.

**Comment by Sticky3002** [comment]
So hidden folders uh? Thanks for explaining that for me. Awesome mod on the other hand.

**Comment by Gedas-S** [comment]
Seems to work just fine for me in dev. Not sure if it's a case of "works on my box" or if it was actually fixed in the meantime, and not marked as fixed.
