### ISSUE TITLE
Game Crash on prerelease

### ISSUE THREAD

**Issue by Alex-Champion-of-Hephaestus** [PapaJoesSoup/BDArmory#55]
output log was too big so here is a link 

https://drive.google.com/drive/folders/0B0k1YbVlc49-V1QyX2N4ai0zems?usp=sharing

**Comment by Nerfclasher** [comment]
look like stock bug because of all the nulls refs with krakensbane showing more than 100 times go repeat in stock and report it to squad

**Comment by TheDestroyer111** [comment]
Somebody close this!
