### ISSUE TITLE
AI not engaging in dogfight competition

### ISSUE THREAD

**Issue by AlexMFClark** [PapaJoesSoup/BDArmory#553]
- Support 	 

KSP 
1.4.3.2152
BDA Version
1.2.1

Win 10 

AI pilots will not engage with each other when competition starts. Will fly directly at each other w/o firing weapons.

Built new craft for reproduction of problem after reinstall of KSP and BDA.

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2217354/KSP.log)

**Comment by AlexMFClark** [comment]
Update:
New Log File
Removed all mods except for BDA and associated mods required for BDA. 

Used stock craft (Dove) to replicate. Added AI Pilot & MM, added 3 AIM9 missiles, placed 2 craft on runway, take off with no engagements from weapons.

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2217680/KSP.log)

**Comment by jrodrigv** [comment]
Please remove all this mods and assemblies and retest:

Loading assembly at C:\Kerbal Space Program\GameData\ModuleManager.2.6.7.dll
[LOG 21:03:10.344] AssemblyLoader: Loading assembly at C:\Kerbal Space
Program\GameData\ModuleManager.2.8.1.dll
[LOG 21:03:10.346] AssemblyLoader: Loading assembly at C:\Kerbal Space
Program\GameData\ModuleManager.3.0.4.dll
[LOG 21:03:10.348] AssemblyLoader: Loading assembly at C:\Kerbal Space
Program\GameData\ModuleManager.3.0.6.dll
 C:\Kerbal Space Program\GameData\Firespitter\
 C:\Kerbal Space Program\GameData\MechJeb2\
C:\Kerbal Space Program\GameData\WorldStabilizer\Plugins\WorldStabilizer.dll
