### ISSUE TITLE
autopilot dosent worke

### ISSUE THREAD

**Issue by NoBody76** [PapaJoesSoup/BDArmory#557]
- Support 	 

Ksp :145

Bdamory; all

##### OS / ENVIRONMENT
windows 10

##### SUMMARY
no engins exept jx-4 with autopilot
##### STEPS TO REPRODUCE
build plane with any engin exept jx4 and add autopilot 
launch and use autopilot.

**Comment by XOC2008** [comment]
I am not sure if you are saying no engines work except the jx-4, or all engines work except the jx-4. In either instance, I cannot replicate this issue. All engines (except for RPM controlled Firespitter engines) function under autopilot for me.

**Comment by NoBody76** [comment]
non exept jx-4 work

**Comment by Gedas-S** [comment]
@NoBody76 what language KSP do you use? Do you have logs of this issue?

**Comment by NoBody76** [comment]
okay switching from german to english fixed it

**Comment by Gedas-S** [comment]
If someday you'd want to provide the relevant logs so we can try to see what's wrong and fix it, that'd be great. Meanwhile closing this. :)

**Comment by Sushka597** [comment]
i have the same problem but i use english
