### ISSUE TITLE
Weapon manager non functional in build  01553

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/BDArmory#56]
Noticed non functional weapon manager on loading vessel.  
Created new install with only BDAc and quickstart.  
Tested again weapon manager non functional,  gui opens shows no weapon manager found message   Checked cfg and log, error as follows

`[ERR 12:40:42.693] Module ModuleWeapon threw during OnStart: System.MissingMethodException: Method not found: 'Part.FindModelComponents'.
  at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 

[ERR 12:40:42.697] Module MissileFire threw during OnStart: System.MissingFieldException: Field '.GameEvents.onPartJointBreak' not found.
  at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 `

Compiles with the following errors
`'Krakensbane' does not contain a definition for 'Threshold'	\ModuleWeapon.cs		
`
`Argument 1: cannot convert from 'method group' to 'EventData<PartJoint, float>.OnEvent'	\MissileFire.cs	
`

**Comment by Nerfclasher** [comment]
Ok it is a reference to krakensbane but with bdac this got more interesting let me try to make a save with this issue

**Comment by Nerfclasher** [comment]
Look like @jrodrigv fixed it in the latest  commit on the support branch
