### ISSUE TITLE
BDarmory requires "module manager" to work properly?

### ISSUE THREAD

**Issue by kspguy** [PapaJoesSoup/BDArmory#563]
What is module manager? Where do I get module manager? Could you please tell me what this is and maybe link it to me if it's a separate mod? I keep searching "BDarmory module manager" online but I can't find any answers to my problem. Thanks and bye

**Comment by TheKurgan** [comment]
[https://ksp.sarbian.com/jenkins/job/ModuleManager-Dev/](url)

click on ModuleManager.dll	right under Last Successful Artifacts

**Comment by kspguy** [comment]
Thanks so much guys!

**Comment by fruitsbar** [comment]
I installed both the ModuleManager.dll and the PhysicsRangeExtender but now is it's saying 'Weapon Manager not found.' Could I have some help?
