### ISSUE TITLE
Hydra70 rocket is underpowered

### ISSUE THREAD

**Issue by TheDestroyer111** [PapaJoesSoup/BDArmory#57]
The hydra70 rocket pod weighs more than the S-8KOM pod, and holds less rockets. Although in the .cfg files the hydras have more powerful explosions, ingame live-fire testing shows no difference between the explosive power of the two rocket types.

**Comment by Hector919** [comment]
I did set up a small construction made of mostly girders, held in place by launch clamps and fired both hydra and S-8 rockets at the ground below it. the rocket pods were attached to the girder structure, so they would always impact the same spot. to destroy the girders, it took either three hydra missiles or five S-8 missiles.

They are different in terms of damage, but not that much.

**Comment by gomker** [comment]
Updates to armor and ammo configs forthcoming in next release
