### ISSUE TITLE
Predictable bullet distribution

### ISSUE THREAD

**Issue by Gedas-S** [PapaJoesSoup/BDArmory#571]
It has been reported by @SpannerMonkey that low RPM turrets follow a predictable bullet distribution pattern: a few short (low), a few long (high), a few on target, repeat.

In all likelihood this is a problem with the random number generator, needs investigation.

**Comment by meltingSnowdrift** [comment]
Is the "fix pending release" label still warranted after release 1.2.4.0 has been made? What about the other issues with the same label?
