### ISSUE TITLE
Module manager missing?

### ISSUE THREAD

**Issue by whyunowork** [PapaJoesSoup/BDArmory#573]
##### ISSUE TYPE

 - Support

##### KSP and BDA Version

KSP: 1.4.5

BDA: 1.2.2.2

##### OS / ENVIRONMENT
PC

##### SUMMARY
Whenever I open the BD armory menu (with a weapons manager), big red text showing "Module Manager missing, BDA will not work properly" appears onscreen and doesn't change.

##### STEPS TO REPRODUCE
1. Open BD armory menu
2. That's it.

##### Log Files
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/2385927/output_log.txt)

**Comment by TheKurgan** [comment]
Module Manager is a dependency for BDAc, and is not included in the mod.

**Comment by whyunowork** [comment]
I've already installed that, but it still says I'm missing it

**Comment by TheKurgan** [comment]
ok, lets see if I can help you out.

Module Manager is only one file, and it goes here, like this:
https://i.imgur.com/5bGAfJM.jpg

**Comment by TheKurgan** [comment]
see it in the bottom right of that pic?

**Comment by TheKurgan** [comment]
it goes right in the root of your GameData folder

**Comment by TheKurgan** [comment]
Looking at your log, you have an OLD module manager file. Use the one I linked, and delete these files:

ModuleManager.2.8.1.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree

**Comment by whyunowork** [comment]
Where can I find the .dll?  Is it in the module manager master?

**Comment by TheKurgan** [comment]
https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/lastSuccessfulBuild/artifact/MechJeb2-2.7.3.0-801.zip

**Comment by TheKurgan** [comment]
wait... sorry

**Comment by whyunowork** [comment]
I've got that in my folder already, here's a pic
![idk](https://user-images.githubusercontent.com/43300040/45589164-f2737d80-b8d5-11e8-822c-27b9ca82db35.PNG)

**Comment by TheKurgan** [comment]
I made a mistake. One sec I'll have the right link

**Comment by whyunowork** [comment]
Haha, no worries

**Comment by PapaJoesSoup** [comment]
That is the source code.   you need the dll...

**Comment by TheKurgan** [comment]
delete ModuleManager-master

**Comment by TheKurgan** [comment]
https://ksp.sarbian.com/jenkins/job/ModuleManager/lastSuccessfulBuild/artifact/ModuleManager.3.0.7.dll

**Comment by TheKurgan** [comment]
that is the correct one. my apologies

**Comment by whyunowork** [comment]
Thats the file ive been looking for, lets hope this works!  Give me a sec to boot up the game.

**Comment by TheKurgan** [comment]
I linked MechJeb to you.... DUH, sorry about that. if you installed MechJeb because of me, you can delete that too.

**Comment by whyunowork** [comment]
Jackpot!  Thanks you guys!  You all are some serious heroes.

**Comment by TheKurgan** [comment]
You're welcome... I need more coffee LOL!
