### ISSUE TITLE
Custom modular missile doesn't work.

### ISSUE THREAD

**Issue by Astrowolf13** [PapaJoesSoup/BDArmory#574]
##### ISSUE TYPE
Bug Report

##### KSP and BDA Version

KSP - 1.4.5
BDArmory - 1.2.2.2
PRE - 1.7.0

##### OS / ENVIRONMENT
Windows 10 64-bit

##### SUMMARY
When testing a one-staged SAM, built by myself, i could not launch it - after the decouple works out, engines do not activate (they are still disabled when i check them) and missile falls down on the ground. Everything seems to be ok with the modular guidance and power supply - it just does not fly upwards.

##### STEPS TO REPRODUCE
1.Build a random one-stage missile with Modular Missile guidance (no procedural parts involved, their version is outdated) and liquid fuel engines.
2. Set it to AAM mode, radar targering.
3. Custom stage one - Activate engines.
4. Reboot it to the engine (so it will stand on the radial decoupler).
5. Save it to Subassembling zone.
6. Build a wheeled missile carrier with a TWS radar and a decoupler on it (radial, in my case).
7. Reboot it to the decoupler.
8. Place a missile on a carrier with its engine on the decoupler.
9. Start test mission, check the electicity and fuel ready to burn.
10. Open weapon manager, select the missile.
11. Press fire (without any targets inbound).
12. Missile decouples and jumps off the carrier, without having its engine activated.
Help please. I will hug you.

# #

**Comment by jrodrigv** [comment]
I'd like to clarify that you can use the procedural parts from my mod BDModularMissileParts because it still works perfectly with KSP 1.4.5. Also you can download ProceduralParts for KSP 1.4.5 using CKAN,

Now, regarding the steps to reproduce:

Step 3. Custom stage one- activate engines. Do you mean that you have added to the "Custom Action Group 1" the activate engine action?

Did you check which is current state of the engine after firing the missile? It is just not activated or it is flame-out due to resources?

Would you mind to record a video? It would be very helpful.

Thanks!

**Comment by Astrowolf13** [comment]
Hello jrodrigv,
Oh, that was a suprise for me. The freshest one i found was dated on summer 2017. Looks like I need to look better.
Step 3. Yes, it is custom action group 1. All according to this guide, excet procedural parts: https://github.com/jrodrigv/BDModularMissileParts/wiki/1.-Building-your-first-Modular-Missile
And the state of missile was Deactivated, not Flame-out. Not a single drop of fuel or electricity was used.
Thank you that you decided to help me.

**Comment by Astrowolf13** [comment]
https://drive.google.com/file/d/1_gI7TEgX5jHGMpQhCoToJPZs3qO8n5og/view?usp=sharing
Oh wait, here, have it.

**Comment by Astrowolf13** [comment]
So using a weapon manager is a no-no for this particular reason?
BTW, I tried to launch it using the Fire missile button thru a Modular Missile Guidance, and same thing happened.
Will try it later with a flying target.

**Comment by jrodrigv** [comment]
> What do you mean by staging the missile stage?
 Looking at the video it seems that you are trying to fire the missile clicking "Space" and staging instead of firing the missile using the specific button and actions.

I will try to reproduce your scenario locally and record a video too :)

**Comment by Astrowolf13** [comment]
Ah, I did not use space, I used WM menu + trigger on click.
Still thank you for the reccomendations.

**Comment by jrodrigv** [comment]
@Astrowolf13 I have done a local test and everything is working as expected.

I have uploaded a stock modular missile to kerbalx (you only need tweakscale)
https://kerbalx.com/crafts/47739/

It is a subassembly ready to use, just drag & drop on a decoupler. AAM modular missile ready to destroy planes :)

**Comment by Astrowolf13** [comment]
Hello again, jrodrigv!
I could not download your missile because of the error 404 - I do not know what happened.
So i retried to build a missile with my own hands and tested it on flying target - the results are in this video (custom action group 1 - only Activate engines):
https://drive.google.com/drive/u/1/my-drive

**Comment by Astrowolf13** [comment]
GOOD NEWS!
I now can get the missile of the ground - the only thing looks like I forgot to add is a unmanned command module for the missile - but now I have to improve its stabilization.

**Comment by jrodrigv** [comment]
That might be more difficult to test. Is the radar within range? Can you test to fly the target vessel to ensure a stable flight path?

I recommend to disable the roll correction too

**Comment by Astrowolf13** [comment]
Finally got it right - I flew my test craft higher in the sky, launched a missile (using radar data receiver for the missile carrier, data link through TWS locking radar), it keeps tracking until it actually flies near the craft, sometimes detonating (the problem is that missile keeps going a bit under the plane, and I could blow it up only by crashdiving). How do I fix this? Does it relate to the settings in MMG? Please write me down.
PS Where can I get those procedural parts for the BDA? Would you mind leaving a link?

**Comment by jrodrigv** [comment]
You can download the procedural parts from here:
https://github.com/jrodrigv/BDModularMissileParts

For AAM missiles I recommend to set the detonation distance to at least 10 meters to ensure a detonation.

I have seen also the missiles flying under planes not sure if it is due to lack of lifting surface/reaction time of the missiles. But you can mitigate this by increasing the explosive amount or the detonation range distance.

**Comment by Astrowolf13** [comment]
Thank you very much! Just one more question - how do I use this universal ammo boxes from the inventory?
