### ISSUE TITLE
Self guided missiles

### ISSUE THREAD

**Issue by coltenmfr** [PapaJoesSoup/BDArmory#581]
i think it would be cool if you were able to guide cruise missile or a air to surface missile,because using radar is confusing

**Comment by Gh0stReaper123** [comment]
For your first statement: 
Sorta but you can already do that with the stock game albeit a bit more complicated. Also, how would anyone be able to control more than one missile if guard mode fires more than one.

For your second statement:

Not really; all you need to do is equip an AMRAM or PAC-3 missile, select it, choose your target on the radar display and fire it.

**Comment by jrodrigv** [comment]
I don't think this is gonna happen.  As @Gh0stReaper123   you can already do this.
