### ISSUE TITLE
Hard Coded Radar Display Range Cap?

### ISSUE THREAD

**Issue by Isenderen** [PapaJoesSoup/BDArmory#584]
##### ISSUE TYPE

 - Support 	    ( Need help getting something to work)

##### KSP and BDA Version

```KSP 1.4.4

```BDAc 1.2.2.2a

##### OS / ENVIRONMENT

Windows 10 64 Bit

##### SUMMARY
I'm attempting to make some more realistically ranged radars starting with the AN/APG-71.
But even though i have my float curves set to be able to see a fighter out to about 130NM
or 240km and a bomber out to about 200NM or 370km, the radar display only goes out to 100km.
Is this a hard coded cap on the radar display, or am i doing something wrong in the programming
of my radar? Ill attach both my radars file (which will need to be converted back to a CFG from
a text file), and my KSP log.

##### STEPS TO REPRODUCE
<!--
If you want to test my radar only going out to 100km, just drop my radars file into your ksp at
GameData\BDArmory\Parts\radome125. I'm not to great at modeling, so it just uses the AN/APG-63
radomes model and texture.
-->


##### Log Files
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2452407/KSP.log)
[Radome2.txt](https://github.com/PapaJoesSoup/BDArmory/files/2452414/Radome2.txt)

**Comment by PapaJoesSoup** [comment]
100 km is the default range cap.  However it can be changed.  There is a float curve as part of the part config.  You will need to alter that curve.  I forget which parameter it is, but you should be able to locate it.  I believe the numbers are In meters, so 100000 is 100 kilometers iirc.

**Comment by Isenderen** [comment]
The only curves im seeing are the Radar Track and Radar Lock curves and those use KM and M^2.
I used the AN/APG-63s file as a template that i input my researched values into, and i also added more data points on the track and lock curves in an attempt to create a more accurate curve. Would using the -63 as a template not include that max display range curve, or would the extra data points on the track and lock curves affect anything?

**Comment by Isenderen** [comment]
Ive looked through all the different radars in base BDA and i cant find anything regarding the display range float curve. Only track and lock ones.

**Comment by PapaJoesSoup** [comment]
Sorry for the delay in the response.  In the Parts/radome125 folder  You will find radome1.cfg.  in there is this:
          radarDetectionCurve
          {
            // floatcurve to define at what range (km) which minimum cross section (m^2) can be detected.
            // this defines both min/max range of the radar, and sensitivity/efficiency
            // it is recommended to define an "assured detection range", at which all craft are detected regardless
            //     of their rcs. This is achieved by using a minrcs value of zero, thus detecting everything.
            //        key = distance	rcs
                      key = 0.0	0
                      key = 5	0	//between 0 and 5 km the min cross section is 0, thus assured detection of everything
                      key = 10	5   //
                      key = 20 15	//
                      key = 35 25	//maxrange of 35km
          }
This section defines the min and max range of the radar.  if the max range is less than the max range in the defaults, the defaults will apply.  if the max range in this section exceeds the max range default (100km) then the max range of the part applies.

radarDetectionCurve is the parameter you need to adjust for a higher max range on the display.

**Comment by Isenderen** [comment]
The largest datapoint on my detection curve is 370km though. Although I do have 7 or 8 data points (i cant remember at the monent which of those it is) in the curve. Could my extra data points be causing the issues?

**Comment by Isenderen** [comment]
Ill try a few different things tomorrow:
1. Matching distances on the curves
2. Cutting the datapoints on the curves down to 5
3. Combining the previous two.

Ill see if those fix the issues.

**Comment by Isenderen** [comment]
Update:
Matching the distances on the float curves data points did nothing, the radar display will still stop at 100km. And deleting data points on the curves so that theres only 5 data points just pulled the range limit in to 10km.

**Comment by Isenderen** [comment]
Ive been thinking over this and those last two things i tried were the only things i can think of to extend the range. I dont really know what else to try.

**Comment by Isenderen** [comment]
Sorry its been a while, ive been caught up in some other things. But ive tried the last thing i can think of, which is making it so that each node is double the distance of the previous node. Specifically 0, 8, 16, 32, 64, 128, 256, and 512km. But the display in game still only displays 1, 3, 5, 10, 20, 40, and 100km ranges.

I dont have any more ideas after this one.
