### ISSUE TITLE
BDA Weapons Manager UI button missing 

### ISSUE THREAD

**Issue by jman117** [PapaJoesSoup/BDArmory#59]
The weapon manager is installed on my craft, but when I "launch" my craft there is no UI button to control weapons.

![capture](https://cloud.githubusercontent.com/assets/22826429/19369867/fbe0fd86-915c-11e6-8dc5-9477ec9e73a1.PNG)

**Comment by Nerfclasher** [comment]
First thing first I need logs so I know if it's installed properly or not and please give me your version of kerbal space program

**Comment by MysticDeath** [comment]
Hi, im having the same problem. the weapons manager and missiles dont do anything when you right click on them either. I am running KSP version 1.2. How do i show my you logs?

**Comment by gomker** [comment]
@MysticDeath We have not released the version for 1.2 yet, we are doing some final testing before release.

**Comment by MysticDeath** [comment]
@gomker Ok, thank you for the notice, Good luck to you guys with the mod and the 1.2 release!

**Comment by Guard13007** [comment]
Since we're here, any ETA for 1.2 or unknown right now?
