### ISSUE TITLE
Airplane plus have part hp in the millions?

### ISSUE THREAD

**Issue by MuricanJeb** [PapaJoesSoup/BDArmory#598]
##### ISSUE TYPE
 - Bug Report   (Something is broken)
##### KSP and BDA Version

1.5.1

v1.2.3

##### OS / ENVIRONMENT
Windows 10, device is a laptop

##### SUMMARY
I noticed that most parts from airplane plus have MILLIONS of hp. I don't know if it's a bug from bda, a bug with module manager, or just the airplane plus parts themselves, but I'm sure either way this behaviour is not supposed to happen.

##### STEPS TO REPRODUCE
Simply just look at some the airplane plus parts, they have HP in the millions. The ones I specifically noticed to have this issue were the drone core and the drone's cargo bay nose, but there are other parts with this issue too.

##### Log Files

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2593190/KSP.log)

**Comment by jrodrigv** [comment]
Thanks for the information. I will review it!

**Comment by RaptorTech-Inc** [comment]
> ##### ISSUE TYPE
> * Bug Report   (Something is broken)
> 
> ##### KSP and BDA Version
> 1.5.1
> 
> v1.2.3
> 
> ##### OS / ENVIRONMENT
> Windows 10, device is a laptop
> 
> ##### SUMMARY
> I noticed that most parts from airplane plus have MILLIONS of hp. I don't know if it's a bug from bda, a bug with module manager, or just the airplane plus parts themselves, but I'm sure either way this behaviour is not supposed to happen.
> 
> ##### STEPS TO REPRODUCE
> Simply just look at some the airplane plus parts, they have HP in the millions. The ones I specifically noticed to have this issue were the drone core and the drone's cargo bay nose, but there are other parts with this issue too.
> 
> ##### Log Files
> [KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2593190/KSP.log)

![image](https://user-images.githubusercontent.com/45148815/48755596-77bf3980-ec5b-11e8-8c86-1a7d4c653dd9.png)

Also occurs with B9 parts as well.

**Comment by MuricanJeb** [comment]
Maybe we should make adjustable hit points, that way issues like these can be easily resolved. Although the downside of this is HP might be able to be edited in flight like armour, it would provide an easy fix for now until the team look deeper into this problem.

**Comment by jrodrigv** [comment]
I will provide some testing binaries soon. The Airplane plus mod is returning wrong values using the same methods I use for the rest of the parts.

I will clamp the Hitpoints value to avoid crazy values in some mods.

**Comment by jrodrigv** [comment]
@meltingSnowdrift  We are not storing the hitpoint values, they are calculated when a vessel is loaded unless maybe when you have a MMpatch. (not completely sure about it)

You can create MMpatch to fix the values as a hotfix, using this example
https://github.com/PapaJoesSoup/BDArmory/blob/master/BDArmory/Distribution/GameData/BDArmory/MMPatches/000000_HitpointModule.cfg

For the next release of BDArmory the MMPatch would not be really necessary for AP+ because I will add some logic to avoid the extreme HP values.

**Comment by meltingSnowdrift** [comment]
If hitpoint values are not stored in craft files, why does this appear in a craft file?
![image](https://user-images.githubusercontent.com/45924338/50380147-2e805200-062c-11e9-90c0-07b21f81ac5d.png)

**Comment by jrodrigv** [comment]
Uhm I will do more testing when I have time. Even if the are stored they should be autocalculated at runtime everytime you load a craft. For example if you reduce the mass of a part, it should give you a different HP value.

**Comment by MuricanJeb** [comment]
Just coming here to say thanks to all the people contributing to help fix this problem, even during the holidays 😄

**Comment by meltingSnowdrift** [comment]
👏

**Comment by meltingSnowdrift** [comment]
In BDA 1.2.4.0, I launched a vessel created in 1.2.3.0 with an existing (wrong) hitpoint count stored for a part and this value was kept both when loaded in the editor and when launched. This incorrect hitpoint count originated from a value explicitly specified in a config file; neither the original nor the new value with which I wanted to replace it were auto-generated.

If this is very hard to prevent Is it possible to at least make some functionality that automatically corrects all hitpoint counts stored in craft files to the newest ones specified in part configs?
