### ISSUE TITLE
Kursor of the Kraken

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#6]
This occurs in a fresh install with only BDArmory installed:

The issue is when you press the \ key to toggle your mouse to camera pan mode and then switch vessels using the [ or ] key, your cursor reappears in the center of the screen and stays there until you exit the pan mode.

I have discovered that this only occurs when focus switches to a part that does not have a weapon manager module attached to it ... It also occurs when you switch to a Kerbal

I dug through the log for the video I posted and found the exceptions being spammed 

---

[LOG 11:54:51.441] [FLIGHT GLOBALS]: Switching To Vessel AGM-114 ----------------------
[LOG 11:54:51.445] [PlanetariumCamera]: Focus: AGM-114
[EXC 11:54:51.569] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:51.851] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:52.855] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:53.040] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:53.333] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:53.415] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:54.002] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:54.104] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:54.338] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:54.363] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:54.547] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:54.665] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:54.706] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:54.964] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:54.968] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:55.008] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:55.340] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:55.384] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:55.680] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:55.704] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:55.767] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:55.926] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:55.985] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:56.111] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:56.451] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:56.475] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:56.513] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.UpdateGuardViewScan ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[LOG 11:54:56.574] AGM-114 Hellfire Missile linecast hit on model_island_ap_exterior_v46_ground_collider
[LOG 11:54:56.576] [F: 19178]: [00:00:11]: AGM-114 Hellfire Missile exploded due to overheating.
[LOG 11:54:56.577] bahaAGM-114 Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.578] [bahaAGM-114]: Deactivated
[LOG 11:54:56.583] AGM-114 Hellfire Missile linecast hit on model_island_ap_exterior_v46_ground_collider
[LOG 11:54:56.584] bahaAGM-114 Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.585] [bahaAGM-114]: Deactivated
[LOG 11:54:56.603] [F: 19178]: [00:00:11]: Clamp-O-Tron Docking Port Jr. exploded due to overheating.
[LOG 11:54:56.605] [Explosion] Combined.
[LOG 11:54:56.605] dockingPort3 (CANUKWorks CP-302 Mishka Rover) Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.612] Saved ripple data: M230,True,650;
[LOG 11:54:56.616] [dockingPort3 (CANUKWorks CP-302 Mishka Rover)]: Deactivated
[LOG 11:54:56.618] [F: 19178]: [00:00:11]: Modular Girder Segment exploded due to overheating.
[LOG 11:54:56.619] [Explosion] Combined.
[LOG 11:54:56.620] trussPiece1x Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.639] Saved ripple data: M230,True,650;
[LOG 11:54:56.657] [trussPiece1x]: Deactivated
[LOG 11:54:56.659] [F: 19178]: [00:00:11]: TR-2L Ruggedized Vehicular Wheel exploded due to overheating.
[LOG 11:54:56.661] [Explosion] Combined.
[LOG 11:54:56.661] wheelMed Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.666] [wheelMed]: Deactivated
[LOG 11:54:56.668] [F: 19178]: [00:00:11]: 30mm Ammunition Box exploded due to overheating.
[LOG 11:54:56.669] [Explosion] Combined.
[LOG 11:54:56.670] baha30mmAmmo Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.671] [baha30mmAmmo]: Deactivated
[LOG 11:54:56.673] [F: 19178]: [00:00:11]: TR-2L Ruggedized Vehicular Wheel exploded due to overheating.
[LOG 11:54:56.675] [Explosion] Combined.
[LOG 11:54:56.675] wheelMed Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.680] [wheelMed]: Deactivated
[LOG 11:54:56.682] [F: 19178]: [00:00:11]: 30mm Ammunition Box exploded due to overheating.
[LOG 11:54:56.683] [Explosion] Combined.
[LOG 11:54:56.684] baha30mmAmmo Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.685] [baha30mmAmmo]: Deactivated
[LOG 11:54:56.688] [F: 19178]: [00:00:11]: EAS-1 External Command Seat exploded due to overheating.
[LOG 11:54:56.689] [Explosion] Combined.
[LOG 11:54:56.690] seatExternalCmd Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.695] [seatExternalCmd]: Deactivated
[LOG 11:54:56.779] [F: 19178]: [bahaM230ChainGun] Collision Enhancer Punch Through - vel: 216.0067
[LOG 11:54:56.781] [F: 19178]: [00:00:11]: M230 Chain Gun Turret collided into the surface.
[LOG 11:54:56.782] [Explosion] Combined.
[LOG 11:54:56.783] bahaM230ChainGun Exploded!! - blast awesomeness: 0.5
[LOG 11:54:56.784] [bahaM230ChainGun]: Deactivated
[WRN 11:54:56.841] Kerbal Jebediah Kerman was marked as debris, fixed.
[LOG 11:54:56.845] 2 explosions created.
[EXC 11:54:56.868] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.BDATargetManager.GetMissileTarget (BahaTurret.MissileFire mf, Boolean targetingMeOnly)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[LOG 11:54:57.034] [FLIGHT GLOBALS]: Switching To Vessel Jebediah Kerman ----------------------
[LOG 11:54:57.036] [PlanetariumCamera]: Focus: Jebediah Kerman
[WRN 11:54:57.044] [Part]: kerbalEVA holds crew but has no interior model defined!
[EXC 11:54:57.425] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.TargetInfo.get_position ()
    BahaTurret.MissileFire.SmartPickWeapon (BahaTurret.TargetInfo target, Single turretRange)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()
[EXC 11:54:57.523] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.MissileFire.StartGuardTurretFiring ()
    BahaTurret.MissileFire+<GuardTurretRoutine>d__162.MoveNext ()
[LOG 11:54:57.584] [FLIGHT GLOBALS]: Switching To Vessel CANUKWorks CP-302 Mishka Rover Probe ----------------------
[LOG 11:54:57.586] [PlanetariumCamera]: Focus: CANUKWorks CP-302 Mishka Rover Probe
[LOG 11:54:58.797] [FLIGHT GLOBALS]: Switching To Vessel CANUKWorks CP-302 Mishka Rover Debris ----------------------
[LOG 11:54:58.798] [PlanetariumCamera]: Focus: CANUKWorks CP-302 Mishka Rover Debris
[EXC 11:54:58.907] NullReferenceException: Object reference not set to an instance of an object
    BahaTurret.TargetInfo.get_position ()
    BahaTurret.MissileFire.SmartPickWeapon (BahaTurret.TargetInfo target, Single turretRange)
    BahaTurret.MissileFire.SmartFindTarget ()
    BahaTurret.MissileFire.GuardMode ()
    BahaTurret.MissileFire.OnFixedUpdate ()
    Part.ModulesOnFixedUpdate ()
    Part.FixedUpdate ()

**Comment by Nerfclasher** [comment]
#2 is this related

**Comment by PapaJoesSoup** [comment]
I will start looking at this one.

**Comment by gomker** [comment]
Is this still a problem in current version?

**Comment by jrodrigv** [comment]
@DoctorDavinci I've trying to reproduce it but I can't. Can you confirm if you can reproduce it?

**Comment by DoctorDavinci** [comment]
Solved on Windows (you can briefly see the cursor appear when switching between craft while in pan mode but it is only for a split second)

Linux has the dreaded thing, although instead of just craft or parts in game without a weapon manager, It happens regardless if there is one attached or not when switching between craft while in pan mode

Further investigation required as well as OSX confirmation

**Comment by jrodrigv** [comment]
I'm going to close this issue. We can always re-open if it becomes relevant for Linux or OSX users.
