### ISSUE TITLE
Proximity Fuse for Missiles

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#60]
Cruise missiles of a larger size sometimes need higher crash tolerances set to survive loading in game. This leads to some interesting results, such as the missile being turned into a battering ram. SpannerMonkey and I have seen it first hand with some of his Anti-Ship Missiles in his BoomSticks weapons pack.

I propose we add a feature configurable at the part level to turn on a proximity fuse to let the missile detonate at X meters away from target.  Later on make this something configurable via UI in VAB.

**Comment by TheDestroyer111** [comment]
I think this is already implemented for air-air, so maybe it is possible for ground target missile... Or you can just give them guidance type air-air, which afaik doesn't make it unusable :P

**Comment by gomker** [comment]
Technically speaking there is detonation is calculated from blast radius and distance from target however this not configurable.
We will be adding a  parameter so this can be adjusted per each missile. Add some realism as AA missiles IRL will detonate at distance, while Anti Ship Missiles will want to penetrate then explode etc... 
Since we do not have a penetration method I would set ASM missiles to detonate at something like 0.5 meters to keep the described behavior from occuring

**Comment by TheDestroyer111** [comment]
And BTW what do you mean by

> Cruise missiles of a larger size sometimes need higher crash tolerances set to survive loading in game.

KSP has lots of big parts with small tolerances which somehow don't get rekt by the kraken...

**Comment by gomker** [comment]
Mainly very large vessels for Maritime packs like[ Large Boat Pack](http://forum.kerbalspaceprogram.com/index.php?/topic/133439-113-large-boat-parts-pack/) have these issues. I am heavily involved in maintaining VesselMover as well as launching large boats can be problematic. New KJR beta is helping quite a bit.

Many times dropping the ship in water can cause my missiles to get destroyed prematurely as water can go right through the hulls, while there is buoyancy , parts are not configured to keep water out.  I bump up the crash tolerance to keep them from being eaten on contact with water.

**Comment by gomker** [comment]
Status update @jrodrigv has code in feature branch to implement this feature in a future release

**Comment by gomker** [comment]
Looks like missiles after launch are being set to almost unbreakable crash tolerance

https://github.com/PapaJoesSoup/BDArmory/blob/support/BahaTurret/MissileLauncher.cs#L626

`part.crashTolerance = 9999;`

**Comment by jrodrigv** [comment]
I think now I can extend the functionality implemented for the proximity fuse on Modular missiles.

@gomker  you can look for detonationRadius in https://github.com/PapaJoesSoup/BDArmory/blob/support/BahaTurret/Parts/BDModularGuidance.cs

**Comment by gomker** [comment]
@jrodrigv 
Check this branch out , first pass at adding it for all missiles

https://github.com/PapaJoesSoup/BDArmory/tree/Feature_ProximityDetonation

**Comment by gomker** [comment]
quick update - current branch not 100% - missile detonation check is not accurate, tried moving to different update() methods with no luck

**Comment by jrodrigv** [comment]
@gomker  I've noticed this as well with modular missiles. Not always, but sometimes. 

I'm wondering...
The proximity detonation method implemented by baha was working before,right?

`				//proxy detonation
				if(proxyDetonate && ((targetPosition+(targetVelocity*Time.fixedDeltaTime))-(transform.position)).sqrMagnitude < Mathf.Pow(blastRadius*0.5f,2))
				{
					part.temperature = part.maxTemp + 100;
				}`

This code is executed during the OnFixedUpdate. It is only taking into account the target position and velocity, and the explosion is triggered due to missile auto-destruction.

Maybe we should try using the same approach.

**Comment by jrodrigv** [comment]
This feature has been implemented and it will be released.
