### ISSUE TITLE
Missile turret follows mouse after deselection

### ISSUE THREAD

**Issue by meltingSnowdrift** [PapaJoesSoup/BDArmory#613]
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

```
KSP 1.5.1
BDA 1.2.3.0
```

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY

When a missile turret becomes deselected with at least one missile still attached to it, the turret begins rotating to follow the mouse as though it were selected and not slaved to any sensor.

##### STEPS TO REPRODUCE

Create a craft containing a weapon manager and a rotating missile turret such as the Patriot launcher. Place at least one missile in this turret. Launch this craft. In the weapons section of the weapon manager dialog, select the missile. As expected, the turret should follow the mouse. Select "None" to deselect the missiles. The turret should continue to follow the mouse.

If the turret is slaved to a sensor after this procedure, and the direction pointed to by the mouse is very different from that commanded by the sensor, the turret will visibly try to follow both and fail to point in the direction commanded by the sensor. I am not sure of the exact conditions required to reproduce this specific effect, but it very often, if not always, accompanies the main bug.

If all the missiles on a turret are fired (or, presumably, cease to be on the turret for any other reason), the turret will behave correctly when it becomes deselected.

On craft with multiple turrets, a turret may cease to be affected by this bug if another missile turret carrying missiles of a different type becomes selected. The originally affected turret will return to its normal idle position; when this next turret becomes deselected with at least one missile remaining on it, it will become affected by the bug.

**Comment by o24UK42o** [comment]
I can confirm the same issue in KSP version 1.4.5 as well.

**Comment by Gedas-S** [comment]
@meltingSnowdrift @o24UK42o  Thank you for the report. This should be fixed in the next version

**Comment by Gedas-S** [comment]
Should be fixed in 1.3.0.
