### ISSUE TITLE
No Weapon Manager Found

### ISSUE THREAD

**Issue by Schmitty548** [PapaJoesSoup/BDArmory#63]
I've installed the 1.2 prerelease to use in 1.2 KSP, but cannot use the weapon manager. The manager is on the craft, i have hotkeys set for arm/disarm, but under the BD Armory tab on the left of the screen, the message still says "No Weapon Manager Found." This very well be my fault, I might be using the wrong version, but I am just unsure. 
Sorry if this has been answered already or if this doesn't belong here, i looked but didn't find this thread, and i'm also new to Github

**Comment by gomker** [comment]
We have not yet released the final 1.2 build. The 1.2pre was built during the pre-release period in which a new build of 1.2 was coming daily  and we decided to not release any more after issues developed that needed more work to fix.

The final 1.2 build will be coming soon

**Comment by Schmitty548** [comment]
ahh ok thanks
