### ISSUE TITLE
Missile/Torp Drop Time Ignored When Decoupled Forward.

### ISSUE THREAD

**Issue by TheKurgan** [PapaJoesSoup/BDArmory#630]
ISSUE TYPE

 - Bug Report   (Something is broken)

KSP and BDA Version

KSP 1.6.0

BDAc latest dev version

OS / ENVIRONMENT
Windows 10

SUMMARY
 If a  Missile or torpedo is set to decouple forward, then drop time is not being considered at all, and the missile/torp's guidance activates immediately.

This is a very nasty bug, and is causing many issues. It's wreaking havoc on forward decoupled torpedoes and  missiles that should have a slight delay when being decoupled forward.

STEPS TO REPRODUCE

Load a missile or torpedo onto a rail, or into a tube, set decouple forward, decouple speed to 10 and drop time to 5. Launch, and notice that it takes off immediately.

**Comment by SpannerMonkey** [comment]
Confirmed in same KSP and BDA versions and displaying same behaviors

**Comment by Gedas-S** [comment]
Should be fixed in 1.3.0.
