### ISSUE TITLE
Radar Display will not match max range of radar

### ISSUE THREAD

**Issue by Isenderen** [PapaJoesSoup/BDArmory#633]
##### ISSUE TYPE

 - Support 	    ( Need help getting something to work)

##### KSP and BDA Version

```KSP 1.4.4

```BDAc 1.2.2.2a

##### OS / ENVIRONMENT

Windows 10 64 Bit

##### SUMMARY
I'm attempting to make some more realistically ranged radars starting with the AN/APG-71.
But even though i have my float curves set to be able to see a fighter out to about 130NM
or 240km and a bomber out to about 200NM or 370km. But the radar display only goes out to 100km.
Im Using my AN/APG-71 as an example, but this issue has been happening with any radar i try to make
see past 100km.
(This is edited and re-posted to more accurately reflect what the issue i'm seeing is.)

##### STEPS TO REPRODUCE
<!--
This issue happens with any radar who's detection or locking float curve is set to go farther than 100km.
-->


##### Log Files
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2452407/KSP.log)

**Comment by Gedas-S** [comment]
@Isenderen As far as I understand, fundamentally, this is still the same issue as #584, right?

It is generally better to have all the conversation for a specific issue in one place, that way we don't lose what other members of the team have already figured out, though the enthusiasm is appreciated. :)

**Comment by Isenderen** [comment]
Kindof, but also kindof not. The original issue was about if there was a hard coded cap on the radar display, which according to Papa jones there isnt. Now im trying to figure out what bug or miss coding on my part is preventing the display to match ranges. So at least from my perspective theyre related but separate issues.

If you want i can close this thread, or close the other thread and edit any relevant info thats missing to this one.

**Comment by Gedas-S** [comment]
Ah, alright.

I grabbed the Jernas turret, changed its `radarDetectionCurve` so the last key is 240, and the display happily goes out to 250km (the whole curve included below). Can you post your curves or the whole part config, because without that I'm not sure how to help you? :)

Also, sorry for the confusion, there is a hardcoded cap at 1000km, which might expand as you increase flying vessel loading range, but I haven't managed to make it work in half a minute of trying. The exact available increments are `{ 500, 2500, 5000, 10000, 20000, 40000, 100000, 250000, 500000, 750000, 1000000 }` in meters, the display will round up 500 and 2500 to 1km and 3km.

```
        radarDetectionCurve
        {
          // floatcurve to define at what range (km) which minimum cross section (m^2) can be detected.
          // this defines both min/max range of the radar, and sensitivity/efficiency
          // it is recommended to define an "assured detection range", at which all craft are detected regardless
          //     of their rcs. This is achieved by using a minrcs value of zero, thus detecting everything.
          //        key = distance	rcs
                    key = 0.0	0
                    key = 5	0	//between 0 and 5 km the min cross section is 0, thus assured detection of everything
                    key = 10 10   //
                    key = 15 20   //
                    key = 240 25	// this radar is NOT very good at detection (limited range, needs large rcs)
        }
```

![screenshot254](https://user-images.githubusercontent.com/8385798/51240601-b1bf6a00-1984-11e9-9de1-03d463215a4e.png)

**Comment by Gedas-S** [comment]
I see you are on BDA 1.2.2.2 which may or may not have the same values. If I remember correctly the ranges were increased back in 1.2.1.1 when SpaceRadar was added, so it should be the same. Before that it could have been hard capped at 100km.

**Comment by Isenderen** [comment]
Im not sure if copying and pasting this from the old thread will work but ill give it a try since im anout to go to sleep. [Radome2.txt](https://github.com/PapaJoesSoup/BDArmory/files/2452414/Radome2.txt)
The curves in there are older placeholder curves that i made. Since then ive made more precise curves, but they still havent changed the 100km setting being the max on my radar displays.

You are using BDAc 1.2.2.2c right?

**Comment by Gedas-S** [comment]
Your `Key` past 81 is capitalized, so unity ain't reading it right, fix it to `key` without the capital `K` and it should work. ;)

I'm on the dev version, but shouldn't change things.

**Comment by Isenderen** [comment]
ok, that makes Sense. Ill try it out tomorrow.

Kinda a side note, but have you guys implemented lofting on air to air missiles yet?

**Comment by Isenderen** [comment]
Update: It did work. Ill close this one now.
