### ISSUE TITLE
Modular missile parts aren't there

### ISSUE THREAD

**Issue by TheTimgor** [PapaJoesSoup/BDArmory#647]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Support 	    ( Need help getting something to work)

##### KSP and BDA Version
```
KSP 1.6.1
BDA 1.2.4
```

##### OS / ENVIRONMENT
Ubuntu

##### SUMMARY

The modular missile parts just aren't there.

##### STEPS TO REPRODUCE

I installed BD armory alongside several other mods, and the modular missile parts promised in the wiki aren't there.

**Comment by jrodrigv** [comment]
The modular missile parts are not part of BDA.

You need to get it from here:
https://github.com/jrodrigv/BDModularMissileParts

You need to download also Procedural Parts and Procedural Wings.
