### ISSUE TITLE
Weapon manager does not work (1.2pre)

### ISSUE THREAD

**Issue by oliver1221** [PapaJoesSoup/BDArmory#65]
i cant use the weapon manager with the BD button, it is telling me no weaponmanager found. it does also not work with action groups

**Comment by gomker** [comment]
Hi Oliver, The release for 1.2pre does not currently work with the Final 1.2.  There were daily builds coming out during testing and we decided not to release any interim updates fixes needed to be worked on.

We will be releasing the final build for 1.2 soon.
