### ISSUE TITLE
AI Guard mode missile wont fire

### ISSUE THREAD

**Issue by Cdough8** [PapaJoesSoup/BDArmory#654]
##### ISSUE TYPE

 - Support 	    ( Need help getting something to work)

##### KSP and BDA Version

KSP 1.4.5

BDA 1.2.2.2

##### OS / ENVIRONMENT
ios 10.14 mojave

##### SUMMARY
When I build an ai missile turret, the missile locks and tracks the plane but the missile does not fire unless the plane in at the same altitude as the turret. I replaced the missile with a gun turret and the gun worked perfectly. I have PRE installed and module manager 4.0.2

**Comment by Gedas-S** [comment]
Could be a clearance problem, you can try turning off clearance check in BDA options and see if it fires. Otherwise we'll need more info to help you, what turret, what missile, also the log files.

**Comment by Cdough8** [comment]
I have unchecked clearance check. I am using aim120 with the jernas missile launcher. 
[ModuleManager copy.log](https://github.com/PapaJoesSoup/BDArmory/files/2849123/ModuleManager.copy.log)

**Comment by Cdough8** [comment]
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2849136/KSP.log)

**Comment by jrodrigv** [comment]
@Cdough8 We don't support old versions of KSP. Would you mind to reproduce the same scenario but using latest version of KSP?

**Comment by Cdough8** [comment]
the problem is fixed with the newer versions

**Comment by jrodrigv** [comment]
Then I think this issue should be closed

**Comment by Cdough8** [comment]
actually i figured something out. It seems that any ground turret built in the SPH wont fire on guard mode, but if they are built in the VAB then they work fine. So ill just build them in the VAB
