### ISSUE TITLE
Reloadable missile module reloads more than 20 times

### ISSUE THREAD

**Issue by xdthegreat** [PapaJoesSoup/BDArmory#668]
##### ISSUE TYPE
 - Bug Report

##### KSP and BDA Version

1.6.1

1.2.4

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY
Reloadable missile module allows reloading more than 20 times.

##### STEPS TO REPRODUCE
1. Make new reloadable part using the module.
2. Fire and reload 21 times. Ammo/missile left will become -1

Test craft used: https://kerbalx.com/Xdthegreat/cruise-missile-car

**Comment by Gedas-S** [comment]
Should be fixed in 1.3.0.
