### ISSUE TITLE
Bug Report: Bullets speeding up over distance

### ISSUE THREAD

**Issue by lancefoxcia** [PapaJoesSoup/BDArmory#669]
##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version
1.6.0
```
v1.2.4
```

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY

I have tested with my own mod that I am currently working on. However this can apply to current BDAC Armor piercing bullets.

I have noticed that bullets will speed up the father a target is. An example I have done was taking a gun that shoots bullets at 775 meters a second.
Upon firing at a target at 2.5km, hitting the target. The bullet is going 1018 meters a second. 
Upon firing at a target at 25 Meters, hitting the target. The bullet is going 779 meters a second. 
Upon firing at a target at 7.4km, hitting the target. The bullet is going 1223 meters a second. 
##### STEPS TO REPRODUCE
Use an Abrams cannon. Bullet type Armor Piercing
Open the debug menu, set down a target to shot at with the cannon, fire at it, and watch as the bullet hits the target. Record down the speed at which it hits the target. Also look at the Bullet.cfg for the speed in which the cannon should fire at accordingly

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2944294/KSP.log)

**Comment by Gedas-S** [comment]
Yes, looks like you are right, the signs for drag calculation are messed up.

`dragVelocity` is calculated as a negative adjustment
https://github.com/PapaJoesSoup/BDArmory/blob/077b56587fe4da75456a57118a419ed760f57d35/BDArmory/Bullets/PooledBullet.cs#L548

but then used as if it was the current velocity after drag
https://github.com/PapaJoesSoup/BDArmory/blob/077b56587fe4da75456a57118a419ed760f57d35/BDArmory/Bullets/PooledBullet.cs#L297

Thank you for the report. :)

**Comment by lancefoxcia** [comment]
You're welcome. I was scratching my head as to why they were speeding up. 

At first, I just thought that gravity was the reason, but I know physics says that's bullshit and with a constant of force of drag being applied should slow the bullet down regardless.

Anyway, thanks for looking into it ^^

**Comment by Gedas-S** [comment]
Should be fixed in 1.3.0.
