### ISSUE TITLE
Radial Weapons

### ISSUE THREAD

**Issue by CondorLead** [PapaJoesSoup/BDArmory#67]
I think that it'd be nice to have a full selection of radial weapons to complement the existing 105mm when making gunships. 
Here is a list of the systems that have been present aboard the AC-130:
- 40mm L/60 Bofors
- 20mm M61 Vulcan
- 25mm GAU-12/U Equalizer
- 30mm ATK GAU-23/A (Mk44 Bushmaster II)
- 7.62mm GAU-2/A

Not all of these would have to be implemented, of course, this is simply a complete list of those weapons which were present.

**Comment by TheDestroyer111** [comment]
But... Why?
We already have the M61 Vulcan itself, while the FPS Weapons addon gives us the Minigun. For all the others, I think adding them is just not a very high priority as we already have four calibers of gun weapons. Personally, my AC-130 has 105mm, two turreted Vulcans, and one turreted M230 Chaingun (30mm gun, used in reality on the AH-64 Apache attack helicopter)

**Comment by Nerfclasher** [comment]
To be quite honest I don't think we want to add more parts to the core of bdac because you can make this into a weapons pack and the parts that come with bdarmory are examples of what bdarmory continued can do

**Comment by Guard13007** [comment]
Before considering adding these, let's look at what other packs have added? I think the needs can be met well enough by extensions.

**Comment by gomker** [comment]
@CondorLead  While I would love to see these weapons myself , I tend to agree that weapon pack makers have usually been the source of new weapons. The team feels that BDA is like reference model for others to build upon. The included weapons are a starting point and we are focusing on the core mechanics to make it all work

Have you seen these 
- [BoomSticks](http://spacedock.info/mod/506/BoomsticksRev3)
- [NAS](http://spacedock.info/mod/83/NAS%20-%20Naval%20Artillery%20System)

Also I suggest hitting up SpannerMonkey in the boomsticks thread. He is always taking suggestions and is the teams resident part master.

I will keep this open and let the team add their input.

**Comment by gomker** [comment]
Closing out now as this is really more for weapon mod makers rather than the core BDA
