### ISSUE TITLE
BDArmory not showing up in Toolbar nor in Build Mode

### ISSUE THREAD

**Issue by fruitsbar** [PapaJoesSoup/BDArmory#674]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version

```

```

##### SUMMARY
I installed everything; BDArmory, PhysicsRangeExtender, and Module Manager, and BDArmory won't show in toolbar nor in build mode (in which I can't find the category for BDArmory)

##### STEPS TO REPRODUCE
Install BDArmory (zip and newest version)
Install PhysicsRangeExtender (zip and newest version)
Install Module Manager (zip and newest version)
Put all of them in GameData

**Comment by xdthegreat** [comment]
Did you extract the files?
Place everything IN THE GAMEDATA file of the zip into the GAMEDATA FILE of your install.
There should only be 1 gamedata file in your whole install, no Gamedata/Gamedata

**Comment by fruitsbar** [comment]
Yes, I put the 'BDArmory' file into the Gamedata. Nothing else.

**Comment by fruitsbar** [comment]
Okay, I managed to fix everything, but there is something that I can't understand. When I click BDArmory on the toolbar, it says 'Weapon Manager not found.' I tried looking all over the internet for this, but I never could. Could I have some help with this?

**Comment by Sandrik2** [comment]
You have install a weapon manager (its a part) onto the aircraft to have the features of the BDArmory tab. It is located at the bottom of the parts list of the BDArmory section in the craft editor.

**Comment by fruitsbar** [comment]
oh, thanks! Help is appreciated.
