### ISSUE TITLE
Last Mk83 JDAM Bomb Cause Game Crash

### ISSUE THREAD

**Issue by didas72** [PapaJoesSoup/BDArmory#689]
When reporting issues please provide the following information:

##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

1.7.0

1.3.0

##### OS / ENVIRONMENT
Windows 10 (x64)
AMD Ryzen 5 2600
16GB RAM
Geforce RTX 2070
I'm using a joystick and controls are setup for the joytsick.
Mods:
BDA v1.3.0
Firespitter core(lastest)
Aviation plus(lastes)

##### SUMMARY
Every time I try to drop my last Mk83 bomb, the game crashes

##### STEPS TO REPRODUCE

I have my A-10 plane in which I placed 4 of the mk83 bombs and, While in flight and with a gps point active, when I trigger the last bomb, the game crashes without any error message. 

##### Log Files
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/3144753/KSP.log)
No output.txt file

**Comment by jrodrigv** [comment]
Sorry but you have other mods installed causing a massive number of errors. Please try to reproduce your issue but only using BDA mod, PRE and vessel mover.
