### ISSUE TITLE
(Realism) Inaccurate M2 Browning.

### ISSUE THREAD

**Issue by Wraith977** [PapaJoesSoup/BDArmory#69]
This is a really minor realism issue so feel free to place it at the very bottom of your to do list (or call me names and lecture me on how it **really** doesn't matter, whichever works :stuck_out_tongue_winking_eye: ).

In real life the M2 can be set up to be belt fed from either the left or the right side of the gun very easily, making it very useful for twin or quad-mount turrets as well as on aircraft. To facilitate this the spent casings are ejected from the bottom of the gun. The M2 is almost entirely symmetrical

In BDArmory the rounds are (seemingly) fed in from the left and spent casings are ejected out the right. This is not only unrealistic but also makes shell ejections from wing (and fuselage to some extent) mounted M2s look very strange - Either rounds eject up from one wing and down from another or rounds eject out the sides of the wings.

This issue could be fixed by adding an ejection port at the bottom of the gun, moving and rotating the shellEject transform so shells eject out of the port and retexturing the new model.

**Comment by TheDestroyer111** [comment]
LOL. It **really** doesn't matter because who tf would ever care about so minor issues.
A better solution would be implementing an editor tweakable to select which side of the gun the bullet cases eject from. If they ejected downwards, it would look weird with the gun on the fuselage (bullet cases would fly through the fuselage), and if they ejected upwards, it would look weird on many biplanes (bullet case fly thru wing).

**Comment by Wraith977** [comment]
Me, I would care about such a minor issue. (also, "such minor issues")

[This album](http://imgur.com/a/KkFOQ) shows the differences in six different instances between side ejections and bottom ejections. In five of the six instances I would say there is an improvement from having a side ejection.

One of the main advantages is that with bottom ejections all craft will be symmetrical no matter how you rotate the guns, compared to side ejections where it is impossible to have a symmetrical design.

Realistically shells were ejected through chutes when they were mounted on the cowl or behind the prop so having them fall through the fuselage is not unrealistic. Realistically shells were all ejected out the bottom of the wings or respective sides of the fuselage if they were mounted in the cowl, not half being ejected up and half ejected down...

I'm not sure what you mean about the biplanes, look at the album and the only time shells are ejected upwards is with the current side eject system...

As far as I can tell, tweakables affect all objects in symmetry, making your solution pointless, the guns would still act in the same way but both still eject in different directions.

**Comment by gomker** [comment]
Gonna be honest, this is subjective and we have a lot of other issues to tackle.
