### ISSUE TITLE
Hydra Rocket Pods Crashing Game

### ISSUE THREAD

**Issue by OMGMAN3** [PapaJoesSoup/BDArmory#690]
ISSUE TYPE
Bug Report

KSP and BDA Version

KSP - 1.7

BDA - 1.3

OS / ENVIRONMENT

Windows 10

SUMMARY
Hydra Rocket pods crash game, sometimes it could crash by selecting the weapon itself and other times it would allow you to select it but the game would crash when you try to shoot. This was done with BDA and it's dependencies only.

STEPS TO REPRODUCE
Create a new ship
Put Hydra rockets on it with a weapon manager
Launch Vessel
Open Weapons Manager and select Hydra Rocket Pods
If you didn't crash, try to fire said Hydra Rocket Pods

Log Files
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/3154962/KSP.log)

**Comment by Gedas-S** [comment]
Thank you for the report.

Based on the log, this seems like a bug in the rocket code.

**Comment by frenchmarrow** [comment]
Confirming this bug for W8.1 on both the Aerodynamic pods and the regular variant.

**Comment by Gedas-S** [comment]
Should be fixed in 1.3.1 (just out).
