### ISSUE TITLE
Slow missile issue when firing from ground rover based turret.

### ISSUE THREAD

**Issue by noeway** [PapaJoesSoup/BDArmory#70]
First create a land rover or anything that have wheels, put on a "Jernas Missile Turret" with "AIM-9 Sidewinder" missiles. Just fire all of the missile. Once there are no more missile, revert flight. Now you will notice that first 2 to 3 missiles will always slow down and then explode a few meters from your rover and then the rest of the missile will fire and track the target as usual. The worst problem is once this bug is started, it will also affect the missiles on the jet. When fired from the jet instead of going forward the missile would actually fall behind the jet and then explode. The bug will persist until i quit the game and restart a new one. However the problem never occurs if i fire the missile from jets only and never from the turret once the game started. 

Currently i'm using kerbal 1.1.3 with BD amory v0.11.1.2.

To make sure that there aren't any conflict with other mods, i reinstalled the entire game and tested the game with BD armory mod only.
In fact i've found this exact same problem on ksp 1.0.5 as well. In which the first few missile will also slowdown and explode after firing all on the ground and reverting the game.

**Comment by TheDestroyer111** [comment]
Hmm, that's weird, I never experienced that and I thought I tested the jernas turret with reverting flight many times. I'll test that later this day once I get to the PC.

**Comment by noeway** [comment]
I highly suggest that you test it with the "AIM-9 Sidewinder". Once the bug started , other first few shots of anti air missile will also be affected.

**Comment by gomker** [comment]
Please see the latest release for 1.21 that was just issued.  We will not be testing or supporting any versions below KSP 1.2 as there are significant code changes in both the game and the BDA

Let me know if this issue persists after upgrading.

Regards,

**Comment by noeway** [comment]
OK, I'll let you guys know if there is one in the new version.

**Comment by noeway** [comment]
After testing the KSP 1.2 with BD Armory v0.11.1.5 for a few days, i can no longer be able to recreate the same bug from the previous game versions. So yeah,it is safe to assume that the bug is fixed. Thanks for the suggesting to update the game.
