### ISSUE TITLE
Modular Missile Guidance always shut down all my Tanks and Engines

### ISSUE THREAD

**Issue by zkx741481546** [PapaJoesSoup/BDArmory#701]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version
KSP 1.7.0
BDA 1.2.2.2

```

##### OS / ENVIRONMENT
win10 1709

##### SUMMARY
<!-- Explain the problem briefly -->
When I was using Modular Missile Guidance ,sometimes it make my tanks and engine stop working(the green triangle in the tank's menu turns into red stop sign). 
And in Ballistic GPS model, my missile will lost control during flying
##### STEPS TO REPRODUCE
<!--
For bugs, show exactly how to reproduce the problem, using a minimal test-case.
For new features, show how the feature would be used.
-->


##### Log Files
<!-- /KSP Directory/KSP.log -->
<!-- /KSP Directory/KSP_x64_Data/Output.txt -->
<!-- You can also paste gist.github.com links for larger files -->

**Comment by jrodrigv** [comment]
this is not an issue, it was implemented like that on purpose to avoid a plane to deplet the fuel from a missile.
