### ISSUE TITLE
Game crashes when loading in 1.7.1

### ISSUE THREAD

**Issue by kani-mudcrab** [PapaJoesSoup/BDArmory#704]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Support 	    ( Need help getting something to work)

##### KSP and BDA Version

```KSP:1.7.1

```

##### SUMMARY
Game crashes when trying to load BDA parts

##### STEPS TO REPRODUCE
trying to load game

##### Log Files
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/3301399/KSP.log)
Crash Output log: [output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/3301407/output_log.txt)

**Comment by jrodrigv** [comment]
your setup is completely wrong, you have wrong versions of module managers and other mods. Everything is crashing because of that.
 
You should remove everything and create a new KSP setup from scratch.

**Comment by kani-mudcrab** [comment]
oh, that makes sense

**Comment by jrodrigv** [comment]
I recommend using CKAN to download the mods. For BDArmory you need KSP 1.7.0, Physics Range Extender and ModuleManager

**Comment by kani-mudcrab** [comment]
Where would I  go to get this CKAN manager?

**Comment by kani-mudcrab** [comment]
Also once I get CKAN  where do I put it and how do i use it?

**Comment by jrodrigv** [comment]
https://github.com/KSP-CKAN/CKAN/wiki/User-guide

**Comment by kani-mudcrab** [comment]
I figured out how to use it, downloaded BDA and the physics mod and module manager. Now the game loads fine except all the parts in BDA are useless and some are even missing.
