### ISSUE TITLE
Problem with weapon menager not detecting 

### ISSUE THREAD

**Issue by martin240** [PapaJoesSoup/BDArmory#71]

**Comment by TheDestroyer111** [comment]
Lots of people spammed the BDA wikia about this issue without providing ANY useful description, and now you did the same mistake: you provided NO details. This is the BEST way to get your issue closed without anyone even replying.

**Comment by kahogeoff** [comment]
I met the same problem when using the pre-release version of BDA for KSP 1.2.
It seems that the latest version of BDA has fixed this problem. 
So I recommend closing this issue.

**Comment by gomker** [comment]
Considering we have not yet released the 1.2 version and nothing was really specified in this issue other than a subject I will be closing this out. In the future please at the very least give the following information

* version of KSP
* version of BDA
* OS Build and Version
* Link to a full KSP log if reporting a problem

See this for more information
http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/
