### ISSUE TITLE
Torpedo produces thrust above water

### ISSUE THREAD

**Issue by meltingSnowdrift** [PapaJoesSoup/BDArmory#710]
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

```
KSP 1.7.2
BDA 1.3.1
```

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY

This is related to #459 , which appears to not have been thoroughly fixed. Torpedoes do not stop producing thrust when they leave the water, causing them to fly into the sky. A torpedo can leave the water in many situations, even when fired from underwater or into the water at another object in the water. For example, a torpedo fired into the water in a direction close to the opposite of the direction to the target may try to seek the target by turning upward through the air.

A simple approach to fixing this is to simply prevent torpedoes from producing thrust when not immersed in water. If this is done, a torpedo trying to go into the air will lose thrust and fall when it leaves the water.

The fact that this problem is noticeable also illustrates problems with current torpedo behaviour: real torpedoes do not try to fly out of the water at all in most of the cases that cause this bug. That, however, is an entirely different issue of greater difficulty and less urgency.

##### STEPS TO REPRODUCE

There is no specific reproduction procedure needed. This problem occurs whenever a torpedo leaves the water and enters the air. Try launching a torpedo upward from underwater. Also try launching a torpedo into the water from a ship where the torpedo starts out facing exactly away from the target.

**Comment by jrodrigv** [comment]
This will be fixed on next release by @SuicidalInsanity
