### ISSUE TITLE
Doesn't Load

### ISSUE THREAD

**Issue by r3dpanda10rd** [PapaJoesSoup/BDArmory#720]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Support 	    ( Need help getting something to work)
 - Bug Report   (Something is broken)

##### KSP and BDA Version

```1.7.2

```1.3.0

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY
<!-- Explain the problem briefly -->
After putting everything into my Squad folder (PhysicsRangeExtender and Modulemanager) along with the BDArmory folder in the download folder (Gamedata), I open up KSP, and it gets stuck loading "BDArmory.1.2.4.0_12302018 /GameData/BDArmormy/Parts/20mmVulcanTurret/bahaGatlingGun". I have redone it many times, and reinstalled it many times, and it still doesn't work! Please fix this! :)
##### STEPS TO REPRODUCE
<!--
Just do what I said I did in by description of the problem
-->


##### Log Files
<!-- /KSP Directory/KSP.log -->
<!-- /KSP Directory/KSP_x64_Data/Output.txt -->
<!-- You can also paste gist.github.com links for larger files -->
File Name:
BDArmory.1.3.1.0_051220191415

**Comment by jrodrigv** [comment]
You have not attached any log file. Closing until you add more information

**Comment by Gedas-S** [comment]
Everything should go into the Gamedata folder, nothing you download goes into Squad.
