### ISSUE TITLE
Scripting Autopilot

### ISSUE THREAD

**Issue by didas72** [PapaJoesSoup/BDArmory#726]
##### ISSUE TYPE
 - Feature Idea (Something new you want to see)

##### SUMMARY
Adding a way to script the autopilot function.

##### STEPS TO REPRODUCE

I hope I'm writing this in the right place, if I'm not, I'm really sorry.
I think it would be a great idea to make a API for BDA autopilot function, so that players can make their own flight profiles or just try to play around/improve the autopilot. It would be ideal to be able to assign scripts to crafts. It would also be good to be able to send a craft to another person and the script to go with it. Just for reference, including an example such as the default autopilot would definitely help new users of this function. I hope you can bring this to BDA!

**Comment by Gedas-S** [comment]
This is the right place. :)

BDA does support external autopilots, however it still has to be compiled as a separate mod. You can check out an example implementation here: https://github.com/Gedas-S/BDSimpleAI/blob/master/SimpleAI/SimpleAI.cs
But if you'd like to try writing a small mod, this is as good a place to start as any.

This is just for flight, though. The firing of the guns is done by the weapon manager, which currently does not have an API.

In-game scripting of the AI would be cool, but, unfortunately, it is unlikely to happen soon. :(

**Comment by didas72** [comment]
Ok thanks.
