### ISSUE TITLE
Incorrectly displayed (magenta-colored) tracers and tracking camera screen

### ISSUE THREAD

**Issue by stasikos** [PapaJoesSoup/BDArmory#73]
Neither gun tracers of camera screen are displaying correctly in version BDArmory.

0.11.1.5_11022016.zip downloaded from releases page.
It happens in clean KSP 1.2.1.1604 install on 64-bit Linux. Both tracers (any) and whole tracking camera screen are magenta.

Attaching my KSP.log and Player.log just in case (actually, linking, can't attach zip)
https://dl.dropboxusercontent.com/u/5113976/KSP/ziplogs.zip

**Comment by jrodrigv** [comment]
Thanks for the logs. I have reviewed them at it seems that the new shaders are not supported on OpenGL.

I will investigate this. I don't know if it is possible to fix it or not.

**Comment by stasikos** [comment]
It should be possible to fix, just because other mods with custom shaders working, like scatterer or EVE, KSP itself (it uses shaders, of course) are working. Not sure how much you dug about new way for loading shaders, I've tried to fix similar problem in HullcamVDS myself (but it had black image issue, which I managed to turn into magenta :)), found topics like this and seems like I need to get latest Unity first, as per this thread:
http://forum.kerbalspaceprogram.com/index.php?/topic/148180-shaders-loading-tutorial/&page=1
Then I'll be able to rebuild shaders for different platforms properly.
But latest Unity is not available on my platform. I'll try later to get it running on Windows. If I'll find any clues, I'll make update.

**Comment by stasikos** [comment]
Okay, seems I managed to get it work of HullcamVDS at least. It has its shader source, so I can compile and bundle it. But I can't do so for BDArmory to test. :).
How it is done now in other mods: 
1) You need separate shader bundle for each platform. You need to build two additional shader bundles for StandaloneLinuxUniversal and StandaloneOSXUniversal too. It is probably done with 
BuildPipeline.BuildAssetBundles("Bundles", BuildAssetBundleOptions.UncompressedAssetBundle, BuildTarget.StandaloneOSXUniversal);
or something like this for Unity Editor.
Then, for convenience, you need to somehow choose between them depending on platform when you load asset bundles in KSP. It seems like it is done this way in Environment Visual Enhancements and scatterer mods. They all have three bundle packages shipped and somehow load proper one.

**Comment by jrodrigv** [comment]
@stasikos Thank you very much for this information. I will keep you updated regarding this issue.

**Comment by stasikos** [comment]
Okay, I found already compiled .shader files in this git repository and tried to build them into asset bundle  for StandaloneLinuxUniversal. Then I replaced shipped BDArmory bundle. Now my tracers now look more like before, something like orange.  and camera works it shows things with little interlacing effect, but. I remember it was B&W cam before. Now it show colored picture. Is it expected? :)
So, way to fix is confirmed.

**Comment by jrodrigv** [comment]
Nice!  the targeting camera is a gray scale effect (but we had to use a new shader that is not completely gray and things like explosions are colored)

**Comment by stasikos** [comment]
Then it is probably not working well, because my camera is really true-color camera. But, at least, now I can use it.
![targeting_pod](https://cloud.githubusercontent.com/assets/429948/19988500/24c75b96-a229-11e6-9910-acd9279ca547.png)

**Comment by stasikos** [comment]
No, it seems like it is magenta when named properly. You probably can't do same thing with precompiled shaders. Don't know why bullet shader is not "precompiled" for Unity, because they look same in text.
To get really "GrayScale" I've tried to find similar shader in its virginity using Google and got one without _MinClamp parameter (probably it is from Unity Pro assets). It adds some grayscale effect, and it is even works properly for explosions too.

But, okay, it seems irrelevant to this bug as you probably have this shader in non-compiled form. I'll stop buzzing here.

**Comment by jrodrigv** [comment]
I'm working on the fix. I will attach debug binaries to get feedback  as soon as is ready :)

**Comment by jrodrigv** [comment]
@stasikos Can you try this https://1drv.ms/u/s!AixZLrjtqp-RgqcEoMRomEPi4NYMHg

**Comment by stasikos** [comment]
It seems like this time it loads properly. I see tracers, I see camera image. Not really grayscale, as you described. Red color is visible in it, especially fire and tracers.

**Comment by jrodrigv** [comment]
Nice! Thanks for the testing. Yes, I need to find a new grayscale shader :)

**Comment by gomker** [comment]
I kinda like the greyscalish / color thing that it does now :)

**Comment by DoctorDavinci** [comment]
I can confirm that this fix works on Windows 10, the latest release of Ubuntu and on OSX

Great job

**Comment by jrodrigv** [comment]
This issue is now fixed and it will be included on the next release. Thanks all.
