### ISSUE TITLE
BD armory not loading

### ISSUE THREAD

**Issue by SCPscott** [PapaJoesSoup/BDArmory#734]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version

```1.7.3

```v1.3.0

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY
When loading KSP it gets halfway through then stops at the Baha Gatling gun.
I put Bd armoury in KSP's Gamedata folder with physics range loader.
I tried to delete that file but it just got stuck again.
##### STEPS TO REPRODUCE



##### Log Files
<!-- /KSP Directory/KSP.log -->
<!-- /KSP Directory/KSP_x64_Data/Output.txt -->
<!-- You can also paste gist.github.com links for larger files -->

**Comment by kspgamer** [comment]
how did you fix it
