### ISSUE TITLE
Missile Guidance Disable when using Principia, RealFuel makes Missile fly slow

### ISSUE THREAD

**Issue by zkx741481546** [PapaJoesSoup/BDArmory#739]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version
KSP 1.7.3
BDArmory.1.3.1.0_051220191415
```

```

##### OS / ENVIRONMENT
win10 1903

##### SUMMARY
used mod:
Principia
MJ
KJR
TweakScale
AllTweak
BDA
PRE

with above mods，BDA works fun
But when I installed Principia(n-body gravity), all missiles' guidance function just stop working.
The missile just fly forward.

Also, vessel mover doesn't work with Principia, craft keep fall and crash.

And with RealFuel, some Missiles fly so slow, I guess it's because there is no RF config of BDA, hope fix these problem.
##### STEPS TO REPRODUCE
just use principa and you will see the bug

**Comment by jrodrigv** [comment]
Sorry but BDArmory was never implemented or tested with Principia. Feel
free to create a fork and implement a fix for it :)
