### ISSUE TITLE
Problem with display of trajectories/smoke of missiles

### ISSUE THREAD

**Issue by Zuboss01** [PapaJoesSoup/BDArmory#74]
Hello !

I tried the latest versions of BDA (for ksp 1.2 and 1.2.1), 0.11.1.5 and 0.11.1.4 that have just been released.
I saw 2 problems that seem to be only visual.
First -> When I fire a missile from a plane, the trajectory of the missile (visible by the smoke it emits) is not right : the smoke, and in fact even the missile itself, seem to move in the "referential/frame" of the plane.
So, instead of staying not moving after the missile, the smoke emitted by the missile moves exactly like the plane, and the missile too. It really seems that missiles and smokes of missiles are moving in the "referential" of the plane. Sometimes the missile does not even seem to explode the right place because of that. BUT this problem only happens if we look from the plane. If we look the missile flying from a fixed point of view or with the camera linked to the missile itself, the visual trajectory is okay. This is why I really think it a problem of "referential", because if we look from a fixed point of view, the referential/frame is fixed and we cannot see the problem. In the missile camera, the missile always follows a good trajectory, and explodes on the target.
Second -> The smoke emitted by missiles do not seem to be well emitted : there are few smoke, of even not at all, or emitted slowly ...

I have tried both last versions of BDA, and I am playing with ksp 1.2.0.1586 (version windows x64), on windows seven.

I really like very much this mod, and it seems to be the last problem before we can use it on the new versions of KSP.
Can you help to solve this last problem ?

Thank you very much !

**Comment by gomker** [comment]
HI, could you add your notes to issue #72 
If you could also add the following information

OS Build and Version
Link to a full KSP log

See this for details for bug reporting
http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

**Comment by gomker** [comment]
On second thought, I will keep this one open.

**Comment by gomker** [comment]
@Zuboss01  Could you provide a download of your ksp.log and output.log files as well as your OS build information.

Regards,

**Comment by Temptatiions** [comment]
You had asked me to leave the output log and other information in this issue, So here it is:
KSP Version 1.2.1 on Windows 10 64bit. BDA  v0.11.1.5

KSP and Output logs:
https://www.dropbox.com/s/y32eirmgdoj79xq/Logs.zip?dl=0

**Comment by Zuboss01** [comment]
Hello !

I have no output_log in my whole ksp folder. Where can I find it ?
I have the log file, attached to this message. I give you also the information about my OS :
KSP 1.2.0.1586 ; Windows Seven, 64 bit, SP1, current build 7601.
[ksp_log.zip](https://github.com/PapaJoesSoup/BDArmory/files/576167/ksp_log.zip)

Thanks for your help !

**Comment by Wraith977** [comment]
Also having the same issues and it seems to be all particle effects; missile exhausts, muzzle smoke and flare smoke are all affected. flying <≈ 150 metres makes particle effects jump every second or so to catch up to the craft.

[output_log](https://drive.google.com/open?id=0B4CtuMbKBheyUEpWbGVIMEVlNDQ)

I had a quick look in the log and there doesn't seem to be any errors being thrown regularly, flight begins at line 28285.

**Comment by sarbian** [comment]
I did not read your code but you most likely need to register your particle system 
FloatingOrigin.RegisterParticleSystem() or EffectBehaviour.AddParticleEmitter depending on the type of particle system. (and don't forget to removed them when done)

**Comment by jrodrigv** [comment]
Thanks @sarbian for you input! I was wondering if you can provide a code
example to use it properly (or if you can point me to a github repo commit
where it is used that would be enough)

Regards

2016-11-18 11:04 GMT+01:00 sarbian <notifications@github.com>:

**Comment by sarbian** [comment]
It is nothing special to use. When you add a ParticleSystem or a ParticleEmitter you call those with the reference. And when you destroy them (or the object that contains them) you call the equivalent remove call.

**Comment by Guard13007** [comment]
@Zuboss01 Is the issue intermittent or constant for you? I've had the same problem in v0.11.1.6 in KSP 1.2 (I do not recall if I have seen it in KSP 1.2.1) but it only occurs occasionally.

**Comment by harpwner** [comment]
I would like to confirm that in my latest NKD update for 1.2.1, this issue has become present in my weaponry. I first thought it was my addon but turns out it was an issue here too. Particles of all types seem to act strange above this altitude as well. I wouldn't doubt this to be an issue within KSP itself and not a BDArmory issue.

**Comment by sarbian** [comment]
> I wouldn't doubt this to be an issue within KSP itself and not a BDArmory issue.
And you would be wrong since I explained 2 post above you that it is something missing in BDA code.

**Comment by harpwner** [comment]
I'm sorry I really should stop posting stuff so late...
My thought was it happening with engines as well, should've read more carefully

**Comment by jrodrigv** [comment]
Hi @sarbian I've testing your suggestion using EffectBehaviour.AddParticleEmitter but sadly it is not fixing the problem. Not sure if we need to do some extra work on particles models too.

**Comment by sarbian** [comment]
Does this improve something or does it do nothing at all ?

**Comment by jrodrigv** [comment]
I have implemented the  EffectBehaviour.AddParticleEmitter on the [https://github.com/jrodrigv/DestructionEffects](url) mod and it seems to have improved it. However in BDArmory I still seeing the  issue "the smoke, and in fact even the missile itself, seem to move in the "referential/frame" of the plane.

**Comment by sarbian** [comment]
I am not familiar with BDA code. Can you point me to where I could have a look ? I may have some free time over the weekend.

**Comment by jrodrigv** [comment]
Sure! I've seen some of your work on SmokeScreen and I think you should know one trick or two ;)

So regarding emitters and BDA the classes using emitters that are causing obvious issues are

https://github.com/PapaJoesSoup/BDArmory/blob/support/BahaTurret/FX/BDAGaplessParticleEmitter.cs

**MissileLauncher.cs**
[https://github.com/PapaJoesSoup/BDArmory/blob/support/BahaTurret/MissileLauncher.cs#L136#L201](url)
```
List<KSPParticleEmitter> boostEmitters;
List<BDAGaplessParticleEmitter> boostGaplessEmitters;
List<KSPParticleEmitter> pEmitters;
List<BDAGaplessParticleEmitter> gaplessEmitters;
```
**CMFlare.cs**
[https://github.com/PapaJoesSoup/BDArmory/blob/support/BahaTurret/CounterMeasure/CMFlare.cs#L12#L13](url)

There are more classes using emitters but I think if we find a solution for the Flare and the Missiles then I will be able to refactor the rest.

**Comment by jrodrigv** [comment]
Fixed!
