### ISSUE TITLE
When i try and load KSP it gets stuck on the loading expansion page. How can i fix it?

### ISSUE THREAD

**Issue by Belllover** [PapaJoesSoup/BDArmory#742]
https://github.com/PapaJoesSoup/BDArmory/releases

Bug Report

KSP Version 1.8.1
BDA Version 1.3.1

Windos OS / ENVIRONMENT

SUMMARY
When i try and load KSP it gets stuck on the loading expansion page

**Comment by jrodrigv** [comment]
there is no release of BDArmory for KSP 1.8.1 yet.
