### ISSUE TITLE
camera not working

### ISSUE THREAD

**Issue by bigboimeems** [PapaJoesSoup/BDArmory#745]
- Bug Report   (Something is broken)

##### KSP and BDA Version
1.8.1

1.3.2

##### OS / ENVIRONMENT
Mac OsX 10.14.6

##### SUMMARY
All cameras (targeting pod, targeting ball) and radar cross section are block magenta and do not work

##### STEPS TO REPRODUCE
Just activate any camera and nothing shows up in the camera image
<img width="808" alt="Screenshot 2019-11-25 at 17 51 54" src="https://user-images.githubusercontent.com/58184489/69565244-76ca9180-0fac-11ea-8f26-ee1f82f1f6fc.png">

**Comment by jrodrigv** [comment]
I need your KSP.log file please

**Comment by bigboimeems** [comment]
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/3888229/KSP.log)

**Comment by jrodrigv** [comment]
You are running KSP using (OpenGL 4.1 INTEL-12.10.14) which may be the reason for your crash. Only DX11 GPUs are compatible.

**Comment by bigboimeems** [comment]
Makes sense. Thanks for that!
