### ISSUE TITLE
When using wing commander attack pos command frequently disappears

### ISSUE THREAD

**Issue by NiamiTV** [PapaJoesSoup/BDArmory#748]
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

KSP 1.8.1

BDA v1.3.2

##### OS / ENVIRONMENT

Windows 10

##### SUMMARY

When using wing commander, if I set an attack pos command the marker disappears after a few seconds or immediately

If it doesn't disappear immediately the pilot begins to fly to the marker but does nothing else

##### STEPS TO REPRODUCE
Takeoff in a plane and set an "attack pos" command anywhere

It disappears after the mouse moves away or after a few seconds

##### Log Files
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/3907235/KSP.log)

**Comment by Gedas-S** [comment]
The command may have a misleading name.

The "Attack pos" doesn't actually tell the craft to attack the selected position, it's just "go to position, combat speed" (as opposed to "go to position, casual speed" for "Fly to pos").

Once the craft is in (or above) the position, the command will end, and the craft will circle around the selected position.

If this does not clarify what you're seeing, could you describe your scenario in more detail? How far away is the selected position? Could you post a screenshot of your setup?

I'm seeing some errors in the log, but they don't seem to be wing commander related.

**Comment by NiamiTV** [comment]
That's exactly what happens, thanks for clearing it up
