### ISSUE TITLE
Lead asisst aimer for fixed guns are broken

### ISSUE THREAD

**Issue by MuricanJeb** [PapaJoesSoup/BDArmory#75]
I have a bug report. Do you remember that aim asisst thing that told us where do shoot to shoot down planes when we use a fixed gun?

It won't show up. It still shows the spiked circle if I lead my enemy right, but now I just wasted 10 minutes of my life trying to aim.

If I need to prvide a log, please notify me and I will post it on dropbox.

**Comment by SpannerMonkey** [comment]
Confirmed.  Associated log error
`[EXC 23:26:53.262] NullReferenceException: Object reference not set to an instance of an object
	BahaTurret.BDGUIUtils.DrawTextureOnWorldPos (Vector3 worldPos, UnityEngine.Texture texture, Vector2 size, Single wobble)`

**Comment by gomker** [comment]
I can get the leading indicator to display by using Radar Lock and Ground turret with "Slaved" turrets enabled. 
Reviewing logic around aim prediction here https://github.com/PapaJoesSoup/BDArmory/blob/master/BahaTurret/ModuleWeapon.cs#L1899

**Comment by MuricanJeb** [comment]
@gomker I'm talking about fixed guns like the hidden vuclan or .50 cal browning machine gun.

@SpannerMonkey Alright, thanks for the info.

**Comment by gomker** [comment]
The notes are more for us to back track the issue in code. It's not very clear how this is triggered for fixed weapons and having a case in which we can make it work will allow us to get there faster.

**Comment by gomker** [comment]
@MuricanJeb  Just thought of something , since I had not used this feature much , can you tell me how it usually displayed, did it require a radar lock? If so was "slaved turret" enabled? 
The AI does not seem to have an issue so target leading is getting triggered there.

**Comment by MuricanJeb** [comment]
@gomker Yes, it required a Radar Lock and Slave Turrets was enabled. I think the reason the AI is good at it is because heavily accurate.

**Comment by gomker** [comment]
@jrodrigv  
Not sure what this Krakensbane check is accomplishing 
https://github.com/PapaJoesSoup/BDArmory/blob/master/BahaTurret/ModuleWeapon.cs#L1879

I can say during debug the difference in when the leading aimer "greenDotTexture" is not drawn as this check fails.

The Krakensbae.SqrThreshold = 25 and the velocity is usually a number like 13000f for a say for a plane going 120 m/s over surface.

**Comment by gomker** [comment]
Update, taking out the Kranensbane check fixes the issue and I do not see any ill effects so far. From what I understand Krakensbane checks are about accounting for floating point errors and  vessel velocities, not sure why we need it in the code that triggers aimer drawing.

**Comment by jrodrigv** [comment]
Nice one. I didn't know what was the Kranensbane check. I will test this solution

**Comment by MuricanJeb** [comment]
Alright, thanks for helping guys!

**Comment by jrodrigv** [comment]
@MuricanJeb Can you try this debug version of BDArmory https://1drv.ms/u/s!AixZLrjtqp-RgqcF97cp8mC2Oqg8CA ?

**Comment by gomker** [comment]
@jrodrigv  I have not been able to find anything recent on this, api is very thin and wiki is way out of date , apparently it was implemented in early pre 1.x releases

http://forum.kerbalspaceprogram.com/index.php?/topic/76772-more-object-nesting-in-active-scenes-object-consolidation-and-krakensbane/&do=findComment&comment=1239491

> It's the technique used to tame the deep space Kraken. Before it was implemented, all coordinates in       KSP were given in reference from the body a ship was orbiting; this was sufficient when tooling around in Kerbin's SOI but when orbiting Kerbol there wasn't enough precision in such long distances, so parts would flutter and the ship would shake apart.

 > The  krakensbane solution was to make the ship the origin of the coordinate system, so the distances to the parts of the ship had sufficient precision, even in deep space, to avoid kraken effects. The tradeoff is that the orbital calculations become more difficult to implement and debug (the center of the SOI is the simplest origin, calculation-wise).

https://kerbalspaceprogram.com/api/class_krakensbane.html

http://wiki.kerbalspaceprogram.com/wiki/API:Krakensbane

I can see this being relevant in certain situations

**Comment by gomker** [comment]
Issue #77 is corrected by this fix as well in my tests.

**Comment by MuricanJeb** [comment]
@jrodrigv Sorry for late reply, I didn't get the notifaction. But yes, I will test it right now.

**Comment by MuricanJeb** [comment]
I am proud to annoce that @gomker s fix worked.

Since the problem is solved, I will now close this.

**Comment by Guard13007** [comment]
(You really shouldn't change the title of an issue just because it was fixed. That ruins trying to search for it later. Just saying...)

**Comment by gomker** [comment]
@MuricanJeb  Yeah, I switched back the title. We cross reference the git commits and pull requests notes for comprehensive docs. Github keeps track of it all and it makes for a nice view when checking history of changes, Visual studio even integrates them.  I can see who made the changes, when and why.

**Comment by MuricanJeb** [comment]
Alright then.

Now all problems are taken care of here now.
