### ISSUE TITLE
Flir Ball and targeting pod displaying purple even when not forcing open gl 

### ISSUE THREAD

**Issue by Jesys** [PapaJoesSoup/BDArmory#755]
- Bug Report   (Something is broken)

KSP version 1.8.1, BDA version 1.3.2.0

MacOs Catalina

Summary: The Flir ball camera display is purple, forced metal instead of opengl and bug still occurs. 
( i have installed the Module manager for 1.8.1 and range extender too)

STEPS TO REPRODUCE:
Install BDA 1.3.2.0 and run ksp on 1.8.1.

Log Files
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/4233483/KSP.log)

**Comment by jrodrigv** [comment]
After reviewing your log, it seems your GPU is not DX11 compatible. Only
GPUs that are DX11 compatible will work with current BDArmory shaders.
