### ISSUE TITLE
Bomb aimers do not work

### ISSUE THREAD

**Issue by Skyer25** [PapaJoesSoup/BDArmory#77]
http://imgur.com/J4abKf6
they activate while taking off then they shut off for no reason

**Comment by gomker** [comment]
@Skyer25  Can you provide the following 

- version of KSP
- version of BDA
- OS Build and Version
- Link to a full KSP log
- See this for more information
http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

**Comment by gomker** [comment]
Confirmed bomb aimer not showing up in cursory tests. Looking into it now.

**Comment by gomker** [comment]
Steps to reproduce 

- Launch vessel
- Before takeoff - select a bomb type weapon - bomb aiming reticle displayed
- Switch to another weapon, upon switching back to bomb aiming reticle is no longer displayed
- Other aiming reticles are not affected

**Comment by stasikos** [comment]
I'm noticed something weird with bomb reticles too. I'm playing on Linux x64, 1.2.1 and v0.11.1.5.
They actually don't disappear completely but they do appear to be right on ground under plane when you fly. Sometimes they seem to start tracking plane speed and work properly, it can happen right after dropping the bomb or when you takeoff, but when it explodes or you are flying everything returns to the "be right under your belly" situation.
Here you can find my logs too. It is clean KSP install with HullcamVDS and MM only. I took stock Osprey jet plane and attached 4xMk83 bombs to it with missile rails. (But it makes no sense if you use rails or not)

https://dl.dropboxusercontent.com/u/5113976/KSP/ziplogs1.zip

**Comment by Skyer25** [comment]
KSP 1.2
BDA 0.11.1.5
OS Windows 10 64-bit
http://imgur.com/a/XIvEJ
http://www.mediafire.com/file/fctjb3q5kjldvys/output_log.txt Log

**Comment by gomker** [comment]
I can confirm the bomb reticle appears underneath the plane during flight - this points more to a targeting code issue.

**Comment by gomker** [comment]
I believe fix pending for #75 corrects this as well. Went back to debug and its working now with those changes in place

**Comment by gomker** [comment]
Fixes Merged.

**Comment by stasikos** [comment]
Cannot confirm something changed in BDArmory.0.11.1.6_11082016.zip (from release page).
It still draws bomb marker right under plane after take off. Repeat steps are same as above.
The only way to bomb accurately is still 90 degree dive.

**Comment by gomker** [comment]
@stasikos  Just to be sure, when you updated, delete the entire BDArmory folder and replace contents. Just trying to limit any possible errors in install. 
Also - there should be a BDA/craft directory where you will find - BDA - TestPlaneAI - v3.craft
This is our standard test plane, let me know if you see the issue with this craft as I will test with the same exact one.

**Comment by gomker** [comment]
Also note that the bomb aimers and bombs themselves work on a ballistic targeting arc. Speed and altitude will affect the point of aim, and when the targeting code cannot find an "arc" that is proper the aimer will disappear. I think what is happening is the aimer goes to the bottom of the plane when it should be hidden all together as it has not valid target arc to display

**Comment by stasikos** [comment]
1) Repeated again with clean install - Nothing but Squad + ModuleManager.dll in GameData before installation.
2) Repeated with TestPlaneAI with Mk82, JDAM, SnakeEye and cluster bombs, they have same behaviour.

Detailed: 
- If bomb is selected when takeoff happens - it really tracks plane speed while plane is rolling on runway.
- After takeoff and in 10 degree climb up to ~200 m altitude it still works correctly. Above ~200m it drops to the ground (breaks).
- When pitch angle is above ~20 degree it disappears completely (like if it "can't find arc").
- When in dive (at different angles) or in level flight it is always under the plane and speed has no effect on it. It only appears to be working properly when altitude is very low, like less than ~170 m above sea (when flying above water).
- It seems like it "fixes itself" if bomb is dropped and is falling right now and you still have next one on plane. But when bomb explodes its animation happens right where properly working bomb aimer is (probably another bug related to animation, but, who knows, how it can be related).

Logs, just in case.
https://dl.dropboxusercontent.com/u/5113976/KSP/ziplogs2.zip
