### ISSUE TITLE
Reloadable Missile Rail

### ISSUE THREAD

**Issue by j-awe** [PapaJoesSoup/BDArmory#775]
- Support

How to obtain the part? I know it must be added in, could someone help with this?

**Comment by ChippedChap** [comment]
You can't. BDArmory has a module called ModuleMissileRearm, but as of now no BDArmory parts actually use this module. 

It's also difficult to add ModuleMissileRearm to an existing part. A part needs custom transforms for the module to work. I did write some code for a module that lets a user add new transforms to an existing part through only cfg edits, but it's probably going to end up being very buggy and isn't in an official release anyway.

ModuleMissileRearm's code is borrowed from a module called ReloadableRail from a mod called Aircraft Carrier Accessories written by @flywlyx. If you want reloadable rails that mod adds the next best thing.

**Comment by j-awe** [comment]
I just realised I have that mod and the part also. Thanks.
