### ISSUE TITLE
Turrets and Ammo

### ISSUE THREAD

**Issue by Mobmaker55** [PapaJoesSoup/BDArmory#778]
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

```
KSP 1.9.1 
**OTHER MODS**
ExtraplanetaryLaunchpads v6.7.2
LunaMultiplayer  Release 0.25.0
ThrottleControlledAvionics 3.6.2.2
KerbalAlarmClock 3.13
PhysicsRangeExtender 1.19
```
BDArmory 1.3.4
##### OS / ENVIRONMENT
Windows 10 

##### SUMMARY
No matter what kind of ammo I put on my vehicle, turrets will not see the ammo. This isn't too much of a problem, as I can just tick "infinite ammo", right? Wrong. Guard mode seems to completely ignore "infinite ammo", and relies on there being actual ammo (which there is on the ship). To make sure I wasn't being stupid, I put one of EVERY ammo box on the ship. My Goalkeeper still would not fire. I then followed to put one of every gun and gun turret, and none of them fired. Turning on infinite ammo does allow me to use the weapons manually, but Guard mode will still not work. 

##### STEPS TO REPRODUCE
Make vehicle. Add gun. Add associated ammo (or all the ammo types, if you aren't sure.) Launch. Open BDArmory Weapon Manager. See that it says "0 Ammo".

##### Log Files
[KSP.log.txt](https://github.com/PapaJoesSoup/BDArmory/files/4705091/KSP.log.txt)
^It wouldn't let me send just ksp.log, it required it be a txt.

**Comment by Mobmaker55** [comment]
Hey can I get an assist it's been almost a year

**Comment by VladTheEvilCat** [comment]
Have you tried reinstalling the mod?

**Comment by Mobmaker55** [comment]
I've tried a lot. I ended up just quitting that game and haven't gone back to it 🤷‍♂️ 
thanks for the eventual response tho 🙄
