### ISSUE TITLE
Radar not working

### ISSUE THREAD

**Issue by KERBALZ** [PapaJoesSoup/BDArmory#79]
I open the radome radar and try to find a target, but nothing appears, not even with boarsight

**Comment by gomker** [comment]
When reporting issues please provide the following information:

- version of KSP
- version of BDA
- OS Build and Version
- Link to a full KSP log if reporting a problem
- See this for more information
http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

**Comment by gomker** [comment]
This appears to be a duplicate of Issue #73 - There are known issues with Shaders being incorrect for OSX and Linux - this is being addressed. 
The shaders will affect the way Radar works as well.
