### ISSUE TITLE
Auto speed limit for the AI so it doesn't stall and wobble back-and-forth

### ISSUE THREAD

**Issue by Nerfclasher** [PapaJoesSoup/BDArmory#80]
The AI is not smart to know that if you don't keep some thrust you will lose speed and start wobbling uncontrollably and lose more speed forcing the AI to throttle up and continuing a unstoppable pattern which in FAR or stock could lead to a stall

**Comment by Nerfclasher** [comment]
Correcting this to raising the speed limit for the AI so it doesn't stall and wobble back-and-forth

**Comment by DoctorDavinci** [comment]
Please provide more information as to what it is you want to be fixed/changed

As has been explained to you many times in the past, providing a vague description of an issue only serves to waste valuable resources just trying to figure out what it is you are trying to convey

Please refer to the following video concerning Bruce and the Dave's he knows:
https://www.youtube.com/watch?v=dEGCdVADLWY

**Comment by jrodrigv** [comment]
I have done some assumptions updating the tittle and adding the label enhancement

**Comment by Nerfclasher** [comment]
You are correct on that this is a enhancement issue. GitHub went rogue on me when I was typing and it submitted the issue as stated in the second post

**Comment by DoctorDavinci** [comment]
I'm wondering if utilizing the Pitch Ki settings might solve this issue

If your craft isn't balanced propery then you introduce instability which can be compensated for with Pitch Ki

Also setting up your control surfaces is essential ... when designing craft to work with the AI Pilot you need to compensate for how it will try to fly it ... Leaving the control surfaces with the preset deflection values is going to cause you problems as your control surfaces need to be tuned to your craft

There is more to tuning your design for the AI Pilot than meets the eye

**Comment by gomker** [comment]
Old issue with no response
