### ISSUE TITLE
Loading stuck in KSP 1.12.0

### ISSUE THREAD

**Issue by Snek-str** [PapaJoesSoup/BDArmory#822]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Support 	    ( Need help getting something to work)

##### KSP and BDA Version

---KSP: 1.12.0

---BDA: V1.3.4

##### OS / ENVIRONMENT
Windows 11 Pro
##### SUMMARY

I get stuck on loading this:
![image](https://user-images.githubusercontent.com/87203360/205711732-ace2dc36-6b88-47b5-bac3-79b47a2942ab.png)
It gets stuck there no matter how long I wait.
##### Log Files

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/10156784/KSP.log)

**Comment by PapaJoesSoup** [comment]
version 1.3.4 of BDA does not work with KSP 1.12.x.  Please use either BDA+ or version 1.3.5 (Beta), found here in the releases folder.    Preferably use BDA+, which is more up to date and adds many new features.  It can be found here:  

https://forum.kerbalspaceprogram.com/index.php?/topic/209092-19x-112x-bdarmory-plus-bda-v1551-2022-11-27/
