### ISSUE TITLE
weapons manager not working (ksp 1.12.10) 

### ISSUE THREAD

**Issue by nutenjoyer** [PapaJoesSoup/BDArmory#825]
I have a weapons manager on my vehicle but when I open the weapons manager GUI it says there's no weapons manager installed. I'm have BDArmory Plus 1.5.9.2 and BDArmory Extended 1.09.1.

**Comment by PapaJoesSoup** [comment]
BDArmory Plus is the latest version but it is supported by another team.  Please look up BDArmory Plus on the Kerbal forums and look at their requested method to get support.  From first glance without any information on your install or how you installed it, I would say there may be an issue in the installation locations.
