### ISSUE TITLE
The nothing closes ksp

### ISSUE THREAD

**Issue by ELJOKER900** [PapaJoesSoup/BDArmory#826]
##### ISSUE TYPE
 - Bug Report   (Something is broken)
 
##### KSP and BDA Version #####
Ksp 1.12.4

BDA v1.5.9.4 (for ksp 1.12.X)

##### OS / ENVIRONMENT
Windows 11 home
10.0.22621 compilation 22621

##### STEPS TO REPRODUCE
do anything in the game and there's a chance it'll crash on its own

##### Log Files

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/11123872/KSP.log)

There's no are KSP_X64 Data/Output,txt because i don't find it

**Comment by PapaJoesSoup** [comment]
Please note that the version of BDA you have referenced is not found on this fork.  Check the KSP forums for the correct OP  BDArmory+>  the OP of this fork:   https://forum.kerbalspaceprogram.com/index.php?/topic/178156-112x-bdarmory-continued-v135-beta-1292022-vessel-mover-camera-tools-bdmk22-destruction-effects-burn-together/  Will lead you there
