### ISSUE TITLE
Pin Me - Development uncontinued.

### ISSUE THREAD

**Issue by BraveCaperCat2** [PapaJoesSoup/BDArmory#828]
The dev will not respond to issues and no longer supports the mod.

**Comment by PapaJoesSoup** [comment]
First, This mod has been superseded by BDArmoryPlus.  I check the forums for any issues that I may wish to fix, but the supported version is no longer this fork.  [Check the OP of this fork for information on BDArmoryPlus](https://forum.kerbalspaceprogram.com/index.php?/topic/178156-112x-bdarmory-continued-v135-beta-1292022-vessel-mover-camera-tools-bdmk22-destruction-effects-burn-together/)
Second, if the version file you have is 0.2.2.1, then you are using a woefully outdated version of this mod.  The latest version on this fork,  Beta 1.3.5 does work with KSP 1.12.5.  

Third, with all due respect, some research on the forum threads would have led you to the correct solution.  Let me know when you have installed that version or BDArmory+ if you have issues.

**Comment by BraveCaperCat2** [comment]
> First, This mod has been superseded by BDArmoryPlus. I check the forums for any issues that I may wish to fix, but the supported version is no longer this fork. [Check the OP of this fork for information on BDArmoryPlus](https://forum.kerbalspaceprogram.com/index.php?/topic/178156-112x-bdarmory-continued-v135-beta-1292022-vessel-mover-camera-tools-bdmk22-destruction-effects-burn-together/) Second, if the version file you have is 0.2.2.1, then you are using a woefully outdated version of this mod. The latest version on this fork, Beta 1.3.5 does work with KSP 1.12.5.
> 
> Third, with all due respect, some research on the forum threads would have led you to the correct solution. Let me know when you have installed that version or BDArmory+ if you have issues.

1. Which points here.
2. That was the latest version on curseforge or spacedock, (not sure which) FOR THE CONTINUED VERSION
3. I won't read forum threads 100 pages long or whatever.
