### ISSUE TITLE
Memory Leak When Viewing BDArmory Tab

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#9]
gajbooks commented on May 5

Memory leaks when viewing the BDArmory tab with all the parts in it. Vanilla install + BDArmory only. Causes lag/CTD after long enough. Resets upon scene change. Shoots up to 11 GB RAM usage in about half a minute with more third-party BDArmory parts.

The above came from here: [https://github.com/BahamutoD/BDArmory/issues/48](url)

---

There is additional info here: [http://forum.kerbalspaceprogram.com/index.php?/topic/76926-11-bdarmory-v01101-compatibility-fixes-apr-23/&page=302#comment-2601430](url)

---

I can confirm that there is some meat on this bone ... Fresh install with only BDArmory

One thing I have noticed is that if I open the BDA tab I get an immediate spike of 8-10% usage on my CPU by KSP, however this also happens when I open the utility tab so there is definitely more digging to do on this subject

**Comment by gomker** [comment]
Is this still a valid issue in current version?

**Comment by jrodrigv** [comment]
I'm going to close this issue, I didn't see anything strange so far. We can always re-open if it becomes relevant again.
