### ISSUE TITLE
no weapon manager toolbar button appears 

### ISSUE THREAD

**Issue by tooyun** [PapaJoesSoup/BDArmory#93]
I already put the weapons manager on my jet but the BDA Weapon Manager say **_No weapon manager found_**??Why??Please help me
![screenshot29](https://cloud.githubusercontent.com/assets/23555305/20431858/46bf90e2-add7-11e6-9284-9631abc49109.png)

**Comment by jrodrigv** [comment]
Please try to delete you entire BDArmory folder, download the latest
release from github and try again.

2016-11-18 14:41 GMT+01:00 tooyun <notifications@github.com>:
