### ISSUE TITLE
Guard fire missiles off target

### ISSUE THREAD

**Issue by riccardocagnasso** [PapaJoesSoup/BDArmory#94]
I was experimenting with static turrets/ships/vls etc and i was unable to make them fire missiles.
After i lot of research i understood that it was not firing because the target was not "head on" on the missile. You know, the green circle that show the optimal direction to fire the missile at the target.

This makes somewhat sense on planes, but makes static turrets unusable. And doesn't really make sense because radar guided missiles are actually able to steer and engage targets when fired (manually) vertically.

It would be useful to have a flag to tell the missile and/or weapon manager off bore.

**Comment by gomker** [comment]
Thanks for the info, we recently added some guard mode code to improve how they behave against AA missiles and I have seen some issues as well. This will help track down where we need to focus our efforts.

Noting that this may be related to #85

**Comment by gomker** [comment]
New targeting parameters added in next release. Also missile FOV corrects for this if designed. See SpannerMonkey's [SMArmory ](https://spacedock.info/mod/1195/SM_Armory%20)for examples of Anti ship missiles that behave in a way that you desire.
