### ISSUE TITLE
BDArmory refactor

### ISSUE THREAD

**Issue by riccardocagnasso** [PapaJoesSoup/BDArmory#95]
### Disclaimer
This may very well be considered off topic. If that's the case, i will understand when you close the issue. No hard feelings.

I was trying to fix #94 myself, so i cloned the code and... oh boys, the mess. I'd dare to say that the BDArmory codebase at the moment it's not very well organized.

Everything is on the same "level": there's no namespace hierarchy, there's no class hierarchy, therefore there is no clear API between major modules. Because, well, there are no major modules.

The lack of hierarchy whatsoever is particularly troubling when you consider that there are a lot of "optional" stuff in BDArmory. I love the BDRotaryRail part, but i can definitely live without it. On the other hand BahaTurret.cs seems pretty important. But there's no clear indication of this in the code structure.

Naming consistence seems also an issue. E.g. the WeaponManager module seems to be still called MissileFire. Things like doesn't really help to develop a stable working software.

What I'm proposing here is a big refactor of the BDArmory codebase, at the very least from namespace/directories point of view. A more complete approach would be to divide the project in major different modules with a clear API between them. I reckon this is a BIG, time consuming task, but the benefits in the long term would worth it.

If there's some interest in this process, i could dwell more in to the code, trying to understand it better and come up with a new organization for the codebase.

**Comment by jrodrigv** [comment]
Hi @riccardocagnasso you are actually reading our thoughts. We have already started a branch to work on this refactor. 

Every idea to improve BDArmory is more than welcome. And If you are interested to colaborate with us or even join the BDArmory team let us know ;) - @PapaJoesSoup @gomker

**Comment by Nerfclasher** [comment]
@riccardocagnasso if you look this is being worked on the refactor branch

**Comment by Nerfclasher** [comment]
I notice the refactor branch is gone

**Comment by gomker** [comment]
JR did some merge magic and the beginnings of the refactor are in the support branch now

**Comment by riccardocagnasso** [comment]
@gomker i don't know the logic you are using in this refactor, but this is what I would do if I were rewriting this from scratch.

I will break functionalities in modules and then i would create part templates that contain these modules and coordinate them then i would instantiate them to create parts.

Let me make an example. You can create a GuidanceModule class and then RadarGuidance, IRGuidance, GPSGuidance. WarheadModule then FragWarhead, ContinuousRodWarhead, HEATWarhead etc.

Then you create the MissileTemplate that has one (or more) GuidanceModule, one or more WarheadModule, one EngineModule (let's say) etc and the code to glue all this.

Now you can instantiate an AMRAAM being a MissileTemplate with RadarGuidance, ContinuousRodWarhead and AMRAAMEngine.  Or a anti naval missile with GPSGuidance, RadareGuidance, HEATWarhead, some engine.

This could work for radars (ScanModule, TrackingModule) turrets, guns etc etc

**Comment by riccardocagnasso** [comment]
Of course in this case the interface should be defined per Module basis.
e.g. the GuidanceModule would take some sort of target and provide you with guidance or target position. Then all the modules implementing GuidanceModule will behave accordingly.

This schema will probably work well with Dependency Injection

**Comment by jrodrigv** [comment]
Thanks @riccardocagnasso I like you idea to split everything into modules and without any doubt it is something that I would like to try during the next year. It is going to be a massive effort to rewrite everything.

So far, @gomker have a done a simple reorganisation of folder and classes.  And in my case during the Modular Missiles development I took a small step creating an abstract class called MissileBase to extract the common logic between ModularMissiles and LegacyMissiles.

**Comment by riccardocagnasso** [comment]
@jrodrigv well it makes sense to me. A weapon is actually composed of different parts with different functions in reality. Of course a good friend of me used to criticize OOP saying that you can create a Char class composing Atoms but ... oh well, i think this will work.

Anyway, enough ranting. Yup, refactoring all the stuff is going to be a big hell of a job. But if you start to rewrite the whole thing, well, you don't actually need all the parts that are in bdarmory now from day 0.

**Comment by gomker** [comment]
Cleaning up and closing out issues.

**Comment by riccardocagnasso** [comment]
@gomker I understand (I **very** understand **very** well) that you need to keep the issues "clean" and close up stuff like this. But I think that would be useful to have some place where to discuss long term architectural choices for a refactor. Maybe this discussion can be moved someplace better?
